-- Reid Hoffman public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='LinkedIn co-founder, investor, AI-company co-founder, author and host across distinct institutions.',
    "summary"='A multi-institution portfolio separating companies, funds, boards, cofounders, employees, IP, media rights, historic securities, political activity and personal economics.',
    "inclusionRationale"='Tests whether a founder-investor-media portfolio can be represented without conflating roles, entities, ownership, valuation, institutional output, adverse events, sole causality or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.88,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='reid-hoffman';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_rh10_li_s1','https://www.sec.gov/Archives/edgar/data/1271024/000119312511131453/ds1a.htm','LinkedIn Form S-1/A','SEC / LinkedIn','primary_regulatory_filing','2011-05-09T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_rh10_li_merger','https://www.sec.gov/Archives/edgar/data/1271024/000110465916130837/a16-14187_1prem14a.htm','LinkedIn merger proxy','SEC / LinkedIn','primary_regulatory_filing','2016-07-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_rh10_ms_deal','https://www.sec.gov/Archives/edgar/data/789019/000119312516619689/d116815dex991.htm','Microsoft LinkedIn acquisition presentation','SEC / Microsoft','primary_transaction_filing','2016-06-13T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_rh10_ms_ar25','https://www.microsoft.com/investor/reports/ar25/index.html','Microsoft 2025 annual report','Microsoft','primary_company_filing','2025-07-30T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_rh10_ms_exit','https://www.reuters.com/business/linkedin-co-founder-reid-hoffman-step-down-microsofts-board-2026-06-05/','Hoffman will not seek Microsoft board re-election','Reuters','independent_journalism','2026-06-05T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_rh10_bio','https://www.reidhoffman.org/','Reid Hoffman biography','Reid Hoffman','first_party_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_rh10_podcasts','https://www.reidhoffman.org/podcasts/','Reid Hoffman podcasts','Reid Hoffman','first_party_media_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_rh10_manas','https://manasai.co/news/manas-ai-launches-to-transform-discovery-of-novel-cancer-medicines','Manas AI launch','Manas AI','primary_company_announcement','2025-01-27T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_rh10_alabama','https://www.axios.com/2018/12/26/reid-hoffman-apologizes-disinformation-alabama-special-election','Hoffman apologizes over Alabama disinformation funding','Axios','independent_journalism','2018-12-26T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_rh10_epstein','https://www.axios.com/2019/09/12/reid-hoffman-jeffrey-epstein-mit-donations','Hoffman apologizes for Epstein interactions','Axios','independent_journalism','2019-09-12T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_rh10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'formation_history','LinkedIn filings identify Hoffman as one co-founder and document bounded executive and board roles.','distributed_creation','primary_filing','unreviewed',NULL,'Co-founder and former executive within a multi-person company.','No sole-founder, sole-labor or permanent-control claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_rh10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'ownership_boundary','LinkedIn’s 2016 proxy reports holder- and security-specific beneficial interests.','ownership_boundary','primary_filing','unreviewed',NULL,'Use only the filing date, holder, class and attribution definition.','No current percentage, wealth or simple ownership carry-forward.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_rh10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'transaction_metric','Microsoft’s LinkedIn acquisition was valued at approximately $26.2 billion.','institutional_finance','primary_filing','unreviewed',NULL,'Company-level transaction value.','Not personal proceeds, wealth or sole-created value.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_rh10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'role_transition','Hoffman joined Microsoft’s board in 2017 and will not seek re-election at the 2026 annual meeting.','role_transition','corroborated','unreviewed',NULL,'Director through the documented 2026 transition.','No post-meeting carry-forward or forced-removal inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_rh10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'investment_role','Hoffman is publicly identified as a Greylock partner.','formal_role','observed','unreviewed',NULL,'Partner role in a venture firm.','No personal ownership of fund assets, portfolio companies or returns.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_rh10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'ownership_boundary','Microsoft identifies Hoffman as an Inflection co-founder and director and separates holder-specific sub-10% interests.','ownership_boundary','primary_filing','unreviewed',NULL,'Dated, holder-specific related-party interests.','No complete cap table, current percentage, license economics or unilateral control.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_rh10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'formation_history','Manas AI was co-founded with Siddhartha Mukherjee and operates through an interdisciplinary team and Microsoft infrastructure.','distributed_creation','observed','unreviewed',NULL,'Co-founder within a scientific and institutional team.','No sole invention, approved-drug, patient-outcome or sole-causation claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_rh10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'media_role','Hoffman hosts or co-hosts podcasts and co-authors books with separately credited collaborators.','distributed_media','observed','unreviewed',NULL,'Named hosting and co-authorship roles.','No sole ownership of brands, feeds, recordings, publishing or derivative rights.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_rh10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'adverse_event','Hoffman apologized for unknowingly funding a group tied to Alabama election disinformation and disavowed the tactics.','adverse_evidence','attributed','unreviewed',NULL,'Describe funding, stated lack of knowledge and apology together.','No unsupported knowledge, intent, causality or adjudication inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_rh10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'adverse_event','Hoffman apologized for interactions with Epstein connected to MIT fundraising.','adverse_evidence','attributed','unreviewed',NULL,'Describe documented interaction, context and acknowledgment.','No expansion beyond supported events or psychological inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_rh10_c11',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'claim_restriction','No reviewed record establishes complete private cap tables, fund economics, contracts, IP schedules, personal compensation, media rights, labor attribution, causal impact or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified or unmeasured.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_rh10_c01','obs_claim_rh10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1271024/000119312511131453/ds1a.htm' LIMIT 1),'supports',NULL,'Director biography and governance','Executive chronology and distributed formation.',CURRENT_TIMESTAMP),
('obs_ev_rh10_c02','obs_claim_rh10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1271024/000110465916130837/a16-14187_1prem14a.htm' LIMIT 1),'supports',NULL,'Beneficial ownership','Dated holder- and security-specific snapshot.',CURRENT_TIMESTAMP),
('obs_ev_rh10_c03','obs_claim_rh10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/789019/000119312516619689/d116815dex991.htm' LIMIT 1),'supports',NULL,'Transaction presentation','Company transaction value separated from personal economics.',CURRENT_TIMESTAMP),
('obs_ev_rh10_c04','obs_claim_rh10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/linkedin-co-founder-reid-hoffman-step-down-microsofts-board-2026-06-05/' LIMIT 1),'supports',NULL,'June 2026 disclosure report','Transition endpoint and no-disagreement statement.',CURRENT_TIMESTAMP),
('obs_ev_rh10_c05','obs_claim_rh10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reidhoffman.org/' LIMIT 1),'supports',NULL,'Current biography','First-party role; fund economics excluded.',CURRENT_TIMESTAMP),
('obs_ev_rh10_c06','obs_claim_rh10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.microsoft.com/investor/reports/ar25/index.html' LIMIT 1),'supports',NULL,'Related-party transaction note','Inflection license and holder-specific interests.',CURRENT_TIMESTAMP),
('obs_ev_rh10_c07','obs_claim_rh10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://manasai.co/news/manas-ai-launches-to-transform-discovery-of-novel-cancer-medicines' LIMIT 1),'supports',NULL,'Launch announcement','Cofounder, team and infrastructure attribution.',CURRENT_TIMESTAMP),
('obs_ev_rh10_c08','obs_claim_rh10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reidhoffman.org/podcasts/' LIMIT 1),'supports',NULL,'Media portfolio','Host credit; ownership not inferred.',CURRENT_TIMESTAMP),
('obs_ev_rh10_c09','obs_claim_rh10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.axios.com/2018/12/26/reid-hoffman-apologizes-disinformation-alabama-special-election' LIMIT 1),'supports',NULL,'Attributed statement','Apology and stated lack of knowledge preserved.',CURRENT_TIMESTAMP),
('obs_ev_rh10_c10','obs_claim_rh10_c10',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.axios.com/2019/09/12/reid-hoffman-jeffrey-epstein-mit-donations' LIMIT 1),'supports',NULL,'Attributed statement','Interaction, context and apology bounded.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_rh10_linkedin',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'organization','LinkedIn','cofounder_former_executive_chair','2002-12-01T00:00:00Z','2016-12-08T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1271024/000119312511131453/ds1a.htm' LIMIT 1),NULL,'Multiple cofounders and role transitions preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_rh10_greylock',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'organization','Greylock','partner','2009-11-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reidhoffman.org/' LIMIT 1),NULL,'Fund and portfolio economics not inferred',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_rh10_microsoft',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'organization','Microsoft','director_announced_nonreelection','2017-03-14T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/linkedin-co-founder-reid-hoffman-step-down-microsofts-board-2026-06-05/' LIMIT 1),NULL,'Role continues only through 2026 annual meeting',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_rh10_inflection',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'organization','Inflection AI','cofounder_director_related_holder','2022-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.microsoft.com/investor/reports/ar25/index.html' LIMIT 1),NULL,'Separate company, IP, management and holder definitions',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_rh10_manas',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'organization','Manas AI','cofounder','2025-01-27T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://manasai.co/news/manas-ai-launches-to-transform-discovery-of-novel-cancer-medicines' LIMIT 1),NULL,'Siddhartha Mukherjee and interdisciplinary team preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_rh10_media',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'group','Masters of Scale and Possible','host_cohost','2017-05-03T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reidhoffman.org/podcasts/' LIMIT 1),NULL,'Production, platform and collaborator rights incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_rh10_linkedin',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'formation','LinkedIn co-founded','Hoffman and named cofounders formed LinkedIn.','2002-12-01T00:00:00Z','month','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1271024/000119312511131453/ds1a.htm' LIMIT 1),NULL,'Distributed formation attribution',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_rh10_greylock',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'appointment','Greylock partner role begins','Hoffman joined Greylock as a partner.','2009-11-01T00:00:00Z','month','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1271024/000119312511131453/ds1a.htm' LIMIT 1),NULL,'Fund ownership and economics not inferred',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_rh10_msdeal',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'acquisition','Microsoft announces LinkedIn acquisition','The approximately $26.2B company transaction was announced.','2016-06-13T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/789019/000119312516619689/d116815dex991.htm' LIMIT 1),NULL,'Company value, not personal proceeds',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_rh10_inflection',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'transaction','Microsoft enters Inflection license','Microsoft entered a non-exclusive IP license and related arrangements.','2024-03-01T00:00:00Z','month','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.microsoft.com/investor/reports/ar25/index.html' LIMIT 1),NULL,'License and holder boundaries preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_rh10_manas',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'formation','Manas AI launched','Hoffman and Siddhartha Mukherjee launched Manas AI with an interdisciplinary team.','2025-01-27T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://manasai.co/news/manas-ai-launches-to-transform-discovery-of-novel-cancer-medicines' LIMIT 1),NULL,'Prospective drug-development claims only',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_rh10_msexit',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'role_transition','Microsoft non-re-election announced','Microsoft disclosed Hoffman will not seek re-election at the 2026 annual meeting.','2026-06-05T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/linkedin-co-founder-reid-hoffman-step-down-microsofts-board-2026-06-05/' LIMIT 1),NULL,'No disagreement reported; endpoint prospective',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_reid_hoffman_100','reid-hoffman-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'1.0.0','research/observatory/dossiers/reid-hoffman-1.0.0.md','d400ff1d4adaed1c4e4842cc73ae1fedabcdeda4',
'{"claimIds":["obs_claim_rh10_c01","obs_claim_rh10_c02","obs_claim_rh10_c03","obs_claim_rh10_c04","obs_claim_rh10_c05","obs_claim_rh10_c06","obs_claim_rh10_c07","obs_claim_rh10_c08","obs_claim_rh10_c09","obs_claim_rh10_c10","obs_claim_rh10_c11"],"relationshipIds":["obs_rel_rh10_linkedin","obs_rel_rh10_greylock","obs_rel_rh10_microsoft","obs_rel_rh10_inflection","obs_rel_rh10_manas","obs_rel_rh10_media"],"eventIds":["obs_event_rh10_linkedin","obs_event_rh10_greylock","obs_event_rh10_msdeal","obs_event_rh10_inflection","obs_event_rh10_manas","obs_event_rh10_msexit"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","multi_entity_portfolio","historic_securities_not_current_ownership","transaction_value_not_personal_wealth","fund_economics_unverified","cofounders_and_labor_preserved","ai_ip_and_license_incomplete","media_rights_incomplete","adverse_events_attributed","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.88,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_reid_hoffman_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='reid-hoffman' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_reid_hoffman_100',
'{"packageId":"reid-hoffman-1.0.0","claimsLoaded":11,"relationshipsLoaded":6,"eventsLoaded":6,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Entity, ownership, fund, valuation, IP, media, labor, adverse-event, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
