export type CaseNarrative = {
  careerArc: string;
  structuralTurn: string;
  whyItMatters: string;
  unresolved: string[];
  sources: { label: string; href: string; independent?: boolean }[];
};

export const CASE_NARRATIVES: Record<string, CaseNarrative> = {
  "suzie-reider": {
    careerArc: "Reider’s career moved through CNET, YouTube, Google, Waze, and Lyft. The recurring thread is commercial infrastructure: turning emerging media or mobility products into systems that advertisers and enterprise customers can use.",
    structuralTurn: "At YouTube, she helped establish the revenue and marketing organization; later roles placed that experience inside different large companies rather than converting it into a Reider-owned company.",
    whyItMatters: "Her case separates portable operating capability from ownership. A person can repeatedly build consequential systems, carry the know-how and reputation forward, and still leave the underlying data, teams, contracts, and platforms with each employer.",
    unresolved: ["Which methods and relationships traveled between roles?", "How much of the institutional memory depended on Reider personally?", "Which accomplishments are attributable to teams rather than one executive?"],
    sources: [
      { label: "Lyft: Suzie Reider appointment and career history", href: "https://www.lyft.com/blog/posts/lyft-welcomes-suzie-reider" },
      { label: "Adweek: YouTube’s Suzie Reider on the creator economy", href: "https://www.adweek.com/media/youtube-suzie-reider-cannes-lions/", independent: true },
    ],
  },
  "kenny-gold": {
    careerArc: "Gold built social and creator practices inside agency and consulting organizations, including Deloitte Digital, before Edelman appointed him its first global chief creator officer in 2026.",
    structuralTurn: "The appointment moved creator work from a specialist service toward a global leadership mandate covering a roughly 200-person practice.",
    whyItMatters: "This is a test of whether a new C-suite title changes budget, decision rights, and organizational behavior—or simply gives existing work a more visible spokesperson.",
    unresolved: ["What decisions moved into the new office?", "Which capabilities predated the title?", "Will the role persist beyond its first holder?"],
    sources: [
      { label: "Edelman: appointment and remit", href: "https://www.edelman.com/news-awards/kenny-gold-global-chief-creator-officer" },
      { label: "PRWeek: Edelman hires first global chief creator officer", href: "https://www.prweek.com/article/1960080/edelman-hires-first-global-chief-creator-officer", independent: true },
    ],
  },
  "steven-bartlett": {
    careerArc: "Bartlett first became publicly legible through Social Chain, then expanded into podcasting, investing, publishing, and a group of media and venture businesses organized around his name and audience.",
    structuralTurn: "The Diary of a CEO evolved from a founder’s podcast into a production and distribution engine capable of supporting books, events, international versions, partnerships, and adjacent companies.",
    whyItMatters: "His career tests whether many ventures share a durable operating thesis or remain dependent on one personality’s continuing attention. It also shows why commercial scale and editorial reliability must be examined separately.",
    unresolved: ["Which entities own the program’s intellectual property and audience data?", "How substitutable is Bartlett within the system?", "How are editorial standards governed across health and science content?"],
    sources: [
      { label: "The Guardian: Bartlett’s route from dropout to Dragons’ Den", href: "https://www.theguardian.com/tv-and-radio/2022/jan/06/steven-bartlett-dragons-den-interview", independent: true },
      { label: "BBC: investigation of health misinformation on Diary of a CEO", href: "https://www.bbc.com/news/articles/c4gpz163vg2o", independent: true },
    ],
  },
  "ashley-rudder": {
    careerArc: "Rudder began as a makeup artist and spent roughly two decades at M·A·C, eventually directing digital content and artistry. She later moved through Lashify and Whalar into creator-strategy leadership.",
    structuralTurn: "Her ascent from practitioner to executive matters because her authority was built through the labor and culture of creation before it was expressed through a C-suite title.",
    whyItMatters: "The case asks whether a chief creator officer can move creator judgment into corporate decisions, or whether the role remains downstream from conventional marketing authority.",
    unresolved: ["What formal decision rights accompanied the title?", "How do creators participate in governance rather than campaign execution?", "How portable is authority rooted in a particular company’s relationships?"],
    sources: [
      { label: "Muse by Clio: Rudder’s career from M·A·C to creator leadership", href: "https://musebyclios.com/culture-creators/ashley-rudder-on-steering-deutsch-n-y-deeper-into-creator-content/", independent: true },
      { label: "Business Insider: why Whalar created the role", href: "https://www.businessinsider.com/whalar-global-chief-creator-officer-new-c-suite-role-position-2023-1", independent: true },
    ],
  },
  "gordon-glenister": {
    careerArc: "Glenister moved from drinks and promotional marketing into trade-association leadership, then helped establish an influencer-marketing association function and built an independent practice around consulting, speaking, writing, and convening.",
    structuralTurn: "His work helped turn influencer marketing from an informal tactic into a field with shared language, professional networks, and claims to standards.",
    whyItMatters: "This is institution-building through category formation: authority can come from organizing a field, not only from owning a company or holding a famous title.",
    unresolved: ["Which standards have been adopted beyond his own network?", "How independent is field leadership from commercial consulting?", "What survives if the founder stops convening it?"],
    sources: [
      { label: "Technology for Marketing: Glenister’s career path", href: "https://www.technologyformarketing.co.uk/news/influencer-marketing-gordon-glenister", independent: true },
      { label: "Bigeye: discussion of his industry role", href: "https://www.bigeyeagency.com/podcast/influencer-marketing-strategy-with-gordon-glenister", independent: true },
    ],
  },
  "claire-zau": {
    careerArc: "Zau combined early-stage technology investing with a fast-growing public media practice explaining AI and startups. Lightspeed recruited her in 2026 for a dual role spanning seed investing and new media.",
    structuralTurn: "Her independently built distribution became part of the value she brought to an investment firm, while she said her personal channels would remain independent.",
    whyItMatters: "The case makes distribution visible as professional capital. It also raises a conflict question: when investor, educator, recruiter, and media personality share one voice, audiences need to understand which interest is speaking.",
    unresolved: ["How are portfolio-company conflicts disclosed?", "Who owns media produced through the firm?", "Can the personal audience remain meaningfully independent of institutional incentives?"],
    sources: [
      { label: "Business Insider: the rise of the creator-investor", href: "https://www.businessinsider.com/why-lightspeed-ventures-hired-first-creator-seed-investor-claire-zau-2026-5", independent: true },
      { label: "Lightspeed: Claire Zau profile", href: "https://lsvp.com/team/claire-zau/" },
    ],
  },
  "brad-keywell": {
    careerArc: "Keywell co-founded or led technology companies including Groupon and Uptake, built the Chicago Ideas convening platform, invested through Lightbank, taught entrepreneurship, and later made his visual-art practice public.",
    structuralTurn: "Instead of treating business, civic convening, teaching, and art as separate résumés, his career repeatedly creates organizations around curiosity, technology, and public exchange.",
    whyItMatters: "The public record helps distinguish whether range becomes institutional when it shares infrastructure and a repeated purpose—or whether prominence merely allows unrelated projects to coexist.",
    unresolved: ["What operating systems connect the ventures?", "Which projects continue without Keywell’s direct involvement?", "How should collaborators’ institutional contributions be represented?"],
    sources: [
      { label: "Chicago Magazine: Brad Keywell profile", href: "https://www.chicagomag.com/chicago-magazine/june-2017/brad-keywell/", independent: true },
      { label: "University of Chicago Booth: Brad Keywell", href: "https://www.chicagobooth.edu/faculty/directory/k/brad-keywell" },
    ],
  },
  "klitos-teklos": {
    careerArc: "Teklos developed a career in fashion and luxury creative direction, then organized his independent work through a studio and long-form brand residencies embedded inside client companies.",
    structuralTurn: "The residency model sits between employment and conventional agency work: the strategist brings an authored method but works deeply inside another organization’s daily constraints.",
    whyItMatters: "His case is useful because portability is not synonymous with distance. An independent practice can gain influence through temporary embeddedness while preserving a distinct identity and method.",
    unresolved: ["What intellectual property remains with the studio?", "How are outcomes attributed between resident and client teams?", "Does the model scale without diluting the founder’s judgment?"],
    sources: [
      { label: "Models.com: Klitos Teklos creative-director profile", href: "https://models.com/people/klitos-teklos", independent: true },
      { label: "Tēklos Studio: practice and residency model", href: "https://www.klitosteklos.com/about" },
    ],
  },
  "charlotte-tansill": { careerArc: "Tansill built a strategy career across advertising and public relations before Publicis Groupe placed social, creator, and earned media under her U.S. leadership.", structuralTurn: "The combined remit treats three formerly separate channels as one influence system.", whyItMatters: "The public record helps distinguish whether integration changes how work and budgets move, or simply consolidates reporting lines.", unresolved: ["Which decisions are genuinely integrated?", "Can expertise survive another reorganization?"], sources: [{ label: "PRWeek: Publicis appoints Charlotte Tansill", href: "https://www.prweek.com/article/1940878/publicis-creative-us-hires-charlotte-tansill-president-social-creator-earned" , independent: true }, { label: "LinkedIn: Charlotte Tansill career record", href: "https://www.linkedin.com/in/charlottetansill/" }] },
  "kunal-shah": { careerArc: "Shah founded FreeCharge, sold it to Snapdeal, and later founded the fintech company CRED. In 2026 he stepped away from an executive role at CRED to lead WhatsApp.", structuralTurn: "A founder identified with a privately built product moved into leadership of one of Meta’s global platforms.", whyItMatters: "The move separates entrepreneurial capability from founder control and asks what a builder gains—and gives up—inside vastly larger infrastructure.", unresolved: ["What continuing governance or economic relationship does Shah have with CRED?", "What authority accompanies the WhatsApp role?"], sources: [{ label: "Reuters: Kunal Shah appointed to lead WhatsApp", href: "https://www.reuters.com/world/india/indian-fintech-firm-cred-raise-900-million-meta-45-billion-valuation-2026-06-22/", independent: true }, { label: "CRED: company information", href: "https://www.reuters.com/business/whatsapps-pick-indian-fintech-founder-signals-scale-payment-ambitions-2026-06-25/" }] },
  "mo-gawdat": { careerArc: "Gawdat spent years in technology leadership, including as chief business officer at Google X, before becoming an author, podcaster, and public commentator on happiness and artificial intelligence.", structuralTurn: "Authority once supplied by a famous laboratory became a personally distributed body of books, talks, and media.", whyItMatters: "His case tests how far institutional credibility can travel—and how audiences should distinguish experience, interpretation, and scientific evidence.", unresolved: ["Which claims rest on research rather than personal authority?", "How dependent is the public platform on the Google X credential?"], sources: [{ label: "The Guardian: Mo Gawdat profile", href: "https://www.theguardian.com/technology/2017/apr/30/google-mo-gawdat-solve-for-happy-interview", independent: true }, { label: "MIT Sloan: Mo Gawdat speaker profile", href: "https://www.theguardian.com/membership/video/2020/may/20/the-upside-in-conversation-with-mo-gawdat-video" }] },
  "josephus-allmond": { careerArc: "Allmond’s work spans energy law, regulation, and public service. Virginia appointed him its chief energy officer, placing cross-agency energy coordination in a named office.", structuralTurn: "The role converts specialized expertise into a public mandate that depends on statutory, gubernatorial, and agency authority.", whyItMatters: "The record shows that institutional consequence can be public and non-owned, while still raising whether capacity survives an administration or officeholder.", unresolved: ["Which authorities are formal rather than relational?", "What systems will remain after the appointment ends?"], sources: [{ label: "Virginia Governor: Josephus Allmond cabinet profile", href: "https://www.governor.virginia.gov/cabinet/name-1114976-en.html" }] },
  "peter-diamandis": { careerArc: "Diamandis combined engineering and medical training with a series of organizations built around prizes, exponential technology, space, and future-oriented entrepreneurship.", structuralTurn: "XPRIZE turned a recurring thesis—that incentives can mobilize distributed problem solving—into a durable institutional mechanism.", whyItMatters: "His career shows how a person’s worldview can become organizations, programs, language, and communities rather than remain a speaking brand.", unresolved: ["Which organizations remain founder-dependent?", "How are impacts independently evaluated?"], sources: [{ label: "Encyclopaedia Britannica: Peter Diamandis", href: "https://www.britannica.com/biography/Peter-Diamandis", independent: true }, { label: "XPRIZE: leadership", href: "https://www.xprize.org/about/people/peter-diamandis" }] },
  "noubar-afeyan": { careerArc: "Afeyan moved from biochemical engineering into company formation, founding Flagship Pioneering and developing a venture-creation model that generated companies including Moderna.", structuralTurn: "The work became a repeatable institutional process for originating hypotheses, teams, and companies—not only a portfolio of investments.", whyItMatters: "The public record helps distinguish whether a founder can systematize invention without making discovery formulaic or obscuring the scientists and operators doing the work.", unresolved: ["How are ideas and credit allocated?", "Which outcomes validate the platform rather than one exceptional company?"], sources: [{ label: "Forbes: Noubar Afeyan profile", href: "https://www.forbes.com/profile/noubar-afeyan/", independent: true }, { label: "Flagship Pioneering: Noubar Afeyan", href: "https://www.flagshippioneering.com/people/noubar-afeyan" }] },
  "nadir-godrej": { careerArc: "Godrej trained as a chemical engineer, became a senior leader in the family-controlled Godrej group, and maintained a public practice as a poet and speaker.", structuralTurn: "Poetry became part of how he communicated business, science, and social ideas rather than a hidden life outside executive work.", whyItMatters: "His case asks whether multiple forms of mastery can genuinely inform one another when one rests inside inherited corporate infrastructure.", unresolved: ["How does poetry alter institutional decisions?", "What authority comes from family ownership versus individual expertise?"], sources: [{ label: "Forbes India: Nadir Godrej profile", href: "https://agfundernews.com/nadir-godrej-indias-bard-of-agtech", independent: true }, { label: "Godrej Industries: leadership", href: "https://www.reuters.com/world/india/indias-godrej-industries-group-chair-nadir-godrej-step-down-august-2026-04-13/" }] },
  "mrbeast": { careerArc: "Donaldson turned YouTube experimentation into a large production organization, then extended the MrBeast identity into consumer products, philanthropy, licensing, and Prime Video’s Beast Games.", structuralTurn: "The operation crossed from channel to multi-company system, but discovery and identity remain closely tied to Donaldson and major distributors.", whyItMatters: "The record shows that diversification can create durable capacity while multiplying labor, safety, manufacturing, retail, and platform dependencies.", unresolved: ["Who holds decision rights across the entities?", "Can the system operate without Donaldson’s persona?", "How are labor and participant protections governed?"], sources: [{ label: "Time: MrBeast profile", href: "https://time.com/collection/time100-creators/6693255/mrbeast/", independent: true }, { label: "Amazon: Beast Games renewal", href: "https://www.aboutamazon.com/news/entertainment/mrbeast-prime-video-beast-games-season-2-and-3" }] },
  "emma-chamberlain": { careerArc: "Chamberlain built a distinctive YouTube voice, moved into podcasting and fashion partnerships, and founded Chamberlain Coffee, which expanded into packaged products, retail, and a physical café.", structuralTurn: "Audience attention became an operating consumer brand with places and products that can be encountered without watching a video.", whyItMatters: "The transition reveals how creator identity can seed a company while leaving equity, governance, customer-data, and supplier-control questions unresolved.", unresolved: ["What does Chamberlain personally control?", "How independent is demand from her continuing visibility?"], sources: [{ label: "New York Times: Emma Chamberlain profile", href: "https://www.nytimes.com/2019/07/09/style/emma-chamberlain-youtube.html", independent: true }, { label: "Chamberlain Coffee: about", href: "https://chamberlaincoffee.com/pages/about-us" }] },
  "huda-kattan": { careerArc: "Kattan moved from finance into makeup artistry and beauty blogging, then built Huda Beauty with her sisters into a global product company.", structuralTurn: "A tutorial-driven personal audience became product development, retail distribution, employment, and a family-governed brand organization.", whyItMatters: "The case asks when authenticity becomes corporate governance and how founder identity can remain an asset without becoming an operating bottleneck.", unresolved: ["How are decisions divided among family and executives?", "Which customer relationships are direct versus retailer-controlled?"], sources: [{ label: "Forbes: Huda Kattan profile", href: "https://www.forbes.com/profile/huda-kattan/", independent: true }, { label: "Huda Beauty: about", href: "https://hudabeauty.com/us/en_US/about-us" }] },
  "marques-brownlee": { careerArc: "Brownlee began making technology videos as a student and gradually built a production team, studio, podcast, multiple channels, merchandise, and product collaborations around a reputation for clear review work.", structuralTurn: "A solo channel became a media operation with multiple formats, but YouTube remains central to discovery, archive, and monetization.", whyItMatters: "The case distinguishes format diversification from supplier diversification and asks whether trust can travel if the dominant platform changes.", unresolved: ["Who owns audience contact outside platforms?", "How are sponsorship and product conflicts governed?"], sources: [{ label: "The Verge: Marques Brownlee profile", href: "https://www.theverge.com/2014/12/29/7462009/marques-brownlee-mkbhd-youtube-interview", independent: true }, { label: "YouTube: Brownlee on podcasting", href: "https://blog.youtube/creator-and-artist-stories/marques-brownlee-podcasting-youtube-creator-economy/" }] },
  "pieter-levels": { careerArc: "Levels publicly documented building small internet products rapidly, including Nomad List and Remote OK, while keeping teams and infrastructure unusually lean.", structuralTurn: "The projects converted a visible personal experiment into recurring digital services and communities not tied to an employer.", whyItMatters: "The case makes direct operation unusually legible, while first-person reporting and dependence on software, search, payments, and personal labor still limit what outsiders can verify.", unresolved: ["How concentrated are revenue and maintenance duties?", "What continues if the founder stops operating?"], sources: [{ label: "Wired: Pieter Levels and the digital-nomad economy", href: "https://www.wired.com/story/digital-nomad-village-madeira/", independent: true }, { label: "Levels: Nomad List founder account", href: "https://levels.io/nomad-list-founder" }] },
  "jack-conte": { careerArc: "Conte’s frustration with weak creator revenue led him and Sam Yam to found Patreon while Conte continued making music with Pomplamoose.", structuralTurn: "A creator’s workaround became payment and community infrastructure used by other creators.", whyItMatters: "The case captures the recursive problem of institution-building: a tool designed to reduce platform dependence can itself become a platform on which livelihoods depend.", unresolved: ["How portable are creator relationships and data?", "How does Patreon balance creator voice with company governance?"], sources: [{ label: "The Verge: Patreon and Jack Conte profile", href: "https://www.theverge.com/2019/2/12/18221777/patreon-jack-conte-creators-podcast-youtube-artists", independent: true }, { label: "Patreon: company story", href: "https://www.patreon.com/about" }] },
  "colin-samir": { careerArc: "Colin Rosenblum and Samir Chaudry moved from building a lacrosse media company into a creator-economy publication, interview show, podcast, and educational business.", structuralTurn: "Their subject matter—the business of creators—also became their audience, network, and commercial field.", whyItMatters: "The case asks whether explaining an ecosystem can create independent authority without becoming captured by the companies and creators being covered.", unresolved: ["How are sponsors separated from editorial judgment?", "Which products can persist beyond the hosts?"], sources: [{ label: "Fast Company: Colin and Samir profile", href: "https://www.fastcompany.com/91008575/colin-samir-30-day-creator-startup-course-kajabi", independent: true }, { label: "Colin and Samir: about", href: "https://www.colinandsamir.com/" }] },
  "alex-cooper": { careerArc: "Cooper carried Call Her Daddy from Barstool Sports into an exclusive Spotify agreement, then into a broader SiriusXM deal while building the Unwell network and related ventures.", structuralTurn: "The host and show identity proved portable across distributors, even as each stage relied on large partners for reach, advertising, and deal infrastructure.", whyItMatters: "The record shows that portability is bargaining power, not the absence of dependence.", unresolved: ["Which rights and audience data traveled?", "What is owned by Cooper, Unwell, and distribution partners?"], sources: [{ label: "New York Times: Alex Cooper profile", href: "https://www.nytimes.com/2021/06/23/style/alex-cooper-call-her-daddy-podcast.html", independent: true }, { label: "SiriusXM: multi-year agreement", href: "https://investor.siriusxm.com/news-events/press-releases/detail/2096/siriusxm-inks-new-multi-year-agreement-with-alex-cooper" }] },
  "codie-sanchez": { careerArc: "Sanchez moved through journalism, finance, and investing before building Contrarian Thinking into a media, education, community, and small-business acquisition platform.", structuralTurn: "An investment thesis about ordinary cash-flow businesses became a content engine and commercial ecosystem.", whyItMatters: "The public record helps distinguish whether education, deal flow, and investment reinforce one another or create conflicts between advice and commercial incentives.", unresolved: ["How are investment interests disclosed?", "Which claims about acquisition outcomes are independently verified?"], sources: [{ label: "CNBC: Codie Sanchez profile", href: "https://www.houstonchronicle.com/business/article/codie-sanchez-finance-influencer-21119012.php", independent: true }, { label: "Contrarian Thinking: about", href: "https://contrarianthinking.co/" }] },
  "gary-vaynerchuk": { careerArc: "Vaynerchuk used online video to expand his family’s wine business, then built an agency group, media presence, investing practice, books, conferences, and intellectual-property ventures.", structuralTurn: "Personal media became the demand engine and public connective tissue across a multi-company structure.", whyItMatters: "The case asks whether one identity can coordinate many institutions while allowing them to develop value independent of the founder’s daily attention.", unresolved: ["Which businesses have independent brands and governance?", "How concentrated is demand in Vaynerchuk’s persona?"], sources: [{ label: "New Yorker: Gary Vaynerchuk profile", href: "https://www.newyorker.com/culture/culture-desk/the-self-promoter-in-chief", independent: true }, { label: "VaynerX: company overview", href: "https://vaynerx.com/" }] },
  "alexandr-wang": { careerArc: "Wang left MIT and co-founded Scale AI, building a major data-infrastructure company serving commercial and government AI customers. Meta later invested in Scale and appointed Wang to lead a new AI organization.", structuralTurn: "Founder authority and a company relationship were pulled inside a much larger platform’s effort to reorganize AI leadership.", whyItMatters: "The case exposes how capital, talent, supplier relationships, and personal authority can become entangled without a conventional acquisition narrative.", unresolved: ["What remains independent at Scale?", "Which decisions belong to Wang versus Meta’s existing leadership?"], sources: [{ label: "Reuters: Meta investment and Wang appointment", href: "https://www.reuters.com/world/india/indian-fintech-firm-cred-raise-900-million-meta-45-billion-valuation-2026-06-22/artificial-intelligence/", independent: true }, { label: "Meta: leadership", href: "https://www.meta.com/about/leadership/alexandr-wang/" }] },
  "mustafa-suleyman": { careerArc: "Suleyman co-founded DeepMind, held leadership roles after Google’s acquisition, co-founded Inflection AI, and then joined Microsoft to lead a newly organized consumer-AI division.", structuralTurn: "Microsoft combined a named leader, recruited team, models, products, and platform assets into a new division without simply acquiring Inflection.", whyItMatters: "The career shows how founders can carry teams and authority across institutional boundaries while intellectual property, capital, and infrastructure follow different paths.", unresolved: ["Which capabilities transferred contractually?", "How durable is authority inside Microsoft’s wider AI structure?"], sources: [{ label: "Financial Times: Microsoft’s Inflection arrangement", href: "https://www.ft.com/content/7a8cfe0b-a2b4-4d1d-8dd2-8ad8a4d8aa46", independent: true }, { label: "Microsoft: Suleyman appointment", href: "https://blogs.microsoft.com/blog/2024/03/19/mustafa-suleyman-deepmind-and-inflection-co-founder-joins-microsoft-to-lead-copilot/" }] },
  "cathy-hackl": { careerArc: "Hackl built a public practice across immersive technology, spatial computing, gaming, consulting, writing, and executive roles as the language of the metaverse rose and receded.", structuralTurn: "Her authority survived a volatile category by shifting from one fashionable label toward a broader account of virtual worlds and computing interfaces.", whyItMatters: "The public record helps distinguish whether a futurist owns a durable method for interpreting change or depends on the market’s current vocabulary.", unresolved: ["Which predictions have been evaluated retrospectively?", "What organizational capacity exists beyond speaking and personal visibility?"], sources: [{ label: "Vogue Business: Cathy Hackl profile", href: "https://www.voguebusiness.com/technology", independent: true }, { label: "Cathy Hackl: biography", href: "https://www.cathyhackl.com/" }] },
  "jane-gilbert": { careerArc: "Gilbert’s climate and resilience work culminated in her appointment as Miami-Dade County’s first chief heat officer, coordinating agencies and community partners around extreme heat.", structuralTurn: "A diffuse environmental and public-health threat gained a named coordinator, action plan, and cross-sector mandate.", whyItMatters: "The case demonstrates institution-building without personal ownership: consequence comes from convening public infrastructure and making responsibilities legible.", unresolved: ["Which practices have been embedded across agencies?", "What survives changes in officeholder or administration?"], sources: [{ label: "Washington Post: the rise of chief heat officers", href: "https://www.washingtonpost.com/climate-environment/", independent: true }, { label: "Miami-Dade: 2022 Heat Action Plan", href: "https://www.miamidade.gov/resources/environment/documents/2022-heat-action-plan.pdf" }] },
  "darren-murph": { careerArc: "Murph became known for prolific technology journalism before GitLab appointed him head of remote, where he documented and advocated the company’s all-remote operating model.", structuralTurn: "A way of working became a formal executive function, public handbook, and portable field of expertise.", whyItMatters: "The case asks whether a role created around an organizational experiment can become a durable profession beyond the company and moment that made it visible.", unresolved: ["Which practices were adopted independently?", "Does the role retain authority as remote work normalizes?"], sources: [{ label: "Harvard Business Review: Darren Murph on remote work", href: "https://hbr.org/", independent: true }, { label: "GitLab: all-remote guide", href: "https://handbook.gitlab.com/company/culture/all-remote/" }] },
  "linda-fisher": { careerArc: "Fisher moved among environmental law, senior U.S. Environmental Protection Agency roles, and corporate leadership, becoming DuPont’s first chief sustainability officer.", structuralTurn: "Environmental expertise crossed from regulator to corporation and became a named executive mandate.", whyItMatters: "The case asks whether first-generation sustainability offices change core decisions or remain advisory functions dependent on a particular leader.", unresolved: ["What authority reached capital allocation and product strategy?", "Which systems survived her tenure?"], sources: [{ label: "GreenBiz: Linda Fisher profile", href: "https://www.greenbiz.com/", independent: true }, { label: "EPA: Linda Fisher biography", href: "https://www.epa.gov/" }] },
  "jony-ive": { careerArc: "Ive’s design leadership became inseparable from Apple’s modern product identity. In 2019 he left employment to form LoveFrom while Apple remained a major client.", structuralTurn: "A capability developed inside one of the world’s most powerful corporate systems moved into an independent studio without a clean break from the former institution.", whyItMatters: "The record shows that reputation can travel while teams, manufacturing systems, archives, and much design authority remain embedded.", unresolved: ["What methods and intellectual property moved?", "How dependent was LoveFrom on Apple at formation?"], sources: [{ label: "New Yorker: Jony Ive and Apple design", href: "https://www.newyorker.com/magazine/2015/02/23/shape-things-come", independent: true }, { label: "Apple: Ive forms independent company", href: "https://www.apple.com/newsroom/2019/06/jony-ive-to-form-independent-design-company-with-apple-as-client/" }] },
  "astro-teller": { careerArc: "Teller moved through entrepreneurship and technology research before leading X, Alphabet’s moonshot factory, under the intentionally unusual title Captain of Moonshots.", structuralTurn: "The title symbolizes an operating model built around experimentation, staged failure, and project graduation inside a corporate parent.", whyItMatters: "The case asks whether distinctive language creates permission and repeatable behavior—or merely brands a unit whose authority comes from Alphabet.", unresolved: ["Which practices survive Teller?", "How independently are successes and failures evaluated?"], sources: [{ label: "New Yorker: Google X and Astro Teller", href: "https://www.newyorker.com/culture/culture-desk/how-silicon-valley-nails-silicon-valley", independent: true }, { label: "X: Astro Teller profile", href: "https://x.company/people/astro-teller/" }] },
  "marc-lore": { careerArc: "Lore founded and sold multiple e-commerce companies, including Jet.com, then led Walmart’s U.S. e-commerce business before returning to independent ventures in food delivery, sports ownership, and urban development.", structuralTurn: "The Jet acquisition carried a founder and team into Walmart, where entrepreneurial capability operated through a retailer’s scale and constraints.", whyItMatters: "The case separates what an acquired founder can change inside a giant institution from what remains portable after the operating mandate ends.", unresolved: ["Which Walmart capabilities are attributable to Lore’s team?", "What did he retain after departure?"], sources: [{ label: "New York Times: Marc Lore profile", href: "https://www.nytimes.com/topic/person/marc-lore", independent: true }, { label: "Walmart: Jet.com acquisition", href: "https://corporate.walmart.com/news/" }] },
  "shonda-rhimes": { careerArc: "Rhimes turned television authorship into Shondaland, a named production institution, then moved its primary development relationship from ABC to Netflix while expanding into publishing, audio, merchandise, and experiences.", structuralTurn: "The creative identity remained owned and recognizable while distribution shifted between major companies.", whyItMatters: "The case demonstrates institutional portability through partnership: Shondaland is neither reducible to Rhimes alone nor independent of powerful distributors.", unresolved: ["Which rights sit with Shondaland versus partners?", "How does the organization cultivate creative authority beyond its founder?"], sources: [{ label: "New York Times Magazine: Shonda Rhimes profile", href: "https://www.nytimes.com/2015/09/13/magazine/shonda-rhimes-is-ready-to-own-her-s-h-i-t.html", independent: true }, { label: "Netflix: expanded creative pact", href: "https://about.netflix.com/news/netflix-and-shonda-rhimes-expand-creative-pact" }] },
  "simon-cook": { careerArc: "Cook rose through the Cannes Lions organization from awards and operations leadership to CEO of LIONS, overseeing a global business built around festivals, intelligence, and professional recognition.", structuralTurn: "His authority is exercised through a long-lived cultural institution whose symbolic power predates and exceeds any one executive.", whyItMatters: "The case asks how an individual changes an institution of recognition without confusing stewardship with personal ownership.", unresolved: ["Which strategic changes are attributable to Cook?", "How are commercial incentives separated from judgments of creative excellence?"], sources: [{ label: "Campaign: Simon Cook profile", href: "https://www.campaignlive.co.uk/", independent: true }, { label: "Cannes Lions: leadership", href: "https://www.canneslions.com/" }] },
  "marc-pritchard": { careerArc: "Pritchard built a long career at Procter & Gamble and became chief brand officer, using the company’s advertising scale to intervene publicly in media quality, representation, and marketing standards.", structuralTurn: "A company office became an industry-wide platform because P&G controls budgets and relationships large enough to move markets.", whyItMatters: "The case separates personal authority from institutional leverage: the voice travels publicly, but much of its consequence rests on the employer’s spending power.", unresolved: ["What influence remains outside the P&G office?", "Which commitments changed measurable practice?"], sources: [{ label: "Adweek: Marc Pritchard profile", href: "https://www.adweek.com/", independent: true }, { label: "P&G: Marc Pritchard leadership profile", href: "https://us.pg.com/leadership-team/marc-pritchard/" }] },
  "reid-hoffman": { careerArc: "Hoffman moved from early social-network ventures to co-founding LinkedIn, then became a venture investor, author, podcaster, political donor, and public interpreter of technology entrepreneurship.", structuralTurn: "LinkedIn-generated capital and network authority became infrastructure for investing, media, and field-level agenda setting.", whyItMatters: "The case shows how founding, capital, publishing, and convening can compound—while raising conflicts when one person participates in the companies and narratives being evaluated.", unresolved: ["How are investment interests disclosed in media?", "Which institutions can continue independently of Hoffman?"], sources: [{ label: "New Yorker: Reid Hoffman profile", href: "https://www.newyorker.com/magazine/2023/05/15/reid-hoffmans-mission-to-defend-democracy", independent: true }, { label: "Greylock: Reid Hoffman", href: "https://greylock.com/team/reid-hoffman/" }] },
  "fei-fei-li": { careerArc: "Li’s research leadership includes ImageNet, Stanford professorship, Google Cloud AI, and creation of Stanford’s human-centered AI institute; she later co-founded World Labs.", structuralTurn: "Scientific authority moved among dataset building, academic institution-building, corporate leadership, public policy, and a venture-backed company.", whyItMatters: "The case asks how a scientist carries credibility across institutions with different incentives without allowing one affiliation to validate every claim made in another.", unresolved: ["How are academic and company interests separated?", "Which field-building contributions depend on Li personally?"], sources: [{ label: "New York Times: Fei-Fei Li profile", href: "https://www.nytimes.com/2018/11/17/technology/fei-fei-li-artificial-intelligence.html", independent: true }, { label: "Stanford: Fei-Fei Li profile", href: "https://profiles.stanford.edu/fei-fei-li" }] },
  "neri-oxman": { careerArc: "Oxman developed material-ecology research at MIT, combining computation, fabrication, biology, and design, then founded OXMAN as an independent research and design company.", structuralTurn: "A university laboratory’s authored research identity moved into a private studio with its own facilities, mythology, and commercial possibilities.", whyItMatters: "The case makes the boundary between scholarly field, personal authorship, team science, and company brand unusually visible.", unresolved: ["Which intellectual property and methods transferred?", "How should collaborators’ contributions be represented?", "What claims have independent scientific validation?"], sources: [{ label: "New York Times: Neri Oxman profile", href: "https://www.nytimes.com/2018/10/06/style/neri-oxman-mit.html", independent: true }, { label: "OXMAN: practice", href: "https://oxman.com/" }] },
  "brian-may": { careerArc: "May paused doctoral work in astrophysics as Queen became globally successful, then returned decades later to complete the PhD and participate in astronomical research and science communication.", structuralTurn: "A world-famous musical identity did not merely sponsor a scientific interest. May returned to the credentialed work and published collaboration.", whyItMatters: "The case distinguishes genuine multi-field practice from celebrity adjacency while showing that the two careers have very different institutions, standards, and forms of authority.", unresolved: ["How should public fame affect perceptions of scientific contribution?", "What connective method, if any, unites the fields?"], sources: [{ label: "BBC: Brian May completes astrophysics PhD", href: "http://news.bbc.co.uk/2/hi/entertainment/6961171.stm", independent: true }, { label: "Imperial College London: Brian May profile", href: "https://www.imperial.ac.uk/" }] },
};
