import { CASE_NARRATIVES } from "@/lib/case_narratives";

export type CaseResearchSource = {
  id: string;
  label: string;
  href: string;
  publisher: string;
  published: string;
  kind: "independent" | "primary" | "institutional";
};

export type CaseResearchRecord = {
  documentationLevel: "saturated" | "provisional";
  reviewed: string;
  chronology: { date: string; event: string; sourceIds: string[] }[];
  interpretation: string;
  complication: string[];
  unknowns: string[];
  payoff: string;
  sources: CaseResearchSource[];
};

export const CASE_RESEARCH: Record<string, CaseResearchRecord> = {
  "josephus-allmond": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "Before March 2026", event: "Allmond worked as a Southern Environmental Law Center staff attorney, litigating utility-regulation matters before Virginia’s State Corporation Commission. He also served on the Commission on Electric Utility Regulation.", sourceIds: ["va-bio", "whro-profile"] },
      { date: "March 25, 2026", event: "Governor Abigail Spanberger created a cabinet-level Chief Energy Officer position by executive order and appointed Allmond as its first holder.", sourceIds: ["executive-announcement", "mercury"] },
      { date: "June 17, 2026", event: "Independent reporting described the new office’s practical test: coordinating energy policy amid rising consumer costs, data-center demand, grid constraints, and clean-energy goals.", sourceIds: ["whro-profile"] },
    ],
    interpretation: "This is not a story of a person privately owning an institution. It is a test of whether specialized legal and regulatory knowledge can become durable public coordinating capacity through a newly created office.",
    complication: [
      "The office’s cabinet status supplies formal access, but an executive-created role may remain more vulnerable to a later administration than a statutory agency.",
      "Allmond’s prior litigation experience is evidence of subject-matter expertise; it does not yet establish the new office’s budget, staff capacity, decision rights, or outcomes.",
      "Early coverage describes the mandate more clearly than the office’s completed work because the position is new.",
    ],
    unknowns: [
      "What staff, budget, and binding authorities belong to the office?",
      "Which decisions can the Chief Energy Officer make rather than recommend or coordinate?",
      "What mechanisms would preserve the capacity after this governor or officeholder leaves?",
    ],
    payoff: "Allmond’s case teaches that public authority can be consequential without being owned. The durability question is whether a new mandate becomes routines, resources, and legal structure that survive the person who first carries it.",
    sources: [
      { id: "executive-announcement", label: "Governor creates the office and announces the appointment", href: "https://www.governor.virginia.gov/newsroom/news-releases/2026/march-releases/name-1114943-en.html", publisher: "Commonwealth of Virginia", published: "2026-03-25", kind: "primary" },
      { id: "va-bio", label: "Official biography and prior utility-regulation work", href: "https://www.governor.virginia.gov/cabinet/name-1114976-en.html", publisher: "Commonwealth of Virginia", published: "2026", kind: "institutional" },
      { id: "mercury", label: "Independent report on the office’s creation", href: "https://virginiamercury.com/briefs/spanberger-creates-new-cabinet-position-appoints-selcs-josephus-allmond-chief-energy-officer/", publisher: "Virginia Mercury", published: "2026-03-25", kind: "independent" },
      { id: "whro-profile", label: "Independent profile of the office’s energy-policy challenge", href: "https://www.whro.org/virginia-center-for-investigative-journalism/2026-06-17/vcij-josephus-allmond", publisher: "WHRO / Virginia Center for Investigative Journalism", published: "2026-06-17", kind: "independent" },
    ],
  },
  "kunal-shah": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "2010–2015", event: "Shah co-founded FreeCharge and sold it to Snapdeal, establishing a record in Indian consumer payments.", sourceIds: ["reuters-analysis"] },
      { date: "2018", event: "He founded CRED, a members-focused financial platform that expanded across payments, credit, insurance, and wealth services.", sourceIds: ["reuters-deal"] },
      { date: "June 22, 2026", event: "Meta announced that Shah would step down from CRED’s executive leadership to lead WhatsApp globally as Meta invested $900 million for a minority stake in CRED.", sourceIds: ["reuters-deal", "verge"] },
      { date: "June 25, 2026", event: "Reuters analysis connected the appointment to WhatsApp’s payments and commerce ambitions, particularly in India and other major markets.", sourceIds: ["reuters-analysis"] },
    ],
    interpretation: "Shah’s move is unusually useful because it does not cleanly separate founder ownership from employed authority: he leaves executive control of CRED while retaining an economic relationship to the company and enters a vast platform he does not own.",
    complication: [
      "Founder experience may travel, but WhatsApp’s users, infrastructure, data governance, and strategic constraints belong to Meta.",
      "Meta’s investment in CRED creates a continuing institutional relationship, so the move is not a simple founder-to-employee transition.",
      "Public announcements establish appointment and deal terms, not Shah’s practical decision rights inside Meta.",
    ],
    unknowns: [
      "How will conflicts between CRED’s interests and WhatsApp’s product strategy be governed?",
      "Which decisions over payments, commerce, privacy, and monetization will sit with Shah?",
      "What continuing governance rights or obligations accompany Shah’s retained CRED stake?",
    ],
    payoff: "Shah’s case teaches that portability is not binary. A founder can carry judgment and equity into a larger institution while surrendering control over the platform where that judgment will next be exercised.",
    sources: [
      { id: "reuters-deal", label: "Meta investment in CRED and Shah’s move to WhatsApp", href: "https://www.reuters.com/world/india/indian-fintech-firm-cred-raise-900-million-meta-45-billion-valuation-2026-06-22/", publisher: "Reuters", published: "2026-06-22", kind: "independent" },
      { id: "reuters-analysis", label: "Analysis of Shah’s payments background and WhatsApp mandate", href: "https://www.reuters.com/business/whatsapps-pick-indian-fintech-founder-signals-scale-payment-ambitions-2026-06-25/", publisher: "Reuters", published: "2026-06-25", kind: "independent" },
      { id: "verge", label: "Independent account of the WhatsApp leadership transition", href: "https://www.theverge.com/tech/953464/whatsapp-will-cathcart-stepping-down-cred", publisher: "The Verge", published: "2026-06-22", kind: "independent" },
    ],
  },
  "suzie-reider": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "2006", event: "Reider joined YouTube as chief marketing officer before Google's acquisition and later built revenue and marketing functions within Google.", sourceIds: ["middlebury-career", "middlebury-trustee"] },
      { date: "2019–2020", event: "At Waze, Reider led advertising and sales during the pandemic traffic collapse, when mobility and advertising revenue fell sharply.", sourceIds: ["bi-waze", "modern-retail"] },
      { date: "December 4–10, 2024", event: "Lyft appointed Reider executive vice president of Lyft Media and Lyft Business, reporting to CEO David Risher.", sourceIds: ["lyft-announcement", "mediapost"] },
    ],
    interpretation: "Reider's case tests portability inside large companies: she could carry knowledge of advertising, video, local commerce, and platform monetization across YouTube, Waze, and Lyft, while the audience, data, product, capital, and distribution remained institution-owned.",
    complication: [
      "Appointment announcements document senior roles but do not establish how much platform performance was personally caused by Reider rather than teams, acquisitions, market position, and Google's infrastructure.",
      "The Waze pandemic record shows that even a sophisticated advertising operation remained dependent on mobility behavior and advertiser demand outside the leader's control.",
      "Public sources do not establish Reider's budgets, internal decision rights, product ownership, or the successor-capability of the businesses she leads.",
    ],
    unknowns: [
      "What binding product, pricing, hiring, and data-access decisions sit with Reider at Lyft?",
      "Which methods or relationships moved with her from Google, and which remained proprietary or team-embedded?",
      "What structures would allow Lyft Media and Lyft Business to continue beyond their current executive sponsor?",
    ],
    payoff: "The case distinguishes portable executive judgment from portable infrastructure. Reider can carry expertise and credibility; the systems through which they produce value still belong to the companies supplying data, products, teams, and distribution.",
    sources: [
      { id: "lyft-announcement", label: "Lyft appointment announcement and reporting line", href: "https://www.lyft.com/blog/posts/lyft-welcomes-suzie-reider", publisher: "Lyft", published: "2024-12-04", kind: "primary" },
      { id: "middlebury-career", label: "Career chronology across Ziff-Davis, CNET, YouTube, and Waze", href: "https://www.middlebury.edu/middcore/suzie-reider", publisher: "Middlebury College", published: "See linked record", kind: "institutional" },
      { id: "middlebury-trustee", label: "Institutional biography describing YouTube and Waze leadership", href: "https://www.middlebury.edu/about-middlebury/suzanne-reider-87", publisher: "Middlebury College", published: "See linked record", kind: "institutional" },
      { id: "mediapost", label: "Independent report on the Lyft appointment", href: "https://www.mediapost.com/publications/article/401629/googles-suzie-reider-joins-lyft.html", publisher: "MediaPost", published: "2024-12-04", kind: "independent" },
      { id: "bi-waze", label: "Independent report on Waze's pandemic advertising dependence", href: "https://www.businessinsider.com/how-googles-waze-salvaged-its-ad-business-amid-the-coronavirus-2020-6", publisher: "Business Insider", published: "2020-06-04", kind: "independent" },
      { id: "modern-retail", label: "Interview on Waze traffic and retail-advertising dependence", href: "https://www.modernretail.co/retailers/wazes-suzie-reider-on-the-return-of-road-traffic-and-the-retailers-that-depend-on-it/", publisher: "Modern Retail", published: "2020-11-05", kind: "independent" },
    ],
  },
  "kenny-gold": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "Before 2021", event: "Gold led social-media work at Grey Group North America before moving from agency work into consulting.", sourceIds: ["aef-bio", "gold-reflection"] },
      { date: "2021", event: "Gold joined Deloitte Digital as managing director and head of social, content, and influencer.", sourceIds: ["aef-bio"] },
      { date: "2023–2025", event: "Public appearances documented Gold's thesis that creators should retain authentic voice, receive support and compensation, and use AI as an enabling tool.", sourceIds: ["buzzincontent", "cmo-podcast", "gold-creator-post"] },
      { date: "June 2, 2026", event: "Edelman appointed Gold global chief creator officer to lead Edelman Creator across a network of approximately 200 specialists.", sourceIds: ["edelman-announcement", "gold-reflection"] },
    ],
    interpretation: "Gold's case examines how a specialist turns a cross-functional practice into an executive mandate across institutions. A thesis, reputation, relationships, and practice-building experience travel; each firm's staff, clients, data, budgets, and authority do not.",
    complication: [
      "A first-ever global title signals recognition but does not establish independent budget, hiring authority, or control over regional teams.",
      "Edelman's approximately 200 creator specialists predated the appointment, so the mandate inherits substantial institutional capacity.",
      "Gold's public philosophy is evidence of a consistent point of view, not proof that client outcomes or organizational change were caused by him alone.",
    ],
    unknowns: [
      "Which global standards, budgets, hiring decisions, and client decisions can Gold make rather than influence?",
      "What portion of Deloitte Digital's creator capability can be attributed to Gold rather than distributed teams?",
      "Will Edelman's creator mandate become durable governance, methods, and succession capacity beyond its first global officeholder?",
    ],
    payoff: "The case separates carrying a field-building point of view from controlling the institution that adopts it. Durability depends on decision rights, routines, distributed capability, and succession—not the novelty of the title.",
    sources: [
      { id: "edelman-announcement", label: "Edelman appointment, reporting line, mandate, and existing team scale", href: "https://www.edelman.com/news-awards/kenny-gold-global-chief-creator-officer", publisher: "Edelman", published: "2026-06-02", kind: "primary" },
      { id: "gold-reflection", label: "First-person account of moving into consulting and building at Deloitte Digital", href: "https://www.linkedin.com/posts/kennethrgold_nearly-five-years-ago-i-took-a-bet-on-myself-activity-7460702920838246400-2cVb", publisher: "Kenny Gold / LinkedIn", published: "2026", kind: "primary" },
      { id: "aef-bio", label: "Institutional biography documenting Grey and Deloitte roles", href: "https://aef.com/partnership-programs/honors-night/honors2021/2021-champions/champion-gold/", publisher: "Advertising Educational Foundation", published: "2021", kind: "institutional" },
      { id: "buzzincontent", label: "Independent report on Gold's creator and AI position", href: "https://www.buzzincontent.com/story/ai-is-an-ally-not-a-replacement-for-creators-deloitte-digital-single-s-kenny-gold/", publisher: "BuzzInContent", published: "2023-06-21", kind: "independent" },
      { id: "cmo-podcast", label: "Creator-economy roundtable documenting Gold's role and thesis", href: "https://podscan.fm/podcasts/the-cmo-podcast/episodes/the-creator-economy-roundtable-with-brandon-b-kim-larson-youtube-and-kenny-gold-deloitte-digital", publisher: "The CMO Podcast", published: "2025-06-25", kind: "independent" },
      { id: "gold-creator-post", label: "First-person articulation of creator autonomy in brand partnerships", href: "https://www.linkedin.com/videos/kennethrgold_creatoreconomy-advertising-content-activity-7394014142975721472-eu7w", publisher: "Kenny Gold / LinkedIn", published: "2025", kind: "primary" },
    ],
  },
  "steven-bartlett": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "2014–2017", event: "Bartlett and Dominic McGregor built Social Chain; Bartlett began The Diary of a CEO in 2017 while still associated with the company.", sourceIds: ["guardian-profile", "prolific-listing", "flightstory-show"] },
      { date: "October 2019", event: "Social Chain combined with Lumaland and traded in Germany; reporting named Bartlett as one of three co-CEOs.", sourceIds: ["prolific-listing"] },
      { date: "August 2020", event: "Bartlett and McGregor announced their departure from Social Chain.", sourceIds: ["prolific-departure", "guardian-profile"] },
      { date: "2021–2024", event: "The podcast expanded while Bartlett held financial relationships with Huel and ZOE; ASA rulings found advertising disclosures inadequate.", sourceIds: ["asa-huel-2022", "asa-huel-2024", "asa-zoe-2024"] },
      { date: "December 2024", event: "A BBC investigation reported recurring harmful health claims in sampled episodes and questioned editorial challenge and verification.", sourceIds: ["bbc-health", "guardian-health"] },
      { date: "2025–2026", event: "FlightStory and Steven.com described a broader system spanning creator media, communities, products, and technology.", sourceIds: ["flightstory-show", "steven-company"] },
    ],
    interpretation: "Bartlett's case examines whether audience attention can become owned media and operating infrastructure beyond one platform. The portfolio creates more capacity than a personal channel alone, but discovery, authority, monetization, and demand remain closely tied to Bartlett and major distributors.",
    complication: [
      "Social Chain's history identifies co-founders, co-CEOs, merger partners, investors, and a later departure; it does not support a sole-builder account.",
      "Commercial scale is not evidence of editorial reliability. BBC reporting and ASA rulings document verification and disclosure failures.",
      "Venture diversity can coexist with dependence on one person's visibility, voice, relationships, and reputation.",
      "Company descriptions do not establish entity-level ownership, audience-data rights, licensing, intercompany agreements, or succession.",
    ],
    unknowns: [
      "Which entities own the podcast name, archive, feeds, formats, audience data, and derivative rights?",
      "What ownership and control rights does Bartlett hold across FlightStory, Steven.com, Flight Fund, and related ventures?",
      "Which platform and distribution relationships are portable if partners change terms?",
      "What editorial, medical-review, corrections, and conflict-disclosure standards govern health content?",
      "What could continue at comparable quality and demand without Bartlett?",
    ],
    payoff: "Attention can seed an institution, but durability depends on rights, governance, editorial controls, direct audience relationships, distributed capability, and succession—not reach or venture count.",
    sources: [
      { id: "guardian-profile", label: "Independent career profile", href: "https://www.theguardian.com/tv-and-radio/2022/jan/06/steven-bartlett-dragons-den-interview", publisher: "The Guardian", published: "2022-01-06", kind: "independent" },
      { id: "prolific-listing", label: "Contemporaneous Social Chain listing report", href: "https://www.prolificnorth.co.uk/news/social-chain-goes-public-german-stock-exchange/", publisher: "Prolific North", published: "2019-10-17", kind: "independent" },
      { id: "prolific-departure", label: "Contemporaneous founder-departure report", href: "https://www.prolificnorth.co.uk/news/co-founders-steven-bartlett-and-dominic-mcgregor-leave-social-chain/", publisher: "Prolific North", published: "2020-08-17", kind: "independent" },
      { id: "flightstory-show", label: "FlightStory description of the show", href: "https://www.flightstory.com/shows/diary-of-a-ceo", publisher: "FlightStory", published: "Current record", kind: "primary" },
      { id: "steven-company", label: "Steven.com system description", href: "https://steven.com/", publisher: "Steven.com", published: "Current record", kind: "primary" },
      { id: "asa-huel-2022", label: "Huel podcast advertising ruling", href: "https://www.asa.org.uk/rulings/huel-ltd-a22-1140981-huel-ltd.html", publisher: "Advertising Standards Authority", published: "2022-08-10", kind: "institutional" },
      { id: "asa-huel-2024", label: "Huel financial-interest disclosure ruling", href: "https://www.asa.org.uk/rulings/huel-ltd-g24-1237493-huel-ltd.html", publisher: "Advertising Standards Authority", published: "2024-08-14", kind: "institutional" },
      { id: "asa-zoe-2024", label: "ZOE financial-interest disclosure ruling", href: "https://www.asa.org.uk/rulings/zoe-ltd-g24-1237489-zoe-ltd.html", publisher: "Advertising Standards Authority", published: "2024-08-14", kind: "institutional" },
      { id: "bbc-health", label: "Investigation of health claims in sampled episodes", href: "https://www.bbc.com/news/articles/c4gpz163vg2o", publisher: "BBC World Service", published: "2024-12-13", kind: "independent" },
      { id: "guardian-health", label: "Report on the investigation and company response", href: "https://www.theguardian.com/media/2024/dec/13/steven-bartlett-accused-of-amplifying-dangerous-health-claims-on-his-podcast", publisher: "The Guardian", published: "2024-12-13", kind: "independent" },
    ],
  },
  "ashley-rudder": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "Approximately 2000–2020", event: "Rudder developed from makeup artist into digital-content and artistry leadership during a long M·A·C career.", sourceIds: ["muse-interview", "whalar-announcement"] },
      { date: "2020–2022", event: "She moved through senior creative and creator-strategy roles and developed her creator practice and HAUS OF SÔS collective.", sourceIds: ["muse-interview", "bi-whalar", "haus"] },
      { date: "December 2022–January 2023", event: "Whalar named Rudder Global Chief Creator Officer with a stated remit spanning guidance, support, advocacy, safety, pay, representation, and creative excellence.", sourceIds: ["whalar-announcement", "bi-whalar"] },
      { date: "2024", event: "Deutsch New York appointed Rudder its first chief creator officer as it launched SociStudio.", sourceIds: ["muse-interview", "deutsch-report"] },
    ],
    interpretation: "Rudder's case tests whether practitioner knowledge and creator participation can become an organizational mandate rather than remain campaign labor. Her expertise travels; institutional teams, clients, budgets, and distribution do not.",
    complication: [
      "First-of-kind titles do not establish binding decision rights, budget control, or durability.",
      "Both organizations had pre-existing capabilities, so appointment announcements cannot isolate Rudder's causal contribution.",
      "The record is rich in appointments and first-person explanation but thin on independent outcome, governance, budget, pay-equity, and succession evidence.",
      "Her executive, creator, and collective roles can aid translation while complicating whose interests, IP, and attribution a decision represents.",
    ],
    unknowns: [
      "What binding authority covered budgets, hiring, campaign approval, creator selection, pay, and client strategy?",
      "Which programs and policies were created by Rudder rather than inherited or jointly produced?",
      "What evidence shows changes in creator pay, representation, safety, retention, quality, or client outcomes?",
      "Who owns methods and IP developed across her personal practice, HAUS OF SÔS, Whalar, and Deutsch?",
      "Did either organization preserve the office, remit, or routines after her tenure?",
    ],
    payoff: "Creator judgment becomes institutional only through authority, repeatable policy, evidence of changed practice, distributed capability, and succession—not a novel title.",
    sources: [
      { id: "whalar-announcement", label: "Whalar announcement defining the remit", href: "https://www.prnewswire.com/news-releases/whalar-names-ashley-rudder-first-ever-chief-creator-officer-301729971.html", publisher: "Whalar / PR Newswire", published: "2023-01-25", kind: "primary" },
      { id: "bi-whalar", label: "Independent report and first-person role account", href: "https://www.businessinsider.com/whalar-global-chief-creator-officer-new-c-suite-role-position-2023-1", publisher: "Business Insider", published: "2023-01-30", kind: "independent" },
      { id: "muse-interview", label: "Career chronology and Deutsch role interview", href: "https://musebyclios.com/culture-creators/ashley-rudder-on-steering-deutsch-n-y-deeper-into-creator-content/", publisher: "Muse by Clio", published: "2024-08-14", kind: "independent" },
      { id: "deutsch-report", label: "Institutional report on the Deutsch remit", href: "https://attivogroup.co/news/dnys-ashley-rudder-talks-to-muse-by-clio-about-delving-deeper-into-creator-content/", publisher: "Attivo Group", published: "2024-08-14", kind: "institutional" },
      { id: "haus", label: "Creator collective record", href: "https://www.hausofsos.com/", publisher: "HAUS OF SÔS", published: "Current record", kind: "primary" },
      { id: "linkedin-career", label: "Self-maintained role chronology", href: "https://www.linkedin.com/in/ashleyrudder1", publisher: "Ashley Rudder / LinkedIn", published: "Current record", kind: "primary" },
    ],
  },
  "gordon-glenister": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "2007–May 2018", event: "Glenister served as Director General of the British Promotional Merchandise Association for approximately eleven years before leaving association employment.", sourceIds: ["bpma-departure", "bcma-profile", "bigeye"] },
      { date: "2018–2019", event: "After leaving BPMA, Glenister moved into independent membership consulting and describes proposing an influencer-marketing trade-body function with BCMA co-founder Andrew Canter.", sourceIds: ["bigeye", "bcma-profile"] },
      { date: "2019–2020", event: "BCMA Influence and the Influence Global podcast became visible public infrastructure; BCMA documented Glenister as Global Head and organizer/head judge of Pitch Influence.", sourceIds: ["bcma-profile", "bcma-guidelines", "bcma-pitch", "apple-podcast"] },
      { date: "2021–2024", event: "Glenister published two editions of Influencer Marketing Strategy while IMTB and ISBA developed a jointly owned code situated within the ASA/CMA regulatory framework.", sourceIds: ["kogan", "imtb-code", "asa-resources"] },
      { date: "December 2024–2026", event: "IMTB partnered with the ASA on weight-loss-drug advertising communication, while the code, podcast, consulting, education, and convening work remained active.", sourceIds: ["imtb-asa", "imtb-code", "glenister-site"] },
    ],
    interpretation: "Glenister's case is strongest as a study of portable association-building capability. He carried membership, convening, publishing, and standards work from one field into another, but the resulting infrastructure belongs to overlapping institutions, collaborators, regulators, publishers, platforms, and clients—not to one founder alone.",
    complication: [
      "Glenister's own formation account is plural: he and Andrew Canter decided to launch Influence inside the pre-existing BCMA. That does not support sole-founder or personal-ownership language.",
      "The ISBA/IMTB code has institutional recognition and signatories, but public adoption does not establish universal compliance, enforcement, or Glenister's individual causal effect.",
      "BCMA, IMTB, ASA, CMA, ISBA, member agencies, creators, advertisers, and platforms are competing explanations for the field's professionalization.",
      "The public portfolio remains closely connected to Glenister's voice and convening; successor-capable operation has not been demonstrated.",
    ],
    unknowns: [
      "What legal, budgetary, voting, staffing, and succession authority did Glenister hold in BCMA Influence and IMTB?",
      "Who drafted, owns, updates, audits, and enforces each part of the code, and what measurable compliance followed?",
      "Which podcast, book, course, consultancy, audience-data, and methodology rights belong to Glenister, publishers, platforms, clients, or institutions?",
      "Which programs and relationships would continue at comparable quality if Glenister stopped convening them?",
    ],
    payoff: "Field-building can be a genuine institution-of-one pathway without becoming personal ownership. The durable asset is not the founder story; it is the degree to which language, standards, relationships, and practices become governed, distributed, measurable, and successor-capable.",
    sources: [
      { id: "bpma-departure", label: "Contemporaneous BPMA departure report", href: "https://www.sourcingcitynews.co.uk/gordon-glenister-resigns-from-bpma/", publisher: "Sourcing City News", published: "2018-05", kind: "independent" },
      { id: "bcma-profile", label: "BCMA Influence remit and Glenister role", href: "https://thebcma.info/about/chapters/bcma-influence.html", publisher: "Branded Content Marketing Association", published: "Current record", kind: "institutional" },
      { id: "bcma-guidelines", label: "BCMA influencer guidelines and founding steering group", href: "https://www.thebcma.info/onewebmedia/DOWNLOADABLE%20DOCUMENTS/BCMA%20Influencer%20Marketing%20Guidelines%20and%20Best%20Practice%20UK.pdf", publisher: "Branded Content Marketing Association", published: "See linked record", kind: "institutional" },
      { id: "bcma-pitch", label: "Pitch Influence organizer and judging record", href: "https://www.thebcma.info/onewebmedia/DOWNLOADABLE%20DOCUMENTS/BCMA%20-%20Pitch%20Influence%202020%20-%20Winners%20Announced.pdf", publisher: "Branded Content Marketing Association", published: "2020-11", kind: "institutional" },
      { id: "bigeye", label: "Detailed first-person account of the BPMA transition and joint BCMA launch", href: "https://www.bigeyeagency.com/podcast/influencer-marketing-strategy-with-gordon-glenister", publisher: "Bigeye", published: "2024-09-03", kind: "independent" },
      { id: "apple-podcast", label: "Influence Global distribution record", href: "https://podcasts.apple.com/gb/podcast/influence-global/id1463375054", publisher: "Apple Podcasts", published: "Current record", kind: "primary" },
      { id: "kogan", label: "Influencer Marketing Strategy publisher record", href: "https://www.koganpage.com/marketing-communications/influencer-marketing-strategy-9781398615620", publisher: "Kogan Page", published: "2024", kind: "institutional" },
      { id: "imtb-code", label: "Joint ISBA/IMTB code, scope, recognition, and signatories", href: "https://imtb.org.uk/influencer-marketing-code-of-conduct/", publisher: "Influencer Marketing Trade Body", published: "Current record", kind: "institutional" },
      { id: "asa-resources", label: "Regulator guidance placing the code within wider advertising rules", href: "https://www.asa.org.uk/advice-and-resources/resource-library/influencer-marketing-key-advice-resources.html", publisher: "Advertising Standards Authority", published: "Current record", kind: "institutional" },
      { id: "imtb-asa", label: "ASA and IMTB weight-loss-drug advertising communication", href: "https://imtb.org.uk/imtb-partners-with-asa-to-warn-weight-loss-drug-advertisers/", publisher: "IMTB / ASA", published: "2024-12-05", kind: "institutional" },
      { id: "glenister-site", label: "Current founder-led services and media portfolio", href: "https://www.gordonglenister.com/about", publisher: "Gordon Glenister", published: "Current record", kind: "primary" },
    ],
  },
  "claire-zau": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "Approximately 2020–2024", event: "Zau developed an early-stage investing career at GSV Ventures and worked across investment, AI coverage, ASU+GSV programming, and thought leadership.", sourceIds: ["gsv-profile", "asugsv-profile", "forbes"] },
      { date: "2024–2025", event: "She expanded public AI and startup communication through institutional media, an AI-and-education newsletter, and personal short-form channels while still working at GSV.", sourceIds: ["asugsv-weekly", "stanford-directory", "fortune"] },
      { date: "May 2026", event: "Lightspeed appointed Zau Partner & New Media in a combined pre-seed/seed investing and media mandate; reporting described the role as a first for the firm.", sourceIds: ["lightspeed-profile", "zau-announcement", "bi-role"] },
      { date: "May–July 2026", event: "The public remit included shaping new-media strategy, co-hosting Lightwork, and supporting Lightspeed Launch, while Zau said her personal channels would remain independent.", sourceIds: ["lightspeed-profile", "bi-role", "lightspeed-launch"] },
    ],
    interpretation: "Zau's case makes distribution visible as professional capital: investing judgment, accessible AI explanation, and direct social reach traveled together into a new institutional mandate. The key boundary is that portable identity and audience access do not establish ownership of platform distribution, firm media, portfolio outcomes, or investment authority.",
    complication: [
      "The transition is not simply audience-to-company: Zau's media and investment work already overlapped at GSV, so institutional infrastructure helped shape the public authority that later traveled.",
      "A firm-first combined title does not establish profession-wide novelty, sole role authorship, partnership economics, or investment-committee power.",
      "Calling personal accounts independent does not resolve employment covenants, content approvals, sponsorships, IP, audience data, portfolio conflicts, or disclosure rules.",
      "The role is too recent to establish outcomes, durability, succession, or whether media attention improves investment performance.",
    ],
    unknowns: [
      "What investment, hiring, budget, publishing, and portfolio-support decisions can Zau make rather than recommend?",
      "How are portfolio holdings, firm interests, sponsorships, recruiting posts, and editorial subjects disclosed across personal and firm media?",
      "Who owns personal-account content, raw audience data, Lightwork IP, production assets, and derivative formats?",
      "What parts of the combined mandate could continue without Zau, and what parts depend on her identity and existing audience?",
    ],
    payoff: "Distribution can become bargaining power and an institutional capability, but independence has layers. Account identity, platform control, employment incentives, firm-owned media, audience trust, and investment authority must be examined separately.",
    sources: [
      { id: "lightspeed-profile", label: "Current title, investment stage, new-media remit, and Lightwork role", href: "https://lsvp.com/team-member/claire-zau/", publisher: "Lightspeed Venture Partners", published: "Current record", kind: "institutional" },
      { id: "zau-announcement", label: "First-person Lightspeed appointment and prior-work chronology", href: "https://www.linkedin.com/posts/clairezau_im-beyond-excited-to-announce-that-im-joining-activity-7460414042734706688-8Xjn", publisher: "Claire Zau / LinkedIn", published: "2026-05", kind: "primary" },
      { id: "bi-role", label: "Independent report on dual mandate, reporting lines, Launch, and personal-channel independence", href: "https://www.businessinsider.com/why-lightspeed-ventures-hired-first-creator-seed-investor-claire-zau-2026-5", publisher: "Business Insider", published: "2026-05-23", kind: "independent" },
      { id: "fortune", label: "Independent profile of the GSV-to-Lightspeed transition and audience growth", href: "https://fortune.com/media/a9e68e36-f547-4aed-ad61-fcb1ebfff0a9", publisher: "Fortune", published: "2026-05-13", kind: "independent" },
      { id: "gsv-profile", label: "Former Partner and AI Lead biography", href: "https://gsv.ventures/our-team/", publisher: "GSV Ventures", published: "Archived/current snapshot", kind: "institutional" },
      { id: "asugsv-profile", label: "Prior investing, programming, and thought-leadership work", href: "https://asugsvsummit.com/leadership/claire-zau", publisher: "ASU+GSV Summit", published: "Current record", kind: "institutional" },
      { id: "asugsv-weekly", label: "Institutional AI & Education Weekly hosting record", href: "https://asugsvsummit.com/video/ai-education-weekly-with-claire-zau-gsvtv-2", publisher: "ASU+GSV Summit", published: "2025", kind: "institutional" },
      { id: "stanford-directory", label: "Independent institutional listing of the AI-and-education newsletter", href: "https://edupreneurship.stanford.edu/resource/education-innovation-newsletters/", publisher: "Stanford University", published: "Current record", kind: "institutional" },
      { id: "forbes", label: "GSV role and named AI investments", href: "https://www.forbes.com/profile/claire-zau/", publisher: "Forbes", published: "2025-01-01", kind: "independent" },
      { id: "lightspeed-launch", label: "Pre-existing founder-support program", href: "https://lsvp.com/launch/", publisher: "Lightspeed Venture Partners", published: "Current record", kind: "institutional" },
    ],
  },
  "brad-keywell": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "1999–2012", event: "Keywell repeatedly co-founded companies with other entrepreneurs, including Starbelly, Echo Global Logistics, MediaBank/Mediaocean, Groupon, and Lightbank; several later reached public markets, merged, or were acquired.", sourceIds: ["tko-proxy", "tribune-starbelly", "groupon-sec", "mediaocean-history"] },
      { date: "2011–2014", event: "He extended institution-building beyond operating companies through Chicago Ideas, Future Founders, teaching, and the Illinois Innovation Council, while continuing venture investing through Lightbank.", sourceIds: ["chicago-ideas", "future-founders", "illinois-council", "booth-profile"] },
      { date: "2014–2019", event: "Keywell founded and led Uptake, an industrial-AI company. Independent reporting documented both rapid private-market valuation and later commercial and organizational strain, including litigation with GE that ended in settlement.", sourceIds: ["reuters-uptake", "ey-profile", "ge-complaint", "ge-settlement"] },
      { date: "2018–2023", event: "He founded WNDR Museum and developed a public art practice, while WNDR's expansion depended on a wider studio, curatorial, artist, operational, and venue network.", sourceIds: ["newcity-wndr", "daily-aztec-wndr", "wndr-installation"] },
      { date: "2024–2026", event: "Keywell joined TKO Group's board and founded Gigawatt AI, returning to utility-focused artificial intelligence in a new company with an operating leadership team.", sourceIds: ["tko-proxy", "gigawatt-company", "gigawatt-thesis"] },
    ],
    interpretation: "Keywell's case tests whether repeated founding can become a portable institution-building practice across technology, investing, civic convening, education, and art. Judgment, capital, relationships, pattern recognition, and public credibility travel; each company's people, intellectual property, customers, governance, and operating systems remain entity-specific and jointly produced.",
    complication: [
      "The visible pattern is repeated co-founding, not solitary creation. Groupon, Lightbank, Echo, MediaBank/Mediaocean, and other ventures had co-founders, executives, employees, investors, boards, and counterparties whose contributions cannot be assigned to Keywell alone.",
      "Private valuation and awards document recognition and investor expectations, not durable operating performance. Uptake's later restructuring and the opposing GE lawsuits complicate a frictionless account of industrial-AI success.",
      "A broad portfolio can diversify institutional dependence while increasing dependence on Keywell's capital, reputation, relationships, and ability to initiate the next organization.",
      "WNDR's founder narrative coexists with identifiable creative and operational teams and participating artists; founding the venue does not establish sole authorship of its works or visitor experience.",
      "Gigawatt is too new to establish market outcomes, institutional durability, or whether the new company carries forward Uptake's assets, methods, personnel, or merely a related thesis.",
    ],
    unknowns: [
      "What equity, voting, board, and intellectual-property rights does Keywell retain in each active entity?",
      "Which repeatable methods genuinely moved between ventures, and which capabilities were rebuilt by different teams?",
      "How are capital, staff, data, technology, and opportunities allocated among Keywell's overlapping companies, funds, civic projects, and art institutions?",
      "What governance and succession structures allow Chicago Ideas, WNDR, Uptake, Gigawatt, and related initiatives to continue without his active sponsorship?",
      "What became of Uptake's technology, customers, personnel, and commercial lessons, and what relationship—if any—do they have to Gigawatt?",
    ],
    payoff: "Repeated founding can be a portable capability, but a portfolio is not itself an institution of one. The structural question is whether initiation becomes distributed governance, operating capacity, rights, and succession—or remains a sequence continually dependent on the same founder's capital and attention.",
    sources: [
      { id: "tko-proxy", label: "Public-company biography documenting board service, Uptake, and Gigawatt roles", href: "https://investor.tkogrp.com/governance/board-of-directors/person-details/default.aspx?ItemId=f95e7a1b-cc0b-44ce-b659-480fbd29ef73", publisher: "TKO Group Holdings", published: "Current record", kind: "institutional" },
      { id: "tribune-starbelly", label: "Contemporaneous report on the Starbelly acquisition", href: "https://www.chicagotribune.com/2000/01/24/ha-lo-buys-starbellycom/", publisher: "Chicago Tribune", published: "2000-01-24", kind: "independent" },
      { id: "groupon-sec", label: "Groupon public filing documenting founders, governance, and company history", href: "https://www.sec.gov/Archives/edgar/data/1490281/000119312511297149/d190362ds1a.htm", publisher: "U.S. Securities and Exchange Commission", published: "2011-11-01", kind: "institutional" },
      { id: "mediaocean-history", label: "Company history of the MediaBank and Donovan Data Systems combination", href: "https://www.mediaocean.com/about-us", publisher: "Mediaocean", published: "Current record", kind: "primary" },
      { id: "chicago-ideas", label: "Founder and chair role in the civic ideas platform", href: "https://www.chicagoideas.com/people/brad-keywell", publisher: "Chicago Ideas", published: "Current record", kind: "institutional" },
      { id: "future-founders", label: "Founding-chair record and cross-venture biography", href: "https://www.futurefounders.com/bradkeywell/", publisher: "Future Founders", published: "Current record", kind: "institutional" },
      { id: "illinois-council", label: "State announcement creating the Illinois Innovation Council", href: "https://www.illinois.gov/news/press-release.9229.html", publisher: "State of Illinois", published: "2011-02-16", kind: "institutional" },
      { id: "booth-profile", label: "Teaching role and entrepreneurship biography", href: "https://www.chicagobooth.edu/faculty/directory/k/brad-keywell", publisher: "University of Chicago Booth School of Business", published: "Current record", kind: "institutional" },
      { id: "reuters-uptake", label: "Independent report on Uptake funding and private-market valuation", href: "https://www.reuters.com/article/us-uptake-funding-idUSKBN1D82W2/", publisher: "Reuters", published: "2017-11-09", kind: "independent" },
      { id: "ey-profile", label: "Uptake founder narrative and 2019 entrepreneurship award", href: "https://www.ey.com/en_gl/weoy/ey-world-entrepreneur-of-the-year-2019-brad-keywell-us", publisher: "EY", published: "2019", kind: "institutional" },
      { id: "ge-complaint", label: "GE complaint stating disputed commercial and personnel allegations against Uptake", href: "https://media.bizj.us/view/img/11243368/ge-lawsuit-2.pdf", publisher: "U.S. District Court / GE filing", published: "2018-12-17", kind: "institutional" },
      { id: "ge-settlement", label: "Independent report that the opposing GE and Uptake suits settled without disclosed terms", href: "https://www.bizjournals.com/chicago/news/2019/08/05/ge-and-uptake-agree-to-make-nice-settle-opposing.html", publisher: "Chicago Business Journal", published: "2019-08-05", kind: "independent" },
      { id: "newcity-wndr", label: "Independent account identifying the wider WNDR creative operation", href: "https://design.newcity.com/2023/08/30/question-everything-how-david-allen-creates-instagrammable-wndr-museum-experiences-without-selling-his-soul/", publisher: "Newcity Design", published: "2023-08-30", kind: "independent" },
      { id: "daily-aztec-wndr", label: "Independent report on WNDR expansion and its studio team", href: "https://thedailyaztec.com/112248/artsandculture/interactive-wndr-museum-to-open-first-west-coast-location-in-san-diego/", publisher: "The Daily Aztec", published: "2022-12-08", kind: "independent" },
      { id: "wndr-installation", label: "Museum record of Keywell's public art installation", href: "https://www.wndrmuseum.com/installations/chicago/we-are-all-artists", publisher: "WNDR Museum", published: "2020", kind: "primary" },
      { id: "gigawatt-company", label: "Current operating team and founder role at Gigawatt", href: "https://gigawatt.ai/company/", publisher: "Gigawatt AI", published: "Current record", kind: "primary" },
      { id: "gigawatt-thesis", label: "First-person statement introducing the utility-AI thesis", href: "https://www.linkedin.com/pulse/introducing-gigawatt-foundation-next-era-utilities-brad-keywell-ddjre", publisher: "Brad Keywell / LinkedIn", published: "2026-05-12", kind: "primary" },
    ],
  },
  "klitos-teklos": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "1999–2003", event: "Teklos moved from Cyprus to New York for advertising and communications-design study, then entered editorial design before moving into fashion advertising at AR New York.", sourceIds: ["cyprus-interview", "teklos-bio"] },
      { date: "Approximately 2006–2018", event: "He spent roughly twelve years at AIR PARIS, ultimately leading creative work across New York, Paris, and Shanghai for fashion, beauty, and luxury clients.", sourceIds: ["linkedin-career", "models-profile", "cyprus-interview"] },
      { date: "2018–2023", event: "At Estée Lauder Companies, Teklos held senior global creative responsibility across a portfolio of fragrance, men's, and skincare brands, spanning strategy, product, packaging, advertising, stores, experiences, and creative operations.", sourceIds: ["teklos-bio", "comparably-elc", "lab-series"] },
      { date: "2023–2026", event: "He founded Tēklos Studio and used embedded brand residencies for work with The Row, Sol de Janeiro, and Gap Inc.'s beauty initiative, moving from company employment into an independent, client-linked operating model.", sourceIds: ["teklos-studio", "linkedin-career", "fashionunited"] },
      { date: "July 7, 2026", event: "Tory Burch appointed Teklos its first chief brand officer, with responsibility for global brand strategy, marketing, social media, and visual merchandising, reporting to Tory Burch and working with the company's existing executive and creative leadership.", sourceIds: ["wwd-appointment", "bof-appointment", "fashionunited", "teklos-announcement"] },
    ],
    interpretation: "Teklos's case tests whether a creative practice can travel among agency, corporate portfolio, founder-owned studio, embedded client residency, and a newly created executive mandate. His aesthetic judgment, cross-category experience, relationships, and portfolio travel; client brands, teams, budgets, distribution, archives, consumer data, and product rights remain institution-controlled.",
    complication: [
      "The studio's case record is largely self-described. Client names and visible campaigns establish engagements, but not contract terms, scope, causal contribution, commercial outcomes, or ownership of the resulting work.",
      "Creative output is distributed across in-house teams, agencies, photographers, directors, designers, executives, founders, licensors, retailers, and production partners; public credits do not support sole authorship.",
      "An embedded residency can offer influence without ownership. The client may retain the trademarks, product rights, consumer relationships, data, and final approval while the studio remains dependent on a small number of major accounts.",
      "The Tory Burch role reverses the move toward independence: it converts portable practice into formal corporate authority, but public reporting does not establish budget, hiring, product approval, or decision rights beyond the announced remit.",
      "Because the Tory Burch appointment is new, there is no evidence yet of outcomes, durability, or whether the first-holder mandate can survive a leadership change.",
    ],
    unknowns: [
      "Does Tēklos Studio continue while Teklos serves at Tory Burch, and how are conflicts, clients, staff, and active obligations handled?",
      "Who owns the studio name, methods, archives, working files, campaign assets, product concepts, and derivative rights created during brand residencies?",
      "What binding budget, hiring, approval, and organizational authority accompanies the Tory Burch chief brand officer title?",
      "Which Sol de Janeiro, Gap, Estée Lauder, and agency outcomes can be causally connected to Teklos's contribution rather than wider teams and market conditions?",
      "What operating systems, staff capabilities, and succession arrangements allow the studio or corporate mandate to continue without his direct creative attention?",
    ],
    payoff: "Creative portability is not the same as asset portability. A practitioner can carry judgment and reputation across organizational forms, but durable independence or institutional authority depends on contracts, rights, teams, decision power, client concentration, and succession.",
    sources: [
      { id: "teklos-bio", label: "First-person career and Estée Lauder portfolio biography", href: "https://www.klitosteklos.com/about", publisher: "Klitos Teklos", published: "Current record", kind: "primary" },
      { id: "teklos-studio", label: "Studio services, residencies, and named brand partnerships", href: "https://www.klitosteklos.com/", publisher: "Tēklos Studio", published: "Current record", kind: "primary" },
      { id: "linkedin-career", label: "Self-maintained chronology across AIR PARIS, Estée Lauder, studio, and brand work", href: "https://www.linkedin.com/in/klitosteklos", publisher: "Klitos Teklos / LinkedIn", published: "Current record", kind: "primary" },
      { id: "cyprus-interview", label: "Long-form interview on education and early agency career", href: "https://annakrith.wordpress.com/2017/09/09/klitos-teklos-interview-with-the-cypriot-creative-director-who-conquers-ny/", publisher: "Anna Krith", published: "2017-09-09", kind: "independent" },
      { id: "models-profile", label: "Independent industry profile and selected creative credits", href: "https://models.com/people/klitos-teklos", publisher: "Models.com", published: "Current record", kind: "independent" },
      { id: "comparably-elc", label: "Institutional executive listing for the Estée Lauder role", href: "https://www.comparably.com/companies/estee-lauder-companies/klitos-teklos", publisher: "Comparably", published: "Current record", kind: "independent" },
      { id: "lab-series", label: "First-person account of the LAB SERIES repositioning", href: "https://www.linkedin.com/posts/klitosteklos_how-est%C3%A9e-lauder-cos-lab-series-reinvented-activity-6890293930697850880-Fm8W", publisher: "Klitos Teklos / LinkedIn", published: "2022", kind: "primary" },
      { id: "wwd-appointment", label: "Independent appointment report and stated remit", href: "https://wwd.com/business-news/human-resources/tory-burch-names-klitos-teklos-chief-brand-officer-1239054554/", publisher: "WWD", published: "2026-07-07", kind: "independent" },
      { id: "bof-appointment", label: "Independent report identifying the first-holder mandate", href: "https://www.businessoffashion.com/news/luxury/tory-burch-names-first-chief-brand-officer/", publisher: "The Business of Fashion", published: "2026-07-07", kind: "independent" },
      { id: "fashionunited", label: "Independent report on studio clients, Gap beauty work, and Tory Burch responsibilities", href: "https://fashionunited.uk/news/people/tory-burch-names-klitos-teklos-chief-brand-officer/2026070889056", publisher: "FashionUnited", published: "2026-07-08", kind: "independent" },
      { id: "teklos-announcement", label: "First-person Tory Burch appointment statement", href: "https://www.linkedin.com/posts/klitosteklos_tory-burch-appoints-klitos-teklos-chief-brand-activity-7482395717081387008-NNk2", publisher: "Klitos Teklos / LinkedIn", published: "2026-07", kind: "primary" },
    ],
  },
  "charlotte-tansill": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "Approximately 2008–2021", event: "Tansill developed within Ogilvy over more than a decade across strategy and transformation roles, ultimately becoming global chief strategy officer for Ogilvy PR.", sourceIds: ["ogilvy-cso", "provokemedia-profile", "mediapost-appointment"] },
      { date: "2022–2025", event: "Ogilvy elevated Tansill to president of PR, social and influence for North America, placing previously distinct practices within one regional remit.", sourceIds: ["prweek-ogilvy", "provokemedia-profile", "prweek-power"] },
      { date: "2024", event: "Tansill was one of many credited leaders on the Michael CeraVe campaign, an integrated CeraVe, WPP Onefluence, Ogilvy, creator, media, production, and talent effort that used earned, social, influencer, paid, and owned channels.", sourceIds: ["one-show-credits", "shorty-credits", "ogilvy-cerave", "wharton-interview"] },
      { date: "November 24, 2025", event: "Publicis Creative U.S. appointed Tansill to the newly created role of president, social, creator and earned, reporting to global chief strategy officer Carla Serrano and joining the U.S. leadership team.", sourceIds: ["lbb-appointment", "prweek-publicis", "mediapost-appointment"] },
    ],
    interpretation: "Tansill's case tests whether an integration practice developed inside one agency network can travel into a new first-holder mandate. Her strategic judgment, relationships, campaign experience, and earned-first thesis travel; Publicis's clients, staff, data, budgets, intellectual property, and distribution remain institution-controlled.",
    complication: [
      "The Publicis role is described as collaboration across existing leaders and teams. A consolidated remit does not by itself establish consolidated budgets, staffing, approvals, client authority, or operating systems.",
      "Michael CeraVe is evidence of integrated work, but award records identify a large multi-organization team. They do not support sole-credit attribution to Tansill or isolate her causal contribution to the campaign's reach and awards.",
      "The appointment moved Tansill from one large holding-company network to another. It demonstrates executive portability, not independence from employer-owned infrastructure.",
      "Most evidence describes appointments, remit, recognition, and campaign outputs; it does not yet establish whether Publicis changed workflows, incentives, measurement, or client outcomes under the new structure.",
      "Because the Publicis office is new, continuity beyond its first holder and resilience through another reorganization remain untested.",
    ],
    unknowns: [
      "Which budgets, hiring decisions, pricing, client assignments, data, and creative approvals are actually integrated under Tansill?",
      "Which methods and relationships could she lawfully carry from Ogilvy, and which remained WPP-owned, client-owned, confidential, or team-embedded?",
      "How will Publicis distinguish and reconcile social, creator, earned, paid, and creative performance when incentives conflict?",
      "What measurable operating or client outcomes can be attributed to the new mandate rather than Publicis's inherited agencies and teams?",
      "What governance, documentation, distributed capability, and succession would allow the integrated practice to survive Tansill or another group reorganization?",
    ],
    payoff: "A cross-functional title can recognize portable integration expertise, but it becomes institutional only when reporting lines are matched by decision rights, shared systems, evidence of changed work, and successor-capable practice.",
    sources: [
      { id: "ogilvy-cso", label: "Ogilvy announcement of Tansill's global PR strategy role", href: "https://www.ogilvy.com/ideas/ogilvy-pr-appoints-global-chief-creative-officer-and-global-chief-strategy-officer", publisher: "Ogilvy", published: "2021-06-14", kind: "primary" },
      { id: "prweek-ogilvy", label: "Independent report on the North America PR, social and influence promotion", href: "https://www.prweek.com/article/1809894/ogilvy-pr-ups-charlotte-tansill-president-pr-social-influence", publisher: "PRWeek", published: "2022", kind: "independent" },
      { id: "provokemedia-profile", label: "Independent industry profile of Ogilvy tenure and integrated-work thesis", href: "https://www.provokemedia.com/ranking-and-data/innovator-25/innovator-25-2024/innovator-25-americas-2024/charlotte-tansill", publisher: "PRovoke Media", published: "2024", kind: "independent" },
      { id: "prweek-power", label: "Independent 2025 role and career profile", href: "https://www.prweek.com/article/1926246/prweek-power-list-2025-30-charlotte-tansill-ogilvy-pr", publisher: "PRWeek", published: "2025-07-23", kind: "independent" },
      { id: "ogilvy-cerave", label: "Ogilvy account of the campaign's integrated channel structure", href: "https://www.ogilvy.com/ideas/how-cerave-broke-mold-won-super-bowl", publisher: "Ogilvy", published: "2024-07-10", kind: "primary" },
      { id: "wharton-interview", label: "Joint interview with Tansill and CeraVe executive Adam Kornblum", href: "https://knowledge.wharton.upenn.edu/podcast/marketing-matters/charlotte-tansill-adam-kornblum-on-ceraves-super-bowl-ad-campaign/", publisher: "Wharton School", published: "2024", kind: "institutional" },
      { id: "one-show-credits", label: "Detailed multi-organization campaign credit record", href: "https://www.oneclub.org/awards/theoneshow/-award/52822/michael-cerave/", publisher: "The One Club for Creativity", published: "2024", kind: "institutional" },
      { id: "shorty-credits", label: "Additional client, agency, creator, and production credits", href: "https://shortyawards.com/17th/cerave-michael-cerave", publisher: "Shorty Awards", published: "2025", kind: "institutional" },
      { id: "lbb-appointment", label: "Publicis appointment, reporting line, leadership membership, and remit", href: "https://lbbonline.com/news/Charlotte-Tansill-Publicis-Creative-US-President-Social-Creator-Earned", publisher: "Little Black Book", published: "2025-11-24", kind: "independent" },
      { id: "prweek-publicis", label: "Independent report on the newly created Publicis role", href: "https://www.prweek.com/article/1940878/publicis-creative-us-hires-charlotte-tansill-president-social-creator-earned", publisher: "PRWeek", published: "2025-11-24", kind: "independent" },
      { id: "mediapost-appointment", label: "Independent career chronology and Publicis remit", href: "https://www.mediapost.com/publications/article/410937/ogilvy-veteran-tansill-will-lead-us-social-creato.html", publisher: "MediaPost", published: "2025-11-25", kind: "independent" },
    ],
  },
  "mo-gawdat": {
    documentationLevel: "saturated",
    reviewed: "2026-07-27",
    chronology: [
      { date: "Before 2007", event: "Gawdat built a technology-business career that included IBM, NCR, and approximately seven years at Microsoft before joining Google.", sourceIds: ["guardian-profile", "gawdat-site"] },
      { date: "2007–2018", event: "He worked at Google and became chief business officer of X, Google's moonshot organization; the public record supports a business leadership role, not sole authorship of X's technologies or research.", sourceIds: ["guardian-profile", "ai-for-good", "gawdat-site"] },
      { date: "2014–2017", event: "After the death of his son Ali, Gawdat developed his personal happiness framework, published Solve for Happy, and began the One Billion Happy mission.", sourceIds: ["guardian-profile", "macmillan-solve", "gawdat-site"] },
      { date: "2020–2024", event: "He distributed his work directly through Slo Mo, an ad-free interview podcast that accumulated more than 300 episodes, while publishing additional books on AI, thought, and stress.", sourceIds: ["apple-podcast", "gawdat-site", "macmillan-scary"] },
      { date: "May–June 2023", event: "Flight Story appointed Gawdat chief AI officer to advise the agency and its clients on AI adoption and regulation.", sourceIds: ["tech-eu-flightstory", "businesscloud-flightstory"] },
      { date: "2025–2026", event: "Gawdat co-founded Emma, an AI relationship and matchmaking product, moving from commentary about AI and human flourishing into a product whose emotional, clinical, privacy, and commercial claims require separate scrutiny.", sourceIds: ["emma-site", "emma-announcement", "sharjah-emma"] },
    ],
    interpretation: "Gawdat's case tests how institutional credibility becomes a personally distributed body of books, talks, podcasting, advocacy, advisory work, and a new company. His experience, voice, frameworks, audience, and some publishing assets travel; Google X's research authority, teams, data, technologies, and governance do not.",
    complication: [
      "Chief business officer experience at X supports technology commercialization and organizational knowledge, but it is not equivalent to being an AI research scientist, clinical psychologist, therapist, or sole creator of X's technical work.",
      "The happiness equation is presented as Gawdat's engineering-derived framework and personal interpretation. Public profiles do not establish it as a validated scientific model or clinical intervention.",
      "Slo Mo and the books create more direct distribution than an employed role, yet reach still depends on publishers, podcast platforms, social platforms, event organizers, guests, and Gawdat's personal visibility.",
      "Flight Story's commercial relationship means public AI commentary can coexist with advisory incentives; Emma adds a direct product interest in AI-mediated relationships.",
      "Emma's company descriptions and founder statements do not establish therapeutic efficacy, safety outcomes, privacy governance, model behavior, or the credentials and authority behind “therapist-backed” features.",
    ],
    unknowns: [
      "Which entities own the One Billion Happy name, book rights, podcast archive and feed, audience data, speaking materials, courses, trademarks, and derivative content?",
      "What formal structure, governance, funding, measurement, and succession—if any—support One Billion Happy beyond Gawdat's personal advocacy?",
      "Which public claims about happiness, stress, consciousness, AI timelines, and employment are evidence-based findings, personal frameworks, commercial forecasts, or rhetorical scenarios?",
      "What equity, board, product, data, and decision rights does Gawdat hold in Flight Story engagements and Emma?",
      "What privacy, clinical-safety, crisis-response, bias, efficacy, age, and accountability controls govern Emma's relationship and coaching features?",
      "Which parts of the public platform could continue with comparable authority, trust, and demand without Gawdat's voice and former-Google credential?",
    ],
    payoff: "Institutional credibility can help launch an owned public platform, but authority does not travel whole. Durable and trustworthy independence requires clear rights, evidence standards, conflict disclosure, governance, distributed expertise, and succession.",
    sources: [
      { id: "guardian-profile", label: "Independent profile of the Google career, bereavement, and happiness framework", href: "https://www.theguardian.com/technology/2017/apr/30/google-mo-gawdat-solve-for-happy-interview", publisher: "The Guardian", published: "2017-04-30", kind: "independent" },
      { id: "gawdat-site", label: "Current first-person career, books, podcast, and venture account", href: "https://www.mogawdat.com/", publisher: "Mo Gawdat", published: "Current record", kind: "primary" },
      { id: "ai-for-good", label: "Institutional biography documenting former X role and public platform", href: "https://aiforgood.itu.int/speaker/mo-gawdat/", publisher: "International Telecommunication Union", published: "Current record", kind: "institutional" },
      { id: "macmillan-solve", label: "Publisher record for Solve for Happy and its stated framework", href: "https://www.panmacmillan.com/authors/mo-gawdat/solve-for-happy/9781501157592", publisher: "Pan Macmillan", published: "2017", kind: "institutional" },
      { id: "macmillan-scary", label: "Publisher record for Scary Smart and its AI thesis", href: "https://www.panmacmillan.com/authors/mo-gawdat/scary-smart/9781529077650", publisher: "Pan Macmillan", published: "2021", kind: "institutional" },
      { id: "apple-podcast", label: "Platform record for Slo Mo ownership, run, and episode count", href: "https://podcasts.apple.com/us/podcast/slo-mo-a-podcast-with-mo-gawdat/id1508914142", publisher: "Apple Podcasts", published: "2020–2024", kind: "institutional" },
      { id: "tech-eu-flightstory", label: "Independent report on Flight Story's chief AI officer appointment", href: "https://tech.eu/2023/05/31/ex-google-x-mo-gawdat-joins-flight-story-as-lead-on-how-ai-will-impact-the-digital-marketing-firm/", publisher: "Tech.eu", published: "2023-06-01", kind: "independent" },
      { id: "businesscloud-flightstory", label: "Independent corroboration of the Flight Story appointment", href: "https://businesscloud.co.uk/news/former-google-x-chief-to-head-up-ai-at-flight-story/", publisher: "BusinessCloud", published: "2023-06-01", kind: "independent" },
      { id: "emma-site", label: "Current company claims, founder role, and therapist-backed positioning", href: "https://emma.love/", publisher: "Emma", published: "Current record", kind: "primary" },
      { id: "emma-announcement", label: "First-person introduction of the Emma product", href: "https://www.linkedin.com/posts/mogawdat_ive-been-talking-for-several-years-about-activity-7361688826286686209-OOvp", publisher: "Mo Gawdat / LinkedIn", published: "2025", kind: "primary" },
      { id: "sharjah-emma", label: "Independent event report on Emma's stated boundaries and accountability", href: "https://sharjah24.ae/en/Articles/2026/02/01/AL018", publisher: "Sharjah 24", published: "2026-02-01", kind: "independent" },
      { id: "businessinsider-ai-jobs", label: "Independent report contrasting Gawdat's job-loss prediction with other industry views", href: "https://www.businessinsider.com/ex-google-exec-predicts-end-of-white-collar-jobs-starting-in-2027-2025-8", publisher: "Business Insider", published: "2025-08-04", kind: "independent" },
    ],
  },
};

const CASE_MILESTONES: Record<string, { date: string; event: string }> = {
  "suzie-reider": { date: "2006–2024", event: "Reider moved from CNET into a 17-year Google career spanning YouTube and Waze, then joined Lyft to lead Lyft Media and Lyft Business." },
  "kenny-gold": { date: "June 2, 2026", event: "Edelman appointed Gold its first global chief creator officer after he built Deloitte Digital’s social-and-creator practice." },
  "steven-bartlett": { date: "2017–present", event: "Bartlett developed The Diary of a CEO from a founder-hosted podcast into the center of a wider media and venture system." },
  "ashley-rudder": { date: "2023–2024", event: "Rudder held first-of-kind chief creator officer roles at Whalar and Deutsch New York." },
  "gordon-glenister": { date: "2010s–2020s", event: "Glenister moved from trade-association leadership into influencer-marketing field building, consulting, publishing, and convening." },
  "claire-zau": { date: "2026", event: "Lightspeed recruited Zau into a dual seed-investing and new-media role after she built an independent technology audience." },
  "brad-keywell": { date: "2000s–2020s", event: "Keywell co-founded technology companies, built Lightbank and Chicago Ideas, taught entrepreneurship, and developed a public art practice." },
  "klitos-teklos": { date: "2010s–2020s", event: "Teklos organized fashion and luxury creative-direction work through an independent studio and embedded brand residencies." },
  "charlotte-tansill": { date: "2026", event: "Publicis Creative US placed social, creator, and earned media under Tansill’s leadership after agency strategy roles." },
  "mo-gawdat": { date: "2007–2020s", event: "Gawdat moved from Google and Google X leadership into books, podcasting, speaking, happiness advocacy, and public AI commentary." },
  "peter-diamandis": { date: "1990s–2020s", event: "Diamandis repeatedly organized prizes, space ventures, education, and future-oriented entrepreneurship through entities including XPRIZE." },
  "noubar-afeyan": { date: "2000–2020s", event: "Afeyan developed Flagship Pioneering’s venture-creation model, which formed companies including Moderna." },
  "nadir-godrej": { date: "1977–2026", event: "Godrej combined nearly five decades in the family-controlled Godrej group with a public practice in poetry, science, and speaking." },
  "mrbeast": { date: "2012–2026", event: "Jimmy Donaldson expanded YouTube production into consumer products, philanthropy, licensing, and Amazon’s Beast Games." },
  "emma-chamberlain": { date: "2017–2025", event: "Chamberlain expanded from YouTube into podcasting, fashion partnerships, packaged coffee, retail distribution, and a physical café." },
  "huda-kattan": { date: "2010–2020s", event: "Kattan moved from beauty blogging and makeup artistry into a global product company built with family members." },
  "marques-brownlee": { date: "2008–2020s", event: "Brownlee grew a student technology-review channel into a staffed media operation spanning video, podcasts, merchandise, and collaborations." },
  "pieter-levels": { date: "2014–2020s", event: "Levels publicly built and operated internet products including Nomad List and Remote OK through a deliberately small independent model." },
  "jack-conte": { date: "2013", event: "Conte and Sam Yam founded Patreon after Conte’s experience trying to finance music through online audiences." },
  "colin-samir": { date: "2011–2024", event: "Colin Rosenblum and Samir Chaudry built and sold a lacrosse channel, then created a creator-economy publication, show, podcast, and course business." },
  "alex-cooper": { date: "2018–2024", event: "Cooper carried Call Her Daddy from Barstool to Spotify and SiriusXM while building the Unwell network." },
  "codie-sanchez": { date: "2020–2026", event: "Sanchez turned a small-business acquisition thesis into Contrarian Thinking’s media, education, community, and investment ecosystem." },
  "gary-vaynerchuk": { date: "2006–2020s", event: "Vaynerchuk used online video to expand a family wine business, then built agencies, media, investing, conferences, books, and IP ventures." },
  "alexandr-wang": { date: "2016–2026", event: "Wang co-founded Scale AI and later entered Meta’s AI leadership structure alongside a major Meta investment in Scale." },
  "mustafa-suleyman": { date: "2010–2024", event: "Suleyman moved from co-founding DeepMind through Google, Inflection AI, and leadership of Microsoft’s newly organized consumer-AI division." },
  "cathy-hackl": { date: "2010s–2020s", event: "Hackl built a portfolio across immersive technology, spatial computing, gaming, consulting, writing, and executive roles." },
  "jane-gilbert": { date: "2021", event: "Miami-Dade appointed Gilbert its first chief heat officer, giving extreme-heat coordination a named office and cross-sector mandate." },
  "darren-murph": { date: "2019–2023", event: "GitLab formalized Murph’s remote-work expertise as Head of Remote and distributed it through a public operating handbook." },
  "linda-fisher": { date: "2004", event: "DuPont appointed Fisher its first chief sustainability officer after senior environmental-law and EPA roles." },
  "jony-ive": { date: "1992–2019", event: "Ive’s Apple design career culminated in the formation of independent studio LoveFrom, with Apple announced as a client." },
  "astro-teller": { date: "2010–2020s", event: "Teller led Alphabet’s X moonshot factory under the title Captain of Moonshots, institutionalizing staged experimentation and project graduation." },
  "marc-lore": { date: "2016–2021", event: "Walmart acquired Jet.com and placed founder Marc Lore over U.S. e-commerce before he returned to independent ventures." },
  "shonda-rhimes": { date: "2005–2021", event: "Rhimes built Shondaland around television authorship, then moved its primary development relationship from ABC to Netflix." },
  "simon-cook": { date: "2000s–2020s", event: "Cook advanced through Cannes Lions awards and operations leadership to become CEO of LIONS." },
  "marc-pritchard": { date: "1982–2020s", event: "Pritchard’s long P&G career culminated in chief brand leadership and public interventions in advertising standards, media quality, and representation." },
  "reid-hoffman": { date: "2003–2020s", event: "Hoffman co-founded LinkedIn, then used the resulting capital and network across venture investing, publishing, podcasting, and political activity." },
  "fei-fei-li": { date: "2009–2024", event: "Li’s work moved through ImageNet, Stanford, Google Cloud AI, Stanford HAI, public policy, and co-founding World Labs." },
  "neri-oxman": { date: "2010–2020s", event: "Oxman developed material ecology at MIT and later moved the authored research identity into the private company OXMAN." },
  "brian-may": { date: "1970s–2007", event: "May paused doctoral astrophysics as Queen became successful, then returned decades later and completed the PhD." },
};

function narrativeResearch(slug: string): CaseResearchRecord | undefined {
  const narrative = CASE_NARRATIVES[slug];
  const milestone = CASE_MILESTONES[slug];
  if (!narrative || !milestone) return undefined;
  const sources = narrative.sources.map((source, index) => ({
    id: "source-" + (index + 1),
    label: source.label,
    href: source.href,
    publisher: source.label.split(":")[0],
    published: "See linked record",
    kind: source.independent ? "independent" as const : "institutional" as const,
  }));
  const sourceIds = sources.map((source) => source.id);
  return {
    documentationLevel: "provisional",
    reviewed: "2026-07-27",
    chronology: [
      { ...milestone, sourceIds },
      { date: "Structural turn", event: narrative.structuralTurn, sourceIds },
    ],
    interpretation: narrative.whyItMatters,
    complication: [
      "The linked public record documents visible roles and announcements; it does not by itself establish private equity, contracts, decision rights, compensation, audience ownership, or causal impact.",
      "Career outcomes belong partly to teams, employers, partners, platforms, capital providers, and inherited institutional infrastructure; the record does not permit sole-credit attribution.",
      ...narrative.unresolved.slice(0, 1).map((item) => "Open complication: " + item),
    ],
