import type { InstrumentId } from "./research-governance";

export type ReviewDisposition = "retain" | "revise" | "split" | "defer";
export type ReviewRisk = "low" | "moderate" | "high";

export interface ItemContentReview {
  instrument: InstrumentId;
  itemId: string;
  disposition: ReviewDisposition;
  risk: ReviewRisk;
  constructAlignment: string;
  finding: string;
  revisionRule: string;
}

export const ITEM_CONTENT_REVIEW: ItemContentReview[] = [
  { instrument:"ownership",itemId:"A1",disposition:"revise",risk:"moderate",constructAlignment:"direct audience access",finding:"The highest anchor says more than 30% while also saying most, which is mathematically inconsistent.",revisionRule:"Remove 'most' and retain the explicit percentage band." },
  { instrument:"ownership",itemId:"A2",disposition:"split",risk:"high",constructAlignment:"audience continuity",finding:"Combines retained reach, relationship continuity, and estimated rebuilding time in one response.",revisionRule:"Measure reachable share after platform loss separately from expected recovery time." },
  { instrument:"ownership",itemId:"A3",disposition:"split",risk:"high",constructAlignment:"channel dependence",finding:"Asks simultaneously where reach and revenue come from; respondents can have opposite answers.",revisionRule:"Separate audience discovery source from revenue-source dependence." },
  { instrument:"ownership",itemId:"A4",disposition:"split",risk:"moderate",constructAlignment:"first-party data capability",finding:"Combines data collection, richness, and active operational use.",revisionRule:"Separate capture coverage from use maturity; add privacy/consent governance in the latter." },
  { instrument:"ownership",itemId:"R1",disposition:"revise",risk:"moderate",constructAlignment:"copyright retention",finding:"Anchors mix assignment, exclusivity, scope, negotiation, and default practice.",revisionRule:"Ask only about the usual copyright disposition; move exclusivity and negotiation to separate evidence fields." },
  { instrument:"ownership",itemId:"R2",disposition:"revise",risk:"moderate",constructAlignment:"usage-duration control",finding:"Assumes shorter use is always better and does not distinguish paid, territorial, media, or renewal terms.",revisionRule:"Measure whether duration is explicit and priced, then record duration separately." },
  { instrument:"ownership",itemId:"R3",disposition:"split",risk:"high",constructAlignment:"catalogue ownership and exploitation",finding:"Combines tracking, ownership, reuse, licensing, and income.",revisionRule:"Separate catalogue control/records from reuse or licensing activity." },
  { instrument:"ownership",itemId:"R4",disposition:"split",risk:"moderate",constructAlignment:"paid secondary usage",finding:"Usage rights and whitelisting are distinct practices, and applicability varies by deal.",revisionRule:"Ask each practice separately with a not-applicable path and a defined time window." },
  { instrument:"ownership",itemId:"V1",disposition:"revise",risk:"moderate",constructAlignment:"income diversification",finding:"'Meaningful' is undefined and stream counts do not measure concentration or quality.",revisionRule:"Define a stream by minimum share or recurring receipt within a stated period." },
  { instrument:"ownership",itemId:"V2",disposition:"revise",risk:"moderate",constructAlignment:"controlled-income share",finding:"The examples combine asset ownership, payment mechanism, and contract type.",revisionRule:"Define controlled income operationally and retain percentage bands with a stated period." },
  { instrument:"ownership",itemId:"V3",disposition:"retain",risk:"low",constructAlignment:"recurring-income share",finding:"Substantively aligned, but the reference period and percentage boundaries should be explicit.",revisionRule:"Add a twelve-month reference period and non-overlapping percentage bands." },
  { instrument:"ownership",itemId:"V4",disposition:"split",risk:"moderate",constructAlignment:"income concentration",finding:"A client and a platform are different dependency types.",revisionRule:"Measure largest payer concentration and platform-mediated concentration separately." },
  { instrument:"ownership",itemId:"I1",disposition:"split",risk:"high",constructAlignment:"brand-identifier protection",finding:"Mixes platform handles, domains, application status, registrations, class coverage, and monitoring; complexity is treated as universally superior.",revisionRule:"Separate identifier control, registration status, territorial/class scope, and monitoring." },
  { instrument:"ownership",itemId:"I2",disposition:"split",risk:"high",constructAlignment:"contractual likeness control",finding:"Combines likeness, voice, frequency of clauses, licensing control, and pricing.",revisionRule:"Measure clause coverage separately from scope and compensation." },
  { instrument:"ownership",itemId:"I3",disposition:"split",risk:"high",constructAlignment:"synthetic-use control",finding:"AI training, cloning, synthetic performance, and contract frequency are distinct legal uses.",revisionRule:"Use a checklist for prohibited, permitted, approval, compensation, duration, and training terms." },
  { instrument:"ownership",itemId:"I4",disposition:"split",risk:"high",constructAlignment:"detection and enforcement readiness",finding:"Detection, knowledge, process, resources, and enforcement capacity are combined.",revisionRule:"Separate monitoring from response readiness and successful enforcement." },
  { instrument:"ownership",itemId:"B1",disposition:"revise",risk:"high",constructAlignment:"business formalization",finding:"The scale treats more entities and formal governance as universally better despite jurisdiction, stage, cost, and business need.",revisionRule:"Measure fit-for-purpose separation, records, and governance rather than entity complexity." },
  { instrument:"ownership",itemId:"B2",disposition:"split",risk:"moderate",constructAlignment:"contracting infrastructure",finding:"Combines contract use, ownership of templates, consistency, completeness, and lawyer review.",revisionRule:"Separate contract coverage from template governance and review status." },
  { instrument:"ownership",itemId:"B3",disposition:"revise",risk:"high",constructAlignment:"delegation and operational capacity",finding:"Headcount is treated as maturity, disadvantaging efficient solo businesses and respondents constrained by resources.",revisionRule:"Measure documented delegation or automation of necessary functions, including valid solo models." },
  { instrument:"ownership",itemId:"B4",disposition:"retain",risk:"moderate",constructAlignment:"continuity",finding:"Aligned but hypothetical and affected by business model, caregiving, disability, stage, and intentional seasonality.",revisionRule:"Retain as a scenario item with a specified thirty-day period and contextual non-scored fields." },

  { instrument:"portfolio_professional",itemId:"C1",disposition:"revise",risk:"high",constructAlignment:"proactive capability building",finding:"Work beyond assigned responsibilities is not equivalent to capability and rewards unpaid overwork or discretionary privilege.",revisionRule:"Measure self-initiated capability creation within or beyond role, without making excess workload the high anchor." },
  { instrument:"portfolio_professional",itemId:"C2",disposition:"retain",risk:"low",constructAlignment:"reusable knowledge artifacts",finding:"Strong alignment; 'artifact' and adoption window require examples and a reference period.",revisionRule:"Add inclusive examples and a twelve-month period." },
  { instrument:"portfolio_professional",itemId:"C3",disposition:"revise",risk:"high",constructAlignment:"capability legibility",finding:"External visibility is treated as superior to consequential internal expertise and is role-dependent.",revisionRule:"Measure evidence and legibility across the relevant audience, whether internal, external, or both." },
  { instrument:"portfolio_professional",itemId:"C4",disposition:"revise",risk:"high",constructAlignment:"capability portability",finding:"'Mine' may imply legal IP ownership even when methods or artifacts belong to an employer.",revisionRule:"Ask what knowledge and capability remains portable subject to contractual and legal restrictions." },
  { instrument:"portfolio_professional",itemId:"V1",disposition:"retain",risk:"moderate",constructAlignment:"organizational adoption",finding:"Aligned but team boundaries and adoption evidence are undefined.",revisionRule:"Specify a period and distinguish informal use from documented standard practice." },
  { instrument:"portfolio_professional",itemId:"V2",disposition:"retain",risk:"low",constructAlignment:"transferability",finding:"Aligned; independence and handoff quality need operational anchors.",revisionRule:"Define independent operation and the observation period." },
  { instrument:"portfolio_professional",itemId:"V3",disposition:"defer",risk:"moderate",constructAlignment:"continuity",finding:"Substantially overlaps V2 and may reflect staffing or organizational support more than respondent-created value.",revisionRule:"Test redundancy with V2; retain only if response-process and factor evidence show distinct continuity information." },
  { instrument:"portfolio_professional",itemId:"V4",disposition:"revise",risk:"moderate",constructAlignment:"traceable organizational value",finding:"Access to metrics and attribution varies by seniority and organization; causal contribution is implied.",revisionRule:"Ask about documented contribution and evidence type without claiming sole attribution." },
  { instrument:"portfolio_professional",itemId:"M1",disposition:"revise",risk:"high",constructAlignment:"role shaping",finding:"Role creation is confounded by seniority, labor market power, organization size, and hiring practices.",revisionRule:"Measure degree of negotiated role shaping and separately collect structural opportunity." },
  { instrument:"portfolio_professional",itemId:"M2",disposition:"retain",risk:"low",constructAlignment:"work autonomy",finding:"Directly aligned but requires a period and distinction between task, method, schedule, and priority autonomy.",revisionRule:"Clarify the autonomy domain or use a short multi-item subscale." },
  { instrument:"portfolio_professional",itemId:"M3",disposition:"defer",risk:"moderate",constructAlignment:"innovation latitude",finding:"Overlaps M2 and combines available time, permission, psychological safety, and personal initiative.",revisionRule:"Test as a distinct innovation-latitude item after cognitive interviews." },
  { instrument:"portfolio_professional",itemId:"M4",disposition:"revise",risk:"high",constructAlignment:"organizational receptivity",finding:"Counterfactual likelihood is unverifiable and reflects organizational power more than individual mandate.",revisionRule:"Ask whether a proposal was made in a stated period and what observable decision followed." },
  { instrument:"portfolio_professional",itemId:"A1",disposition:"revise",risk:"moderate",constructAlignment:"domain referral",finding:"The top anchor claims singular recognized authority without a defined reference group.",revisionRule:"Use observable referral frequency and specify team, organization, field, or public audience." },
  { instrument:"portfolio_professional",itemId:"A2",disposition:"split",risk:"high",constructAlignment:"external recognition",finding:"Awards, speaking, press, and peer recognition are distinct and unequally accessible signals.",revisionRule:"Use a multi-select evidence inventory and do not sum unlike signals without validation." },
  { instrument:"portfolio_professional",itemId:"A3",disposition:"split",risk:"high",constructAlignment:"professional audience access",finding:"Combines network size, followers, community, direct reach, and ownership.",revisionRule:"Separate audience scale from direct/portable access and relationship depth." },
  { instrument:"portfolio_professional",itemId:"A4",disposition:"revise",risk:"high",constructAlignment:"reputation-linked opportunity",finding:"Combines doors, roles, and deals and asks respondents to causally attribute opportunity to reputation.",revisionRule:"Ask about observable inbound opportunities and how the source was known." },
  { instrument:"portfolio_professional",itemId:"T1",disposition:"retain",risk:"moderate",constructAlignment:"portfolio thematic coherence",finding:"Aligned but one thesis may not suit plural, exploratory, or interdisciplinary portfolios.",revisionRule:"Permit a small set of articulated through-lines; do not make singularity inherently superior." },
  { instrument:"portfolio_professional",itemId:"T2",disposition:"revise",risk:"moderate",constructAlignment:"portfolio compounding",finding:"'Makes the next stronger' is broad and can refer to skills, audience, evidence, capital, or access.",revisionRule:"Name the resources that may carry forward and use observable examples." },
  { instrument:"portfolio_professional",itemId:"T3",disposition:"revise",risk:"high",constructAlignment:"external legibility",finding:"A one-sentence description and memorability reward branding simplicity and may penalize complex or marginalized careers.",revisionRule:"Measure whether intended audiences can accurately describe the portfolio's through-lines." },
  { instrument:"portfolio_professional",itemId:"T4",disposition:"split",risk:"high",constructAlignment:"future direction",finding:"A venture, institution, and category are different outcomes; 'already real' lacks an observable anchor.",revisionRule:"Separate intended direction, commitment, current activity, and evidence of progress." },
];

export const REVIEW_SUMMARY = ITEM_CONTENT_REVIEW.reduce(
  (summary, item) => {
    summary[item.disposition] += 1;
    summary[item.risk] += 1;
    return summary;
  },
  { retain: 0, revise: 0, split: 0, defer: 0, low: 0, moderate: 0, high: 0 },
);

