-- Gary Vaynerchuk public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, resolve private ownership, or mark saturation complete.

INSERT INTO "ObservatoryCase"
("id","slug","displayName","caseType","primaryField","jurisdiction","headline","summary","inclusionRationale","roleBuiltFlag","verificationStatus","evidenceCoverage","consentStatus","publicStatus","createdAt","updatedAt")
VALUES
('obs_case_gary_vaynerchuk','gary-vaynerchuk','Gary Vaynerchuk','creator','Marketing, media and entrepreneurship','United States',
'Founder-centered executive and media system spanning a private agency holding company, owned distribution, acquired media assets and separately structured ventures.',
'A public-evidence case separating GaryVee narrative centrality from legal ownership, co-founder contributions, operating leadership, acquired assets, outside capital, exits and project-specific IP.',
'Selected to replace the causal claim that VaynerX was built around GaryVee with a bounded, entity-specific architecture.',
true,'in_review',0.86,'public_evidence','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO UPDATE SET "headline"=EXCLUDED."headline","summary"=EXCLUDED."summary","inclusionRationale"=EXCLUDED."inclusionRationale","roleBuiltFlag"=true,"verificationStatus"='in_review',"evidenceCoverage"=0.86,"updatedAt"=CURRENT_TIMESTAMP;

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_gv_s01','https://vaynerx.com/','VaynerX current portfolio','VaynerX','company_record',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s02','https://garyvaynerchuk.com/press/','Gary Vaynerchuk press kit','Gary Vaynerchuk','subject_record',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s03','https://garyvaynerchuk.com/biography/','Gary Vaynerchuk biography','Gary Vaynerchuk','subject_record',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s04','https://www.nytimes.com/2013/11/03/business/riding-the-hashtag-in-social-media-marketing.html','Riding the Hashtag in Social Media Marketing','The New York Times','independent_reporting','2013-11-02T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s05','https://thehustle.co/09252020-vaynerchuk-vaynermedia','AJ Vaynerchuk interview on VaynerMedia and VaynerSports','The Hustle','cofounder_interview','2024-03-21T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s06','https://tamaragroup.com/','Tamara Group about and leadership','Tamara Group','company_record',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s07','https://www.prnewswire.com/news-releases/vaynerx-launches-tamara-group-the-attention-media-and-relevance-agency-302754653.html','VaynerX launches Tamara Group','VaynerX / PR Newswire','company_release','2026-04-27T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s08','https://www.mediapost.com/publications/article/412378/vaynerx-unveils-rebranded-social-first-agency-chuk.html','VaynerX unveils rebranded ChukMedia','MediaPost','trade_reporting','2026-01-28T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s09','https://finance.yahoo.com/news/gmg-acquires-coveteur-marking-first-145611265.html','Gallery Media Group acquires Coveteur','Adweek / Yahoo Finance','trade_reporting','2025-05-01T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s10','https://www.americanexpress.com/en-us/newsroom/articles/travel-and-dining/new-resy-benefits-are-added-to-american-express-u-s--consumer-an.html','American Express Resy benefits and acquisition record','American Express','acquirer_record','2025-09-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s11','https://ir.cbrands.com/news-events/press-releases/detail/44/constellation-brands-acquires-digitally-native-wine-brand-empathy-wines','Constellation Brands acquires Empathy Wines','Constellation Brands','acquirer_release','2020-07-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s12','https://ir.cbrands.com/sec-filings/all-sec-filings/content/0000016918-22-000069/stz-20220228.htm','Constellation Brands 2022 Form 10-K','Constellation Brands / SEC','regulatory_filing','2022-04-21T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s13','https://veefriends.com/blog/veefriends-announces-global-events-division-to-expand-on-bespoke-experiences-access-and-utility-216d72d74bf2','VeeFriends announces global events division','VeeFriends','company_release','2022-10-25T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s14','https://veefriends.com/blog/veefriends-partners-with-macys-and-toys-r-us-for-official-figure-and-plush-collectibles-launch-34bd4e5dfbd0','VeeFriends Macy''s and Toys R Us partnership','VeeFriends','company_release','2022-10-04T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s15','https://www.foley.com/news/2022/08/foley-represents-gary-v-nft-project-veefriends-50m/','Foley represents VeeFriends in $50 million seed investment','Foley & Lardner','transaction_counsel_record','2022-08-03T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s16','https://veefriends.com/about/ip-trademark-guidelines','VeeFriends IP and trademark guidelines','VeeFriends','company_legal_terms',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s17','https://veefriends.com/terms-of-use/veefriends-nft-terms-of-sale-and-user-license','VeeFriends NFT terms of sale and user license','VeeFriends','company_legal_terms','2025-10-17T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_gv_s18','https://www.prnewswire.co.uk/news-releases/gary-vaynerchuk-releases-his-first-nft-collection-veefriends--870319949.html','Gary Vaynerchuk releases first VeeFriends collection','VeeFriends / PR Newswire','company_release','2021-05-05T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_gv_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'company_formation','Gary and AJ Vaynerchuk co-founded VaynerMedia in 2009.','institution_building','observed','unreviewed',NULL,'VaynerMedia was co-founded by Gary and AJ Vaynerchuk.','Do not singularize the founding.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'formal_roles','Gary is publicly identified as VaynerX chairman and VaynerMedia CEO.','formal_authority','observed','unreviewed',NULL,'Gary holds formal leadership roles across VaynerX and VaynerMedia.','Titles do not establish complete ownership or unilateral authority.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'portfolio_perimeter','VaynerX describes itself as a family of companies and lists multiple operating brands.','portfolio_architecture','observed','unreviewed',NULL,'VaynerX coordinates a portfolio of agency, media, production, speaking and marketing businesses.','Do not place every Gary-affiliated venture inside VaynerX.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'cofounder_operations','AJ served as VaynerMedia COO during early scaling and later led VaynerSports.','distributed_leadership','observed','unreviewed',NULL,'VaynerMedia''s growth involved material co-founder operating leadership.','Early growth is not solely attributable to Gary.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'acquired_media','Gallery Media Group includes acquired media properties and separate operating leadership.','resource_assembly','observed','unreviewed',NULL,'VaynerX''s media portfolio includes acquired assets and separate operating leadership.','Gary did not personally create every publication.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'portfolio_rebrand','The Sasha Group was rebranded as ChukMedia in 2026 under president Mark Rolland.','role_evolution','observed','unreviewed',NULL,'VaynerX''s portfolio changes through rebranding and executive appointments.','Do not present every portfolio company as a new Gary-created business.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'new_agency','Tamara Group launched in 2026 under Ryan Harwood and a named leadership team.','distributed_leadership','observed','unreviewed',NULL,'Gary''s founder story informs the portfolio while operating authority is distributed.','Naming does not prove personal ownership.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'resy_exit','Gary co-founded Resy with Ben Leventhal and Mike Montero; American Express acquired Resy in 2019.','venture_formation_and_exit','observed','unreviewed',NULL,'Resy was a co-founded venture that later exited to American Express.','Gary did not solely found, own or sell Resy.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'empathy_exit','Gary co-founded Empathy Wines with Jon Troutman and Nate Scherotter; Constellation acquired it in 2020.','venture_formation_and_exit','observed','unreviewed',NULL,'Empathy Wines was a three-founder company acquired by Constellation.','Gary did not solely own the company or receive all consideration.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'exit_assets','Constellation identified acquired goodwill, trademarks and inventory plus a performance earn-out.','control_rights','observed','unreviewed',NULL,'Empathy''s exit involved specified business assets and an earn-out.','Founder-by-founder proceeds and current interests are unresolved.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c11',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'veefriends_architecture','VeeFriends uses Gary-created characters through a separate company, staff, executives, partners and outside investment.','institution_building','observed','unreviewed',NULL,'Gary created the character concepts and leads a separately organized entertainment and IP company.','Do not treat every company asset and function as personally owned or performed.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c12',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'outside_capital','VeeFriends received a $50 million seed investment led by a16z crypto.','capital_structure','observed','unreviewed',NULL,'VeeFriends uses outside capital as well as founder-created IP.','Gary''s equity and investor governance terms are undisclosed.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c13',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'ip_boundary','VeeFriends retains underlying commercial IP rights while NFT holders generally receive limited personal noncommercial licenses.','control_rights','observed','unreviewed',NULL,'Token ownership is distinct from ownership of underlying VeeFriends IP.','NFT holders do not receive company equity or character copyrights under the general terms.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c14',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'owned_distribution','Gary''s personal media channels and executive content are recurrent distribution resources for affiliated businesses.','distribution_ownership','observed','unreviewed',NULL,'The GaryVee media system is a material promotional and audience resource.','Audience size does not prove sales causation, firm value or cross-company ownership.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c15',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'portfolio_drift','VaynerX''s public portfolio changed between older biographies and its 2026 website.','claim_restriction','observed','unreviewed',NULL,'Portfolio membership is time-specific and must be dated.','Old speaker biographies do not establish the current corporate perimeter.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c16',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'bounded_founder_architecture','VaynerX is founder-centered in leadership, narrative and distribution but institutionally distributed.','role_centered_architecture','interpretive','unreviewed',NULL,'VaynerX uses Gary''s leadership, reputation and distribution while operating through separate companies, executives and assets.','Prohibit sole-causation or personal-shell language.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_gv_c17',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'psychology_boundary','No reviewed source measures Gary Vaynerchuk''s psychological constructs.','claim_restriction','observed','unreviewed',NULL,'The case documents roles, rights, resources, relationships and outputs, not psychology.','Do not score hustle, empathy, ambition, narcissism or risk tolerance from persona.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_gv_c01','obs_claim_gv_c01','obs_src_gv_s03','supports',NULL,'2009 chronology','Subject record names both founders.',CURRENT_TIMESTAMP),
('obs_ev_gv_c02','obs_claim_gv_c02','obs_src_gv_s02','supports',NULL,'Current role biography','Formal-role evidence only.',CURRENT_TIMESTAMP),
('obs_ev_gv_c03','obs_claim_gv_c03','obs_src_gv_s01','supports',NULL,'Current company list','Public portfolio perimeter.',CURRENT_TIMESTAMP),
('obs_ev_gv_c04','obs_claim_gv_c04','obs_src_gv_s05','supports',NULL,'AJ interview biography','Co-founder operating contribution.',CURRENT_TIMESTAMP),
('obs_ev_gv_c05','obs_claim_gv_c05','obs_src_gv_s09','supports',NULL,'Coveteur acquisition','Acquisition and operating-leader evidence.',CURRENT_TIMESTAMP),
('obs_ev_gv_c06','obs_claim_gv_c06','obs_src_gv_s08','supports',NULL,'ChukMedia rebrand','Portfolio evolution.',CURRENT_TIMESTAMP),
('obs_ev_gv_c07','obs_claim_gv_c07','obs_src_gv_s06','supports',NULL,'Leadership page','Distributed operating authority.',CURRENT_TIMESTAMP),
('obs_ev_gv_c08a','obs_claim_gv_c08','obs_src_gv_s03','supports',NULL,'Resy founding chronology','Three co-founders.',CURRENT_TIMESTAMP),
('obs_ev_gv_c08b','obs_claim_gv_c08','obs_src_gv_s10','supports',NULL,'American Express acquisition record','Current ownership boundary.',CURRENT_TIMESTAMP),
('obs_ev_gv_c09','obs_claim_gv_c09','obs_src_gv_s11','supports',NULL,'Acquirer announcement','Three founders and acquisition.',CURRENT_TIMESTAMP),
('obs_ev_gv_c10','obs_claim_gv_c10','obs_src_gv_s12','supports',NULL,'Empathy acquisition note','Asset and earn-out boundary.',CURRENT_TIMESTAMP),
('obs_ev_gv_c11','obs_claim_gv_c11','obs_src_gv_s13','supports',NULL,'Company and leadership description','Distributed VeeFriends operations.',CURRENT_TIMESTAMP),
('obs_ev_gv_c12','obs_claim_gv_c12','obs_src_gv_s15','supports',NULL,'Transaction counsel announcement','Outside capital.',CURRENT_TIMESTAMP),
('obs_ev_gv_c13a','obs_claim_gv_c13','obs_src_gv_s16','supports',NULL,'IP FAQ','Limited holder license.',CURRENT_TIMESTAMP),
('obs_ev_gv_c13b','obs_claim_gv_c13','obs_src_gv_s17','supports',NULL,'NFT terms section 4','Company rights and token boundary.',CURRENT_TIMESTAMP),
('obs_ev_gv_c14','obs_claim_gv_c14','obs_src_gv_s02','qualifies',NULL,'Media-system biography','Reach observed; causation not measured.',CURRENT_TIMESTAMP),
('obs_ev_gv_c15','obs_claim_gv_c15','obs_src_gv_s01','supports',NULL,'2026 current portfolio','Controls present public perimeter.',CURRENT_TIMESTAMP),
('obs_ev_gv_c16','obs_claim_gv_c16','obs_src_gv_s01','qualifies',NULL,'Portfolio architecture','Bounded synthesis only.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_gv_aj',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'person','AJ Vaynerchuk','brother_cofounder_and_former_coo','2009-01-01T00:00:00Z',NULL,'unreviewed','draft','obs_src_gv_s05',NULL,'Current equity undisclosed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_gv_vm',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'organization','VaynerMedia','cofounder_and_ceo','2009-01-01T00:00:00Z',NULL,'unreviewed','draft','obs_src_gv_s03',NULL,'Private ownership undisclosed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_gv_vx',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'organization','VaynerX','chairman',NULL,NULL,'unreviewed','draft','obs_src_gv_s02',NULL,'Holding-company perimeter incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_gv_harwood',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'person','Ryan Harwood','portfolio_company_ceo',NULL,NULL,'unreviewed','draft','obs_src_gv_s06',NULL,'Gallery Media Group and Tamara leadership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_gv_rolland',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'person','Mark Rolland','chukmedia_president','2026-01-28T00:00:00Z',NULL,'unreviewed','draft','obs_src_gv_s08',NULL,'Distributed operating authority',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_gv_veefriends',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'organization','Vee Friends, LLC','founder_creator_and_executive','2021-05-05T00:00:00Z',NULL,'unreviewed','draft','obs_src_gv_s17',NULL,'Company and personal IP allocation incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_gv_a16z',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'organization','a16z crypto','veefriends_seed_investor','2022-07-29T00:00:00Z',NULL,'unreviewed','draft','obs_src_gv_s15',NULL,'Governance terms undisclosed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_gv_resy',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'organization','Resy','cofounder_former_interest','2014-01-01T00:00:00Z','2019-05-15T00:00:00Z','unreviewed','draft','obs_src_gv_s10',NULL,'Acquired by American Express',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_gv_empathy',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'organization','Empathy Wines','cofounder_former_interest','2019-01-01T00:00:00Z','2020-06-30T00:00:00Z','unreviewed','draft','obs_src_gv_s11',NULL,'Acquired by Constellation; proceeds undisclosed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_gv_amex',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'organization','American Express','resy_acquirer','2019-05-15T00:00:00Z',NULL,'unreviewed','draft','obs_src_gv_s10',NULL,'Acquirer relationship',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_gv_constellation',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'organization','Constellation Brands','empathy_wines_acquirer','2020-06-30T00:00:00Z',NULL,'unreviewed','draft','obs_src_gv_s12',NULL,'Acquired assets and earn-out',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_gv_vm',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'company_formation','Gary and AJ co-found VaynerMedia','Co-founded agency; private ownership undisclosed.','2009-01-01T00:00:00Z','year','unreviewed','draft','obs_src_gv_s03',NULL,'Year precision',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_gv_resy',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'venture_formation','Resy co-founded','With Ben Leventhal and Mike Montero.','2014-01-01T00:00:00Z','year','unreviewed','draft','obs_src_gv_s03',NULL,'Year precision',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_gv_resy_exit',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'acquisition','American Express acquires Resy','Individual proceeds undisclosed.','2019-05-15T00:00:00Z','day','unreviewed','draft','obs_src_gv_s10',NULL,'Announcement date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_gv_empathy_exit',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'acquisition','Constellation acquires Empathy Wines','Three-founder company; acquired assets and earn-out.','2020-06-30T00:00:00Z','month','unreviewed','draft','obs_src_gv_s12',NULL,'Fiscal filing precision',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_gv_vf',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'company_formation','VeeFriends launches','NFT-linked character and event project.','2021-05-05T00:00:00Z','day','unreviewed','draft','obs_src_gv_s18',NULL,'Release date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_gv_vf_seed',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'financing','VeeFriends seed investment','Foley reports $50 million investment led by a16z crypto.','2022-08-03T00:00:00Z','day','unreviewed','draft','obs_src_gv_s15',NULL,'Counsel announcement date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_gv_chuk',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'portfolio_rebrand','The Sasha Group becomes ChukMedia','Rebranded agency under Mark Rolland.','2026-01-28T00:00:00Z','day','unreviewed','draft','obs_src_gv_s08',NULL,'Report date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_gv_tamara',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'company_launch','VaynerX launches Tamara Group','Agency led by Ryan Harwood and named leadership.','2026-04-27T00:00:00Z','day','unreviewed','draft','obs_src_gv_s07',NULL,'Announcement date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_gary_vaynerchuk_100','gary-vaynerchuk-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'1.0.0','research/observatory/dossiers/gary-vaynerchuk-1.0.0.md','pending-runtime-content-hash',
'{"claimIds":["obs_claim_gv_c01","obs_claim_gv_c02","obs_claim_gv_c03","obs_claim_gv_c04","obs_claim_gv_c05","obs_claim_gv_c06","obs_claim_gv_c07","obs_claim_gv_c08","obs_claim_gv_c09","obs_claim_gv_c10","obs_claim_gv_c11","obs_claim_gv_c12","obs_claim_gv_c13","obs_claim_gv_c14","obs_claim_gv_c15"],"relationshipIds":["obs_rel_gv_aj","obs_rel_gv_vm","obs_rel_gv_vx","obs_rel_gv_harwood","obs_rel_gv_rolland","obs_rel_gv_veefriends","obs_rel_gv_a16z","obs_rel_gv_resy","obs_rel_gv_empathy","obs_rel_gv_amex","obs_rel_gv_constellation"],"eventIds":["obs_event_gv_vm","obs_event_gv_resy","obs_event_gv_resy_exit","obs_event_gv_empathy_exit","obs_event_gv_vf","obs_event_gv_vf_seed","obs_event_gv_chuk","obs_event_gv_tamara"],"observationIds":[],"excludedInterpretiveClaimIds":["obs_claim_gv_c16"],"methodBoundaryClaimIds":["obs_claim_gv_c17"],"limitations":["saturation_decision_not_yet_recorded","two_no_new_material_evidence_passes_absent","founder_centered_not_sole_causal","vaynermedia_cofounded_with_aj","vaynerx_private_cap_table_unavailable","current_portfolio_differs_from_old_biographies","adjacent_ventures_not_automatically_vaynerx","resy_and_empathy_multi_founder_exits","individual_exit_proceeds_unverified","veefriends_outside_capital","token_ownership_not_underlying_ip","personal_audience_conversion_unmeasured","psychological_attributes_unmeasured"]}'::jsonb,
0.86,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_gary_vaynerchuk_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='gary-vaynerchuk'),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_gary_vaynerchuk_100',
'{"packageId":"gary-vaynerchuk-1.0.0","sourcesAdded":18,"claimsAdded":17,"claimsInPublicationManifest":15,"relationshipsAdded":11,"eventsAdded":8,"publication":"draft","saturation":"incomplete"}'::jsonb,
'Draft package replaces a sole-founder causal story with entity-specific evidence for co-founders, current portfolio, acquired assets, distributed leadership, outside capital, exits, token and IP rights, and private ownership gaps.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
