-- Kunal Shah public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='CRED founder and former CEO appointed to lead WhatsApp inside Meta.',
    "summary"='A founder-transition case separating company formation, former management and board roles, continuing reported shareholding, delegated platform leadership, institutional ownership and transaction economics.',
    "inclusionRationale"='Tests whether a founder’s transition into global platform leadership can be modeled without conflating founder status, equity, governance, employment, valuation, causality or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.82,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='kunal-shah';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_ks10_cred','https://newsroom.cred.club/cred-to-raise-8-550-crore-us-900m-from-meta/','CRED to raise ₹8,550 crore from Meta','CRED','primary_company_announcement','2026-06-22T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ks10_reuterslead','https://www.reuters.com/business/metas-whatsapp-be-led-by-indian-startup-founder-kunal-shah-2026-06-22/','Meta WhatsApp to be led by Kunal Shah','Reuters','independent_journalism','2026-06-22T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ks10_reuterstxn','https://www.reuters.com/world/india/indian-fintech-firm-cred-raise-900-million-meta-45-billion-valuation-2026-06-22/','Meta to invest in CRED and tap founder to lead WhatsApp','Reuters','independent_financial_journalism','2026-06-22T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ks10_mint','https://www.livemint.com/companies/people/kunal-shah-promoter-board-member-cred-whatsapp-meta-platforms-shareholding-11784023818673.html','Kunal Shah steps down as promoter and board member','Mint','filing_based_journalism','2026-07-16T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ks10_etbfsi','https://bfsi.economictimes.indiatimes.com/news/financial-services/kunal-shah-exits-cred-board-after-meta-appointment/132433359','Kunal Shah exits CRED board after Meta appointment','ETBFSI','trade_journalism','2026-07-16T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ks10_techcrunch','https://techcrunch.com/2026/06/22/whatsapp-gets-new-chief-as-meta-taps-indias-cred-founder-kunal-shah-and-invests-900m-in-startup/','WhatsApp gets new chief as Meta taps CRED founder','TechCrunch','technology_journalism','2026-06-22T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ks10_financials','https://inc42.com/company/cred/financials/','CRED financial breakdown','Inc42','data_journalism',NULL,'2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ks10_freecharge','https://www.foundingfuel.com/article/how-freecharge-found-its-mojo','How FreeCharge found its Mojo','Founding Fuel','contemporaneous_journalism','2015-04-13T00:00:00Z','2026-08-29T00:00:00Z',false,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_ks10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'role_history','Shah founded CRED in 2018 and served as CEO until June 2026.','role_history','observed','unreviewed',NULL,'Shah is CRED’s founder and former CEO.','Founder does not prove sole ownership, sole labor or continuing management authority.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ks10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'financing_boundary','CRED announced a Meta-led Series H of approximately ₹8,550 crore or US$900 million.','institutional_financing','attributed','unreviewed',NULL,'CRED announced the company financing.','The financing is not Shah’s personal payment, liquidity or wealth.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ks10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'management_transition','Shah left CRED’s operating CEO role and Miten Sampat became interim CEO.','role_transition','observed','unreviewed',NULL,'Shah is no longer operating CEO; Sampat became interim CEO.','Founder status does not preserve undisclosed management authority.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ks10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'role_appointment','Shah was appointed to lead WhatsApp globally, succeeding Will Cathcart.','delegated_authority','observed','unreviewed',NULL,'Shah leads WhatsApp within Meta.','The role does not confer ownership of WhatsApp or Meta.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ks10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'governance_transition','July reporting based on MCA filings says Shah resigned from CRED’s board and ceased promoter classification on June 22, 2026.','formal_governance','attributed','unreviewed',NULL,'Filing-based reports document a board and classification transition.','Promoter classification does not equal all beneficial ownership or control.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ks10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'ownership_boundary','Shah reportedly retained material CRED holdings personally and through QED Innovation Labs.','economic_interest','attributed','unreviewed',NULL,'Shah remains a reported CRED shareholder.','Exact current equity, votes, liquidity, transaction proceeds and control remain unverified.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ks10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'predecessor_venture','Shah co-founded FreeCharge with Sandeep Tandon before Snapdeal acquired it.','venture_history','observed','unreviewed',NULL,'FreeCharge was a co-founded predecessor venture.','No sole-founder, sole-builder or verified personal-payout claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ks10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'claim_restriction','No reviewed record establishes a complete current cap table, voting control, personal transaction economics, isolated causal performance or psychological measurements.','claim_restriction','observed','unreviewed',NULL,'Public evidence establishes roles and reported interests, not complete control, personal economics, causality or psychology.','Absence of public evidence is not proof that no private rights exist.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_ks10_c01','obs_claim_ks10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://newsroom.cred.club/cred-to-raise-8-550-crore-us-900m-from-meta/' LIMIT 1),'supports',NULL,'Founder and transition paragraphs','Primary company announcement; founder history and transition.',CURRENT_TIMESTAMP),
('obs_ev_ks10_c02','obs_claim_ks10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/world/india/indian-fintech-firm-cred-raise-900-million-meta-45-billion-valuation-2026-06-22/' LIMIT 1),'supports',NULL,'Transaction summary','Company financing and valuation kept separate from personal economics.',CURRENT_TIMESTAMP),
('obs_ev_ks10_c03','obs_claim_ks10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://newsroom.cred.club/cred-to-raise-8-550-crore-us-900m-from-meta/' LIMIT 1),'supports',NULL,'Leadership transition paragraphs','Miten Sampat interim appointment.',CURRENT_TIMESTAMP),
('obs_ev_ks10_c04','obs_claim_ks10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/metas-whatsapp-be-led-by-indian-startup-founder-kunal-shah-2026-06-22/' LIMIT 1),'supports',NULL,'Leadership succession report','Delegated Meta role.',CURRENT_TIMESTAMP),
('obs_ev_ks10_c05','obs_claim_ks10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.livemint.com/companies/people/kunal-shah-promoter-board-member-cred-whatsapp-meta-platforms-shareholding-11784023818673.html' LIMIT 1),'supports',NULL,'MCA filing report','Underlying filing not directly reviewed.',CURRENT_TIMESTAMP),
('obs_ev_ks10_c06','obs_claim_ks10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.livemint.com/companies/people/kunal-shah-promoter-board-member-cred-whatsapp-meta-platforms-shareholding-11784023818673.html' LIMIT 1),'supports',NULL,'Reported shareholding paragraphs','Percentage and aggregation remain attributed.',CURRENT_TIMESTAMP),
('obs_ev_ks10_c07','obs_claim_ks10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.foundingfuel.com/article/how-freecharge-found-its-mojo' LIMIT 1),'supports',NULL,'Acquisition and founder history','Co-founder boundary preserved.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_ks10_cred_founder',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'organization','CRED / Dreamplug Technologies','founder_former_ceo_former_director_reported_shareholder','2018-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://newsroom.cred.club/cred-to-raise-8-550-crore-us-900m-from-meta/' LIMIT 1),NULL,'Roles have different end dates; full cap table unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ks10_sampat',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'person','Miten Sampat','management_successor','2026-06-22T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://newsroom.cred.club/cred-to-raise-8-550-crore-us-900m-from-meta/' LIMIT 1),NULL,'Interim CEO; exact authority and permanence unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ks10_meta',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'organization','Meta','executive_employer','2026-06-22T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/metas-whatsapp-be-led-by-indian-startup-founder-kunal-shah-2026-06-22/' LIMIT 1),NULL,'Employment contract, compensation and decision rights unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ks10_whatsapp',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'organization','WhatsApp','global_leader','2026-06-22T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/metas-whatsapp-be-led-by-indian-startup-founder-kunal-shah-2026-06-22/' LIMIT 1),NULL,'Meta-owned platform; no personal ownership inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ks10_freecharge',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'organization','FreeCharge','cofounder_former_executive','2010-01-01T00:00:00Z','2015-04-08T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.foundingfuel.com/article/how-freecharge-found-its-mojo' LIMIT 1),NULL,'Co-founder and transaction economics incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ks10_tandon',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'person','Sandeep Tandon','freecharge_cofounder','2010-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.foundingfuel.com/article/how-freecharge-found-its-mojo' LIMIT 1),NULL,'Distributed founder attribution',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_ks10_freecharge',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'venture_history','FreeCharge co-founded','Shah and Sandeep Tandon co-founded FreeCharge.','2010-01-01T00:00:00Z','year_approximate','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.foundingfuel.com/article/how-freecharge-found-its-mojo' LIMIT 1),NULL,'Exact formation date not established here',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ks10_snapdeal',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'acquisition','Snapdeal acquires FreeCharge','Snapdeal announced acquisition of the co-founded company.','2015-04-08T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.foundingfuel.com/article/how-freecharge-found-its-mojo' LIMIT 1),NULL,'Personal proceeds not established',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ks10_cred',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'formation','CRED founded','Shah founded CRED.','2018-01-01T00:00:00Z','year_approximate','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://newsroom.cred.club/cred-to-raise-8-550-crore-us-900m-from-meta/' LIMIT 1),NULL,'Cap table and complete founding labor unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ks10_financing',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'financing','Meta-led CRED Series H announced','CRED announced financing and a minority Meta investment.','2026-06-22T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://newsroom.cred.club/cred-to-raise-8-550-crore-us-900m-from-meta/' LIMIT 1),NULL,'Transaction-level figures only',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ks10_whatsapp',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'role_transition','Shah transitions from CRED CEO to WhatsApp leadership','Shah left CRED operating management and joined Meta to lead WhatsApp.','2026-06-22T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/metas-whatsapp-be-led-by-indian-startup-founder-kunal-shah-2026-06-22/' LIMIT 1),NULL,'Delegated role, not platform ownership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ks10_board',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'governance_transition','CRED board and promoter transition','Filing-based reports say Shah resigned from the board and ceased promoter classification.','2026-06-22T00:00:00Z','day_reported','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.livemint.com/companies/people/kunal-shah-promoter-board-member-cred-whatsapp-meta-platforms-shareholding-11784023818673.html' LIMIT 1),NULL,'Underlying MCA filing not directly reviewed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_kunal_shah_100','kunal-shah-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'1.0.0','research/observatory/dossiers/kunal-shah-1.0.0.md','ba69cfa4a4665b8bc71f25b4d0c37a5eb7f691bb',
'{"claimIds":["obs_claim_ks10_c01","obs_claim_ks10_c02","obs_claim_ks10_c03","obs_claim_ks10_c04","obs_claim_ks10_c05","obs_claim_ks10_c06","obs_claim_ks10_c07","obs_claim_ks10_c08"],"relationshipIds":["obs_rel_ks10_cred_founder","obs_rel_ks10_sampat","obs_rel_ks10_meta","obs_rel_ks10_whatsapp","obs_rel_ks10_freecharge","obs_rel_ks10_tandon"],"eventIds":["obs_event_ks10_freecharge","obs_event_ks10_snapdeal","obs_event_ks10_cred","obs_event_ks10_financing","obs_event_ks10_whatsapp","obs_event_ks10_board"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","founder_management_governance_and_equity_separate","meta_owns_whatsapp","company_transaction_values_not_personal_economics","current_cap_table_unavailable","filing_based_holdings_attributed","distributed_labor_incomplete","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.82,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_kunal_shah_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='kunal-shah' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_kunal_shah_100',
'{"packageId":"kunal-shah-1.0.0","claimsLoaded":8,"relationshipsLoaded":6,"eventsLoaded":6,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Founder, management, governance, ownership, transaction economics, platform ownership, labor, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
