-- Charlotte Tansill public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Publicis Creative U.S.’s first President of Social, Creator and Earned in a newly created, collaborative role.',
    "summary"='A company-specific role-novelty case separating title creation, inherited capabilities, shared authority, distributed labor, ownership and causal performance.',
    "inclusionRationale"='Tests how a new integration title can coordinate existing creator, social, earned, data and agency systems without proving personal ownership, sole construction or worldwide firstness.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.80,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='charlotte-tansill';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_ct10_lbb','https://lbbonline.com/news/Charlotte-Tansill-Publicis-Creative-US-President-Social-Creator-Earned','Charlotte Tansill Joins Publicis Creative US as President, Social, Creator and Earned','Little Black Book','announcement_derived_journalism','2025-11-24T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ct10_campaign','https://www.campaignlive.com/article/publicis-creative-us-hires-charlotte-tansill-president-social-creator-earned/1940880','Publicis Creative US hires Charlotte Tansill','Campaign','journalism','2025-11-24T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ct10_self','https://www.linkedin.com/posts/charlottetansill_publicis-creative-us-hires-charlotte-tansill-activity-7401304896525946880-d8Eu','Charlotte Tansill Publicis transition announcement','Charlotte Tansill / LinkedIn','first_person_announcement',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ct10_influential','https://www.publicisgroupe.com/en/news/press-releases/publicis-groupe-to-acquire-influential-creating-world-s-leading-influencer-marketing-solution','Publicis Groupe to Acquire Influential','Publicis Groupe','primary_institutional','2024-07-25T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ct10_ogilvy21','https://www.ogilvy.com/ideas/ogilvy-pr-appoints-global-chief-creative-officer-global-chief-strategy-officer','Ogilvy PR Appoints Global Chief Creative Officer and Global Chief Strategy Officer','Ogilvy','primary_employer_announcement','2021-06-14T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ct10_transform','https://lbbonline.com/news/ogilvy-new-york-appoints-charlotte-tansill-as-chief-transformation-officer','Ogilvy New York Appoints Charlotte Tansill as Chief Transformation Officer','Little Black Book','announcement_derived_journalism','2020-11-05T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ct10_awards','https://www.ogilvy.com/ideas/ogilvy-pr-emerges-most-awarded-agency-2024-pr-week-awards','Ogilvy PR Emerges as Most-Awarded Agency at 2024 PRWeek Awards','Ogilvy','primary_employer_news','2024-03-15T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ct10_cerave','https://www.ogilvy.com/ideas/ogilvy-wins-grand-prix-ceraves-michael-cerave-jcdecauxs-meet-marina-prieto','Ogilvy Wins Grand Prix for CeraVe Michael CeraVe','Ogilvy','primary_employer_award_report','2024-06-19T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_ct10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'role_appointment','Publicis Creative U.S. appointed Tansill President, Social, Creator and Earned, U.S. in November 2025.','role_history','observed','unreviewed',NULL,'Tansill joined Publicis Creative U.S. in this president role in late 2025.','Do not imply earlier tenure or guaranteed permanence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ct10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'firstness_boundary','Contemporaneous reports describe the role as newly created and Tansill as its first holder at Publicis Creative U.S.','role_firstness','observed','unreviewed',NULL,'She is the first publicly identified holder of this Publicis Creative U.S. title.','Worldwide and industry firstness are prohibited.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ct10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'delegated_remit','Her announced remit includes integrated offerings, centers of excellence, go-to-market work and client advice.','delegated_authority','observed','unreviewed',NULL,'Tansill has announced responsibility for developing specified offerings.','Remit does not prove ownership, budget control, sole labor or unilateral authority.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ct10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'shared_authority','Tansill reports to Carla Serrano and is expected to collaborate with existing leaders and teams.','distributed_authority','observed','unreviewed',NULL,'The role sits in a shared Publicis leadership and operating structure.','Do not depict Tansill as the unilateral controller.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ct10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'institutional_boundary','Publicis owned and operated material creator, data, media, social and agency capabilities before the appointment.','institutional_system','observed','unreviewed',NULL,'Tansill entered and was tasked to connect an established system.','Do not say Publicis created the apparatus from zero around her.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ct10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'career_history','Tansill held successive Ogilvy roles across social strategy, transformation, global PR strategy and North American PR, social and influence leadership.','role_history','observed','unreviewed',NULL,'Her prior career documents expanding delegated scope at Ogilvy.','Titles do not prove ownership, sole labor or individual economics.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ct10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'distributed_labor','Ogilvy documented more than 150 North American social employees under her continuing oversight in 2021 and attributed later work to teams and clients.','distributed_labor','attributed','unreviewed',NULL,'Tansill held announced oversight within a large, multi-party system.','Do not call every employee a direct report or assign all output to her.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ct10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'claim_restriction','No reviewed record establishes ownership, private economics, isolated causal performance or valid psychological measurements for Tansill.','claim_restriction','observed','unreviewed',NULL,'Public evidence establishes roles, relationships and events, not ownership, personal financial outcomes, causality or psychology.','Absence of public evidence is not proof that no private rights exist.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_ct10_c01','obs_claim_ct10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/Charlotte-Tansill-Publicis-Creative-US-President-Social-Creator-Earned' LIMIT 1),'supports',NULL,'Appointment paragraph','Contemporaneous announcement-derived report.',CURRENT_TIMESTAMP),
('obs_ev_ct10_c02','obs_claim_ct10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.campaignlive.com/article/publicis-creative-us-hires-charlotte-tansill-president-social-creator-earned/1940880' LIMIT 1),'supports',NULL,'Role description','Company-specific firstness only.',CURRENT_TIMESTAMP),
('obs_ev_ct10_c03','obs_claim_ct10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/Charlotte-Tansill-Publicis-Creative-US-President-Social-Creator-Earned' LIMIT 1),'supports',NULL,'Remit paragraphs','Prospective remit kept separate from delivered outcomes.',CURRENT_TIMESTAMP),
('obs_ev_ct10_c04','obs_claim_ct10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/Charlotte-Tansill-Publicis-Creative-US-President-Social-Creator-Earned' LIMIT 1),'supports',NULL,'Reporting and collaboration language','Shared authority preserved.',CURRENT_TIMESTAMP),
('obs_ev_ct10_c05','obs_claim_ct10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.publicisgroupe.com/en/news/press-releases/publicis-groupe-to-acquire-influential-creating-world-s-leading-influencer-marketing-solution' LIMIT 1),'supports',NULL,'Acquisition and capability description','Pre-appointment creator infrastructure.',CURRENT_TIMESTAMP),
('obs_ev_ct10_c06','obs_claim_ct10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.ogilvy.com/ideas/ogilvy-pr-appoints-global-chief-creative-officer-global-chief-strategy-officer' LIMIT 1),'supports',NULL,'Career and appointment paragraphs','Employer chronology.',CURRENT_TIMESTAMP),
('obs_ev_ct10_c07','obs_claim_ct10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.ogilvy.com/ideas/ogilvy-pr-appoints-global-chief-creative-officer-global-chief-strategy-officer' LIMIT 1),'supports',NULL,'North America social teams paragraph','Organization-wide team figure, not direct-report proof.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_ct10_publicis',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'organization','Publicis Creative U.S.','president_social_creator_earned','2025-11-24T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/Charlotte-Tansill-Publicis-Creative-US-President-Social-Creator-Earned' LIMIT 1),NULL,'Contract, equity, budget and board authority unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ct10_serrano',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'person','Carla Serrano','reports_to','2025-11-24T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/Charlotte-Tansill-Publicis-Creative-US-President-Social-Creator-Earned' LIMIT 1),NULL,'Exact authority and budget split unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ct10_leadership',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'organization','Publicis Groupe U.S. leadership team','member_and_collaborator','2025-11-24T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/Charlotte-Tansill-Publicis-Creative-US-President-Social-Creator-Earned' LIMIT 1),NULL,'Membership does not prove unilateral governance',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ct10_influential',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'organization','Influential','adjacent_preexisting_capability','2025-11-24T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.publicisgroupe.com/en/news/press-releases/publicis-groupe-to-acquire-influential-creating-world-s-leading-influencer-marketing-solution' LIMIT 1),NULL,'Predates appointment; direct control not established',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ct10_ogilvy',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'organization','Ogilvy','former_executive','2008-01-01T00:00:00Z','2025-11-24T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.ogilvy.com/ideas/ogilvy-pr-appoints-global-chief-creative-officer-global-chief-strategy-officer' LIMIT 1),NULL,'Exact personnel chronology and economics incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ct10_cerave',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'project','Michael CeraVe','senior_agency_collaborator','2023-01-01T00:00:00Z','2024-06-19T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.ogilvy.com/ideas/ogilvy-wins-grand-prix-ceraves-michael-cerave-jcdecauxs-meet-marina-prieto' LIMIT 1),NULL,'Multi-party campaign; sole authorship and causation prohibited',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_ct10_ogilvy_start',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'role_history','Ogilvy career begins','Public profiles place Tansill at Ogilvy from approximately 2008.','2008-01-01T00:00:00Z','year_approximate','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.ogilvy.com/ideas/ogilvy-pr-appoints-global-chief-creative-officer-global-chief-strategy-officer' LIMIT 1),NULL,'Employer announcement states 13 years in 2021',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ct10_transform',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'role_appointment','Ogilvy New York transformation role','Tansill was appointed Chief Transformation Officer after leading the social practice.','2020-11-05T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/ogilvy-new-york-appoints-charlotte-tansill-as-chief-transformation-officer' LIMIT 1),NULL,'Established teams and functions predated title',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ct10_global_cso',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'role_appointment','Ogilvy PR Global CSO appointment','Ogilvy appointed Tansill Global Chief Strategy Officer for Ogilvy PR.','2021-06-14T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.ogilvy.com/ideas/ogilvy-pr-appoints-global-chief-creative-officer-global-chief-strategy-officer' LIMIT 1),NULL,'Delegated remit, not ownership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ct10_influential',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'institutional_event','Publicis announces Influential acquisition','Publicis announced material creator technology, data, network and delivery capabilities before Tansill joined.','2024-07-25T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.publicisgroupe.com/en/news/press-releases/publicis-groupe-to-acquire-influential-creating-world-s-leading-influencer-marketing-solution' LIMIT 1),NULL,'Company claims attributed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ct10_publicis',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'role_appointment','Publicis Creative U.S. appointment','Tansill joined the newly created, company-specific president role.','2025-11-24T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/Charlotte-Tansill-Publicis-Creative-US-President-Social-Creator-Earned' LIMIT 1),NULL,'RoleBuiltFlag remains false; construction by Tansill not established',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_charlotte_tansill_100','charlotte-tansill-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'1.0.0','research/observatory/dossiers/charlotte-tansill-1.0.0.md','05f0d2ebae5a7aa5c4efc50a68786e721f419295',
'{"claimIds":["obs_claim_ct10_c01","obs_claim_ct10_c02","obs_claim_ct10_c03","obs_claim_ct10_c04","obs_claim_ct10_c05","obs_claim_ct10_c06","obs_claim_ct10_c07","obs_claim_ct10_c08"],"relationshipIds":["obs_rel_ct10_publicis","obs_rel_ct10_serrano","obs_rel_ct10_leadership","obs_rel_ct10_influential","obs_rel_ct10_ogilvy","obs_rel_ct10_cerave"],"eventIds":["obs_event_ct10_ogilvy_start","obs_event_ct10_transform","obs_event_ct10_global_cso","obs_event_ct10_influential","obs_event_ct10_publicis"],"observationIds":[],"limitations":["saturation_open","company_specific_firstness_only","worldwide_firstness_prohibited","role_built_flag_false","institutional_capabilities_preexisting","shared_authority","ownership_and_economics_unavailable","distributed_labor_incomplete","campaign_causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.80,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_charlotte_tansill_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='charlotte-tansill' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_charlotte_tansill_100',
'{"packageId":"charlotte-tansill-1.0.0","claimsLoaded":8,"relationshipsLoaded":6,"eventsLoaded":5,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Company-specific firstness, pre-existing infrastructure, shared authority, distributed labor, ownership, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
