import type {Metadata} from "next";
import Link from "next/link";
import {SEED,nodeSlug} from "@/lib/observatory_seed";
import {getCaseResearch} from "@/lib/case_research";
import styles from "./documentation.module.css";
export const metadata:Metadata={title:"Case Documentation Ledger — The Observatory",description:"See which Institutions of One cases are fully saturated, which remain provisional, and what completion requires.",alternates:{canonical:"/observatory/documentation"}};
const REQUIREMENTS=[
["Identity and scope","Disambiguated person, entities, roles, dates, jurisdictions, and the precise structural question the case is being used to examine."],
["Claim inventory","Every factual, causal, comparative, ownership, control, portability, and continuity claim separated into an auditable statement."],
["Claim-level citations","Each material claim linked to the specific supporting source and, where possible, passage, page, timestamp, filing, or official record—not a shared bibliography attached to a whole section."],
["Source triangulation","Primary records for formal facts; first-party sources for self-description; independent reporting or scholarship for corroboration and context; conflicts preserved rather than averaged away."],
["Structural chronology","Dated or honestly bounded events showing what changed, when, and which evidence supports each event. Broad periods remain broad."],
["Build–Carry–Control–Continue","Case-specific findings for what was built, what could travel, what was controlled, and what could persist. Visibility, influence, access, and legal ownership remain distinct."],
["Dependency and governance map","Employer, platform, title, capital, audience, founder, intellectual property, distribution, partners, public mandate, decision rights, and succession—documented, inferred, private, or unknown."],
["Competing explanations","The strongest counterevidence, alternative causal account, team or institutional contribution, and countercase that could weaken the inviting lesson."],
["Unknowns and acquisition plan","Important unresolved facts stated as questions, with the public record, filing, interview, contract, dataset, or follow-up review that could answer them."],
["Review and version trail","Researcher, review date, source checks, changes from the prior version, evidence added or withdrawn, and the interpretation affected by each change."]
];
const rows=SEED.map(p=>{const slug=nodeSlug(p.name);const r=getCaseResearch(slug)!;return {p,slug,r};});
export default function Page(){const saturated=rows.filter(x=>x.r.documentationLevel==="saturated");const provisional=rows.filter(x=>x.r.documentationLevel==="provisional");return <main className="observatory-page"><p className="eyebrow">The Observatory · Research Integrity</p><h1>Strong documentation is a claim-to-evidence system.</h1><p className="lede">A long profile and a long bibliography are not enough. A case is saturated only when its chronology, structural interpretation, dependencies, complications, and unknowns can be traced to the evidence that permits each statement.</p><p><a href="/observatory">← The Observatory</a></p>
<section className={styles.summary}><article><strong>{saturated.length}</strong><span>Saturated case records</span></article><article><strong>{provisional.length}</strong><span>Provisional records requiring full case research</span></article><article><strong>{REQUIREMENTS.length}</strong><span>Required documentation layers</span></article></section>
<section className={styles.standard}><p className={styles.kicker}>The completion standard</p><h2>What each of the 41 cases must contain</h2><div className={styles.requirements}>{REQUIREMENTS.map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div></section>
<section className={styles.status}><div><p className={styles.kicker}>Completed case records</p><h2>Documented to the current standard</h2><p>All 41 cases are now built as discrete claim-level research records. Saturation means the public evidence has been traced, bounded, challenged, and reviewed—not that private facts become knowable.</p>{saturated.map(x=><Link key={x.slug} href={"/observatory/"+x.slug}><strong>{x.p.name}</strong><span>{x.r.sources.length} sources · {x.r.chronology.length} sourced chronology events · {x.r.complication.length} complications · {x.r.unknowns.length} explicit unknowns</span></Link>)}</div>
<div><p className={styles.kicker}>Research queue</p><h2>{provisional.length ? "Provisional, not fully documented" : "No provisional records remain"}</h2><p>{provisional.length ? "These records are usable as research leads and browsing profiles. Their current milestone and structural summary do not yet satisfy claim-level saturation." : "Every case in the current 41-record collection has completed the claim-level migration. New cases enter here as provisional until they meet the same standard."}</p><div className={styles.queue}>{provisional.map(x=><Link key={x.slug} href={"/observatory/"+x.slug}><span>{x.p.name}</span><small>{x.p.domain}</small></Link>)}</div></div></section>
<aside className={styles.guardrail}><strong>What “strongly documented” does not mean</strong><span>It does not mean every claim is confirmed, every case has the same number of sources, or private ownership and contracts become knowable. It means the reader can see what is established, by whom, through which evidence, with what contradiction, and with which remaining uncertainty.</span></aside></main>;}
