import type * as React from 'react';
import type { ToolSpec, Crumb, SiteLinks, RelatedItem, Basis, ResultLine } from '../types.d.mts';
export const h: typeof React.createElement;
export function JsFlag(): null;
export const TK_JS_SCRIPT: string;
export function ToolShell(p: { spec: ToolSpec; related?: RelatedItem[]; crumbs?: Crumb[]; siteLinks?: SiteLinks; children?: React.ReactNode }): React.ReactElement;
export function ClaimRef(p: { spec: ToolSpec; claimId: string }): React.ReactElement;
export function SourceRef(p: { spec: ToolSpec; sourceId: string }): React.ReactElement;
export function BasisTag(p: { basis: Basis }): React.ReactElement;
export function ToolHeader(p: { spec: ToolSpec }): React.ReactElement;
export function LimitsBand(p: { spec: ToolSpec }): React.ReactElement;
export function SourceDrawer(p: { spec: ToolSpec }): React.ReactElement;
export function OriginBar(p: { spec: ToolSpec }): React.ReactElement;
export function RelatedRail(p: { items: RelatedItem[] }): React.ReactElement | null;
export function StatusLine(): React.ReactElement;
export function Crumbs(p: { crumbs: Crumb[]; current: string }): React.ReactElement;
export function ResultCard(p: { spec: ToolSpec; id?: string; headline: string; basis?: Basis | null; lines: (string | ResultLine)[]; note?: string; payload?: { lines?: string[]; text?: () => string; txt?: () => string; csv?: () => string } }): React.ReactElement;
export function announce(text: string): void;
export function copyText(text: string): Promise<boolean>;
export function downloadText(filename: string, text: string, type?: string): void;
export function downloadBlob(filename: string, blob: Blob): void;
export function filterApproved(spec: ToolSpec): ToolSpec;
export function sourceNumber(spec: ToolSpec, id: string): number;
export function claimText(spec: ToolSpec, id: string): string;
