-- Fei-Fei Li public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, assign institutional assets, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Stanford scientist and World Labs co-founder with institution-bounded research, nonprofit, company and media roles.',
    "summary"='A role- and holder-bounded account separating Stanford, ImageNet, HAI, AI4ALL, World Labs, Google, Twitter, publishing and advisory work.',
    "inclusionRationale"='Tests whether a prominent scientist-founder can be represented without conflating research leadership, sole invention, nonprofit governance, company ownership, institutional labor, financing, IP, causal impact or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.88,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='fei-fei-li';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_ffl10_hai','https://hai.stanford.edu/people/fei-fei-li','Fei-Fei Li','Stanford HAI','primary_institution_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ffl10_img','https://www.image-net.org/static_files/papers/imagenet_cvpr09.pdf','ImageNet: A Large-Scale Hierarchical Image Database','CVPR','scholarly_paper','2009-06-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ffl10_ai4','https://ai-4-all.org/our-people/fei-fei-li/','Dr. Fei-Fei Li','AI4ALL','primary_nonprofit_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ffl10_wl','https://www.worldlabs.ai/about','About World Labs','World Labs','primary_company_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ffl10_r24','https://www.reuters.com/technology/artificial-intelligence/ai-godmother-fei-fei-li-raises-230-million-launch-ai-startup-2024-09-13/','Fei-Fei Li raises $230 million to launch AI startup','Reuters','independent_journalism','2024-09-13T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ffl10_r26','https://www.reuters.com/business/ai-pioneer-fei-fei-lis-world-labs-raises-1-billion-funding-2026-02-18/','World Labs raises $1 billion in funding','Reuters','independent_journalism','2026-02-18T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ffl10_google','https://cloud.google.com/blog/products/ai-machine-learning/feifei-li-and-jia-li-join-google-cloud','Fei-Fei Li and Jia Li join Google Cloud','Google Cloud','primary_company_announcement','2016-11-15T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ffl10_book','https://us.macmillan.com/books/9781250897930/theworldsisee/','The Worlds I See','Macmillan','publisher_page','2023-11-07T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ffl10_tw20','https://www.sec.gov/Archives/edgar/data/1418091/000156459020024062/twtr-8k_20200511.htm','Twitter Form 8-K May 2020','SEC','securities_filing','2020-05-11T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ffl10_tw22','https://www.sec.gov/Archives/edgar/data/1418091/000119312522270119/d396440d8k.htm','Twitter Form 8-K October 2022','SEC','securities_filing','2022-10-27T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ffl10_un','https://www.un.org/scientific-advisory-board/sites/default/files/2024-03/SAB%20one-pager%20flyer%202024.pdf','Scientific Advisory Board overview, 2024','United Nations','primary_advisory_register','2024-03-01T00:00:00Z','2026-08-29T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_ffl10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'current_role','Li is a Stanford professor and Denning Co-Director of Stanford HAI as of July 26, 2026.','formal_role','primary_record','unreviewed',NULL,'Current Stanford professor and HAI co-director, with an as-of date.','No ownership of Stanford, HAI, grants, staff, research or outputs.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ffl10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'research_leadership','Li led ImageNet development within a documented scholarly and institutional team.','distributed_invention','corroborated','unreviewed',NULL,'Led or was a principal creator of ImageNet.','No sole invention, sole labor, personal dataset ownership or attribution of all downstream AI advances.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ffl10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'nonprofit_role','Li co-founded AI4ALL and serves as chairperson within a separately governed nonprofit.','formal_role','primary_record','unreviewed',NULL,'Co-founder and chairperson of AI4ALL.','No personal ownership of nonprofit assets, donations, programs or outcomes.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ffl10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'company_role','Li is a named co-founder and CEO of World Labs, founded with Justin Johnson, Christoph Lassner and Ben Mildenhall.','formal_role','corroborated','unreviewed',NULL,'Co-founder and CEO of World Labs.','No sole founding, sole labor, sole ownership or unilateral control.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ffl10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'financing_boundary','World Labs raised reported company financings of $230 million in 2024 and $1 billion in 2026 from multiple investors.','financial_boundary','corroborated','unreviewed',NULL,'World Labs raised the reported company financing.','No conversion into Li personal wealth, proceeds, valuation or ownership percentage.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ffl10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'role_history','Li formerly directed SAIL and served as Google Cloud VP and Chief Scientist of AI/ML during a Stanford sabbatical.','time_bounded_authority','primary_record','unreviewed',NULL,'Former SAIL director and Google Cloud executive.','No ownership of institutional products, contracts, teams or research.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ffl10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'board_history','Li served as an independent Twitter director from 2020 until the board ended following the 2022 acquisition.','time_bounded_authority','primary_record','unreviewed',NULL,'Former Twitter director, 2020–2022.','No present authority, personal ownership, causal performance or individualized for-cause removal.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ffl10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'creative_role','Li authored The Worlds I See under a commercial publisher relationship.','creative_role','primary_record','unreviewed',NULL,'Author of the identified memoir.','No advance, royalty, copyright-allocation, translation, adaptation or sales claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ffl10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'advisory_role','The United Nations listed Li as a member of the Secretary-General’s Scientific Advisory Board in its 2024 Board overview.','formal_role','primary_record','unreviewed',NULL,'Listed by the United Nations as a member of the identified advisory body in 2024.','No executive authority, UN ownership, unilateral policy authorship or control. The Board’s current published membership list does not include Li, so present-tense membership must not be asserted.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ffl10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'claim_restriction','No reviewed public record establishes World Labs complete cap table, Li beneficial ownership, voting control, employment terms, Stanford conflict terms, IP allocations, media economics, complete labor attribution, causal performance or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified or incomplete.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_ffl10_c01','obs_claim_ffl10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://hai.stanford.edu/people/fei-fei-li' LIMIT 1),'supports',NULL,'Faculty biography','Current role requires later refresh.',CURRENT_TIMESTAMP),
('obs_ev_ffl10_c02','obs_claim_ffl10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.image-net.org/static_files/papers/imagenet_cvpr09.pdf' LIMIT 1),'supports',NULL,'Authors and paper body','Distributed authorship and labor preserved.',CURRENT_TIMESTAMP),
('obs_ev_ffl10_c03','obs_claim_ffl10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://ai-4-all.org/our-people/fei-fei-li/' LIMIT 1),'supports',NULL,'Leadership biography','Nonprofit separate from person.',CURRENT_TIMESTAMP),
('obs_ev_ffl10_c04','obs_claim_ffl10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/technology/artificial-intelligence/ai-godmother-fei-fei-li-raises-230-million-launch-ai-startup-2024-09-13/' LIMIT 1),'supports',NULL,'Launch report','Cofounders and staff preserved.',CURRENT_TIMESTAMP),
('obs_ev_ffl10_c05','obs_claim_ffl10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/ai-pioneer-fei-fei-lis-world-labs-raises-1-billion-funding-2026-02-18/' LIMIT 1),'supports',NULL,'2026 financing report','Company capital not personal wealth.',CURRENT_TIMESTAMP),
('obs_ev_ffl10_c06','obs_claim_ffl10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://cloud.google.com/blog/products/ai-machine-learning/feifei-li-and-jia-li-join-google-cloud' LIMIT 1),'supports',NULL,'Company announcement','Time-bounded institutional role.',CURRENT_TIMESTAMP),
('obs_ev_ffl10_c07','obs_claim_ffl10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1418091/000119312522270119/d396440d8k.htm' LIMIT 1),'supports',NULL,'Board termination disclosure','Acquisition event not individualized motive.',CURRENT_TIMESTAMP),
('obs_ev_ffl10_c08','obs_claim_ffl10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.macmillan.com/books/9781250897930/theworldsisee/' LIMIT 1),'supports',NULL,'Publisher page','Rights and economics unresolved.',CURRENT_TIMESTAMP),
('obs_ev_ffl10_c09','obs_claim_ffl10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.un.org/scientific-advisory-board/sites/default/files/2024-03/SAB%20one-pager%20flyer%202024.pdf' LIMIT 1),'supports',NULL,'Board register','Advisory role only.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_ffl10_stanford',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'organization','Stanford University','professor',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://hai.stanford.edu/people/fei-fei-li' LIMIT 1),NULL,'University appointment; institutional assets preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ffl10_hai',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'organization','Stanford HAI','founding_co_director','2019-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://hai.stanford.edu/people/fei-fei-li' LIMIT 1),NULL,'Co-director and university governance preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ffl10_img',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'project','ImageNet','research_leader_and_named_author','2007-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.image-net.org/static_files/papers/imagenet_cvpr09.pdf' LIMIT 1),NULL,'Coauthors, students, annotators and institutions preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ffl10_ai4',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'organization','AI4ALL','cofounder_and_chairperson','2017-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://ai-4-all.org/our-people/fei-fei-li/' LIMIT 1),NULL,'Separate nonprofit governance and assets',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ffl10_wl',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'organization','World Labs','cofounder_and_ceo','2024-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.worldlabs.ai/about' LIMIT 1),NULL,'Cofounders, employees, investors, directors and IP preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ffl10_google',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'organization','Google Cloud','former_vp_and_chief_scientist_ai_ml','2017-01-01T00:00:00Z','2018-12-31T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://cloud.google.com/blog/products/ai-machine-learning/feifei-li-and-jia-li-join-google-cloud' LIMIT 1),NULL,'Time-bounded employee authority',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ffl10_twitter',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'organization','Twitter','former_independent_director','2020-05-11T00:00:00Z','2022-10-27T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1418091/000119312522270119/d396440d8k.htm' LIMIT 1),NULL,'Board role ended with acquisition',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_ffl10_2007',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'project_start','ImageNet work begins','ImageNet work began under Li research leadership within a team and institutional context.','2007-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://hai.stanford.edu/people/fei-fei-li' LIMIT 1),NULL,'No sole-invention inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ffl10_2009',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'publication','ImageNet paper published','CVPR paper identifies named coauthors and dataset method.','2009-06-01T00:00:00Z','month','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.image-net.org/static_files/papers/imagenet_cvpr09.pdf' LIMIT 1),NULL,'Scholarly and labor boundaries preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ffl10_2017',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'institution_launch','AI4ALL launches','AI4ALL begins as a separately governed nonprofit initiative.','2017-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://ai-4-all.org/our-people/fei-fei-li/' LIMIT 1),NULL,'Co-founder and nonprofit boundary',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ffl10_2020',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'appointment','Li joins Twitter board','SEC filing records independent-director appointment.','2020-05-11T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1418091/000156459020024062/twtr-8k_20200511.htm' LIMIT 1),NULL,'No company ownership inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ffl10_2022',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'role_end','Twitter board service ends','Board ended following acquisition.','2022-10-27T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1418091/000119312522270119/d396440d8k.htm' LIMIT 1),NULL,'Corporate event, no individualized motive',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ffl10_2024',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'company_launch','World Labs publicly launches','Four named cofounders and reported $230 million company financing.','2024-09-13T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/technology/artificial-intelligence/ai-godmother-fei-fei-li-raises-230-million-launch-ai-startup-2024-09-13/' LIMIT 1),NULL,'Company capital and distributed formation',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ffl10_2026',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'financing','World Labs financing reported','Reuters reported a $1 billion company financing from multiple investors.','2026-02-18T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/ai-pioneer-fei-fei-lis-world-labs-raises-1-billion-funding-2026-02-18/' LIMIT 1),NULL,'No personal wealth or ownership conversion',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_fei_fei_li_100','fei-fei-li-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'1.0.0','research/observatory/dossiers/fei-fei-li-1.0.0.md','0a126335fefdc96082ad692993bf3a0898eaf48f',
'{"claimIds":["obs_claim_ffl10_c01","obs_claim_ffl10_c02","obs_claim_ffl10_c03","obs_claim_ffl10_c04","obs_claim_ffl10_c05","obs_claim_ffl10_c06","obs_claim_ffl10_c07","obs_claim_ffl10_c08","obs_claim_ffl10_c09","obs_claim_ffl10_c10"],"relationshipIds":["obs_rel_ffl10_stanford","obs_rel_ffl10_hai","obs_rel_ffl10_img","obs_rel_ffl10_ai4","obs_rel_ffl10_wl","obs_rel_ffl10_google","obs_rel_ffl10_twitter"],"eventIds":["obs_event_ffl10_2007","obs_event_ffl10_2009","obs_event_ffl10_2017","obs_event_ffl10_2020","obs_event_ffl10_2022","obs_event_ffl10_2024","obs_event_ffl10_2026"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","distributed_scientific_labor","institutional_governance","company_financing_not_personal_wealth","cap_table_unverified","ip_allocation_unverified","media_rights_unverified","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.88,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_fei_fei_li_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='fei-fei-li' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_fei_fei_li_100',
'{"packageId":"fei-fei-li-1.0.0","claimsLoaded":10,"relationshipsLoaded":7,"eventsLoaded":7,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Scientific, institutional, nonprofit, company, ownership, financing, IP, media-rights, labor, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
