-- Brian May public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, assign institutional assets, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Queen founding member, astrophysicist, stereoscopic publisher and charity co-founder with holder-bounded roles.',
    "summary"='A role- and rights-bounded account separating Queen, Queen companies, music rights, Imperial research, mission teams, stereoscopic publishing, patent relationships and Save Me governance.',
    "inclusionRationale"='Tests whether a polymath can be represented without conflating band membership, corporate authority, ownership, transaction value, scientific collaboration, publishing rights, charity assets, causal impact or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.88,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='brian-may';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_bmy10_bio','https://brianmay.com/brian-may-biography/','Sir Brian May biography','BrianMay.com','primary_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_queen','https://www.queenonline.com/queen','Queen','Queen','primary_band_history',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_ch','https://find-and-update.company-information.service.gov.uk/company/01226628/officers','Queen Productions Limited officers','Companies House','corporate_register',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_cat','https://variety.com/2024/music/news/queen-catalog-acquired-by-sony-music-1-billion-1236042619/','Queen catalog to be acquired by Sony Music for £1 billion','Variety','trade_reporting','2024-06-19T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_thesis','https://spiral.imperial.ac.uk/entities/publication/3d426771-aa65-4ac5-a546-42b23881e3db','A survey of radial velocities in the zodiacal dust cloud','Imperial College London','doctoral_thesis','2007-01-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_grad','https://www.imperial.ac.uk/news/37754/imperial-college-graduation/','Imperial College Graduation','Imperial College London','primary_institutional_news','2008-06-03T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_nasa','https://science.nasa.gov/mission/osiris-rex/','OSIRIS-REx','NASA','primary_mission_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_time','https://time.com/5492147/brian-may-ultima-thule/','Brian May on his work with NASA and New Horizons','TIME','independent_interview','2019-01-02T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_lsc','https://londonstereo.com/','London Stereoscopic Company official site','London Stereoscopic Company','primary_company_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_pat','https://patents.google.com/patent/GB2482249A/en','Stereoscopic viewer','UKIPO / Google Patents','patent_record','2012-01-11T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_save','https://savemetrust.co.uk/','Save Me Trust','Save Me Trust','primary_charity_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_cc','https://register-of-charities.charitycommission.gov.uk/en/charity-search/-/charity-details/3972041/trustees','Save Me Trust trustees','Charity Commission','charity_register',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bmy10_hon','https://www.thegazette.co.uk/London/issue/63918/supplement/N2','New Year Honours 2023','The Gazette','official_honours_record','2022-12-31T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_bmy10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'music_role','May is a founding member of Queen and a credited guitarist, songwriter, producer and performer.','formal_role','corroborated','unreviewed',NULL,'Queen founding member and credited musician-songwriter.','No sole formation, sole authorship, ownership of Queen or attribution of all band output.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bmy10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'distributed_labor','Queen work and operations involve other members, estates, performers, employees, producers, managers, companies and rights holders.','distributed_creation','corroborated','unreviewed',NULL,'A member of a multi-person and institutionally supported band.','No solitary-genius, sole-labor or sole-impact account.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bmy10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'board_history','Companies House records May as a former Queen Productions director whose appointment ended on 26 June 2024.','time_bounded_authority','primary_record','unreviewed',NULL,'Former Queen Productions director, ending June 2024.','No present directorship, forced-removal motive or complete rights inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bmy10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'transaction_boundary','Trade reporting valued the 2024 Queen catalogue transaction at approximately £1 billion.','financial_boundary','attributed_report','unreviewed',NULL,'A reported Queen catalogue transaction of approximately £1 billion.','No conversion into May personal proceeds, wealth, ownership share or tax result.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bmy10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'academic_role','May completed an Imperial doctorate in 2007 concerning radial velocities in the zodiacal dust cloud.','formal_credential','primary_record','unreviewed',NULL,'Imperial College London PhD in astrophysics.','No sole data, sole discovery, field ownership or universal scientific authority.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bmy10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'scientific_collaboration','May contributed stereoscopic imaging and data-analysis work to named space-mission teams.','distributed_invention','corroborated','unreviewed',NULL,'Scientific collaborator on identified mission work.','No NASA employment, mission ownership, sole decision or sole discovery.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bmy10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'publishing_role','May heads the London Stereoscopic Company and publishes stereoscopic books and viewers through it.','formal_role','primary_record','unreviewed',NULL,'Heads the London Stereoscopic Company.','No complete beneficial ownership, unilateral control, sole labor or ownership of every image and publication.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bmy10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'inventorship','Patent records identify May in relation to the OWL stereoscopic viewer with holder-specific rights.','ip_boundary','primary_record','unreviewed',NULL,'Named inventor on the identified viewer patent.','No ownership of every patent, current enforceability or undisclosed royalty economics.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bmy10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'charity_role','May and Anne Brummer co-founded Save Me, which operates through separate charity governance.','formal_role','corroborated','unreviewed',NULL,'Co-founder and trustee of Save Me Trust.','No sole founding, personal ownership of charity assets or attribution of every campaign outcome.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bmy10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'claim_restriction','No reviewed public record establishes May complete current music-rights portfolio, transaction proceeds, company cap tables, voting control, publishing economics, patent economics, charity funding contribution, complete labor, causal impact or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified or incomplete.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_bmy10_c01','obs_claim_bmy10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://brianmay.com/brian-may-biography/' LIMIT 1),'supports',NULL,'Official biography','Band and role boundaries.',CURRENT_TIMESTAMP),
('obs_ev_bmy10_c02','obs_claim_bmy10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.queenonline.com/queen' LIMIT 1),'supports',NULL,'Band history','Distributed membership and labor.',CURRENT_TIMESTAMP),
('obs_ev_bmy10_c03','obs_claim_bmy10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://find-and-update.company-information.service.gov.uk/company/01226628/officers' LIMIT 1),'supports',NULL,'Officer register','Time-bounded corporate office.',CURRENT_TIMESTAMP),
('obs_ev_bmy10_c04','obs_claim_bmy10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://variety.com/2024/music/news/queen-catalog-acquired-by-sony-music-1-billion-1236042619/' LIMIT 1),'supports',NULL,'Trade report','Transaction value is not personal wealth.',CURRENT_TIMESTAMP),
('obs_ev_bmy10_c05','obs_claim_bmy10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://spiral.imperial.ac.uk/entities/publication/3d426771-aa65-4ac5-a546-42b23881e3db' LIMIT 1),'supports',NULL,'Thesis record','Credential and research bounded.',CURRENT_TIMESTAMP),
('obs_ev_bmy10_c06','obs_claim_bmy10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://time.com/5492147/brian-may-ultima-thule/' LIMIT 1),'supports',NULL,'Interview and mission report','Mission team preserved.',CURRENT_TIMESTAMP),
('obs_ev_bmy10_c07','obs_claim_bmy10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://londonstereo.com/' LIMIT 1),'supports',NULL,'Company history','Collaborators and rights preserved.',CURRENT_TIMESTAMP),
('obs_ev_bmy10_c08','obs_claim_bmy10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://patents.google.com/patent/GB2482249A/en' LIMIT 1),'supports',NULL,'Patent record','Inventorship differs from ownership.',CURRENT_TIMESTAMP),
('obs_ev_bmy10_c09','obs_claim_bmy10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://register-of-charities.charitycommission.gov.uk/en/charity-search/-/charity-details/3972041/trustees' LIMIT 1),'supports',NULL,'Trustee register','Charity governance and assets preserved.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_bmy10_queen',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'organization','Queen','founding_member_guitarist_songwriter','1970-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.queenonline.com/queen' LIMIT 1),NULL,'Other members, estates and rights holders preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bmy10_qpl',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'organization','Queen Productions Limited','former_director',NULL,'2024-06-26T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://find-and-update.company-information.service.gov.uk/company/01226628/officers' LIMIT 1),NULL,'Corporate office not complete ownership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bmy10_imperial',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'organization','Imperial College London','phd_holder_and_researcher','1970-01-01T00:00:00Z','2007-12-31T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://spiral.imperial.ac.uk/entities/publication/3d426771-aa65-4ac5-a546-42b23881e3db' LIMIT 1),NULL,'Institutional examination, data and facilities preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bmy10_space',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'program','New Horizons and OSIRIS-REx mission work','scientific_and_stereoscopic_collaborator','2015-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://time.com/5492147/brian-may-ultima-thule/' LIMIT 1),NULL,'NASA and mission-team authority preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bmy10_lsc',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'organization','London Stereoscopic Company','head_author_and_publisher','2008-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://londonstereo.com/' LIMIT 1),NULL,'Coauthors, staff, cap table, contracts and rights preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bmy10_pat',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'ip_family','OWL stereoscopic viewer patent family','named_inventor',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://patents.google.com/patent/GB2482249A/en' LIMIT 1),NULL,'Inventorship, ownership and economics separated',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bmy10_save',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'organization','Save Me Trust','cofounder_and_trustee','2010-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://register-of-charities.charitycommission.gov.uk/en/charity-search/-/charity-details/3972041/trustees' LIMIT 1),NULL,'Anne Brummer, trustees, staff and charity assets preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_bmy10_1970',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'institution_launch','Queen forms','Queen formed with May and other named members.','1970-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.queenonline.com/queen' LIMIT 1),NULL,'No sole-founder inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_bmy10_2007',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'credential','Astrophysics doctorate completed','Imperial approved May doctoral thesis after a long interruption.','2007-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.imperial.ac.uk/news/37754/imperial-college-graduation/' LIMIT 1),NULL,'Academic credential only',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_bmy10_2010',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'institution_launch','Save Me begins','Save Me formally began as a separately governed charity co-founded by May and Brummer.','2010-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://savemetrust.co.uk/' LIMIT 1),NULL,'No personal charity ownership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_bmy10_2015',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'scientific_collaboration','New Horizons activity','May participated in documented mission-team scientific and stereoscopic work.','2015-07-17T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://time.com/5492147/brian-may-ultima-thule/' LIMIT 1),NULL,'Mission-team contribution only',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_bmy10_2024dir',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'role_end','Queen Productions directorship ends','Companies House records the endpoint of May corporate directorship.','2024-06-26T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://find-and-update.company-information.service.gov.uk/company/01226628/officers' LIMIT 1),NULL,'No motive inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_bmy10_2024cat',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'transaction','Queen catalogue transaction reported','Trade reporting described an approximately £1 billion rights transaction.','2024-06-19T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://variety.com/2024/music/news/queen-catalog-acquired-by-sony-music-1-billion-1236042619/' LIMIT 1),NULL,'Personal proceeds and rights allocation unverified',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_brian_may_100','brian-may-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'1.0.0','research/observatory/dossiers/brian-may-1.0.0.md','20e0b98d08f48210c7e5b817d749eb9654096c6a',
'{"claimIds":["obs_claim_bmy10_c01","obs_claim_bmy10_c02","obs_claim_bmy10_c03","obs_claim_bmy10_c04","obs_claim_bmy10_c05","obs_claim_bmy10_c06","obs_claim_bmy10_c07","obs_claim_bmy10_c08","obs_claim_bmy10_c09","obs_claim_bmy10_c10"],"relationshipIds":["obs_rel_bmy10_queen","obs_rel_bmy10_qpl","obs_rel_bmy10_imperial","obs_rel_bmy10_space","obs_rel_bmy10_lsc","obs_rel_bmy10_pat","obs_rel_bmy10_save"],"eventIds":["obs_event_bmy10_1970","obs_event_bmy10_2007","obs_event_bmy10_2010","obs_event_bmy10_2015","obs_event_bmy10_2024dir","obs_event_bmy10_2024cat"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","distributed_band_scientific_publishing_and_charity_labor","company_and_charity_governance","catalogue_value_not_personal_wealth","current_music_rights_unverified","cap_tables_unverified","ip_and_media_rights_unverified","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.88,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_brian_may_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brian-may' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_brian_may_100',
'{"packageId":"brian-may-1.0.0","claimsLoaded":10,"relationshipsLoaded":7,"eventsLoaded":6,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Band, corporate, music-rights, scientific, publishing, IP, charity, labor, economics, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
