import type {Metadata} from "next";
import { withSocial } from "@/lib/page-meta";
import Link from "next/link";
import {SEED,nodeSlug} from "@/lib/observatory_seed";
import {getCaseResearch} from "@/lib/case_research";
import {countSources} from "@/components/case/caseData";
import styles from "./documentation.module.css";
export const metadata:Metadata=withSocial({title:"Case Documentation Ledger — The Observatory",description:"See how each case record is built, which records remain provisional, and what a complete record requires.",alternates:{canonical:"/observatory/documentation"}},"/observatory/documentation");
const REQUIREMENTS=[
["Identity and scope","Disambiguated person, entities, roles, dates, jurisdictions, and the precise structural question the case is being used to examine."],
["Claim inventory","Every factual, causal, comparative, ownership, control, portability, and continuity claim separated into an auditable statement."],
["Claim-level citations","Each material claim linked to the specific supporting source and, where possible, passage, page, timestamp, filing, or official record, with each source attached to its own claim."],
["Source triangulation","Primary records for formal facts; first-party sources for self-description; independent reporting or scholarship for corroboration and context; conflicts preserved rather than averaged away."],
["Structural chronology","Dated or honestly bounded events showing what changed, when, and which evidence supports each event. Broad periods remain broad."],
["Build–Carry–Control–Continue","Case-specific findings for what was built, what could travel, what was controlled, and what could persist. Visibility, influence, access, and legal ownership remain distinct."],
["Dependency and governance map","Employer, platform, title, capital, audience, founder, intellectual property, distribution, partners, public mandate, decision rights, and succession—documented, inferred, private, or unknown."],
["Competing explanations","The strongest counterevidence, alternative causal account, team or institutional contribution, and countercase that could weaken the inviting lesson."],
["Unknowns and acquisition plan","Important unresolved facts stated as questions, with the public record, filing, interview, contract, dataset, or follow-up review that could answer them."],
["Review and version trail","Researcher, review date, source checks, changes from the prior version, evidence added or withdrawn, and the interpretation affected by each change."]
];
const rows=SEED.map(p=>{const slug=nodeSlug(p.name);const r=getCaseResearch(slug)!;return {p,slug,r,counts:countSources(r.sources)};});
export default function Page(){const saturated=rows.filter(x=>x.r.documentationLevel==="saturated");const provisional=rows.filter(x=>x.r.documentationLevel==="provisional");const totalSources=rows.reduce((n,x)=>n+x.counts.total,0);const totalIndependent=rows.reduce((n,x)=>n+x.counts.independent,0);return <main className="observatory-page"><p className="eyebrow">The Observatory · Documentation status</p><h1>See whether each claim can be traced to supporting evidence.</h1><p className="lede">The documentation standard is that a case's chronology, interpretation, dependencies, complications, and unknowns can each be traced to the evidence supporting the statement. This page shows how far each record has been built toward that standard; it does not certify any record as complete.</p><p><a href="/observatory">← The Observatory</a></p>
<section className={styles.summary}><article><strong>{saturated.length}</strong><span>Records organized as claim-level research records</span></article><article><strong>{provisional.length}</strong><span>Provisional records requiring full case research</span></article><article><strong>{REQUIREMENTS.length}</strong><span>Required documentation layers</span></article><article><strong>{totalSources}</strong><span>Sources across all cases, {totalIndependent} of them independent reporting</span></article></section>
<section className={styles.standard}><p className={styles.kicker}>The completion standard</p><h2>What each case must contain</h2><div className={styles.requirements}>{REQUIREMENTS.map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,"0")}</span><div><h3>{x[0]}</h3><p>{x[1]}</p></div></article>)}</div></section>
<section className={styles.status}><div><p className={styles.kicker}>Completed case records</p><h2>Organized as claim-level research records</h2><p>Each of these cases has a dated chronology, an interpretation, complications, and open questions, with sources attached to the chronology. The counts below come from the same source list shown on each case page. Independent reporting is counted separately from primary and institutional records, subject interviews, self-authored pieces, and republished reports. These records have not had an independent expert review, and private facts may still remain unknown.</p>{saturated.map(x=><Link key={x.slug} href={"/observatory/"+x.slug}><strong>{x.p.name}</strong><span>{x.counts.total} sources ({x.counts.independent} independent) · {x.r.chronology.length} sourced chronology events · {x.r.complication.length} complications · {x.r.unknowns.length} explicit unknowns</span></Link>)}</div>
<div><p className={styles.kicker}>Research queue</p><h2>{provisional.length ? "Provisional, not fully documented" : "No provisional records remain"}</h2><p>{provisional.length ? "These records are usable as research leads and browsing profiles. Their current milestone and structural summary do not yet have claim-level research records." : "Every case in the current collection has completed the claim-level migration. New cases enter here as provisional until they are organized the same way."}</p><div className={styles.queue}>{provisional.map(x=><Link key={x.slug} href={"/observatory/"+x.slug}><span>{x.p.name}</span><small>{x.p.domain}</small></Link>)}</div></div></section>
<aside className={styles.guardrail}><strong>What the documentation status means</strong><span>Documentation status describes how a record is built, not whether it has been independently verified. A record organized this way may still contain disputed claims, fewer sources than another case, and unknown private arrangements. The status means a reader can see what the sources establish, who made each claim, what conflicts with it, and what remains uncertain. It does not mean the claims have cleared verification review, and it is not a continuous check that the cited links still resolve.</span></aside></main>;}
