-- Neri Oxman 1.0.0 draft-only public-evidence review package.
-- No publication, verification, scoring, psychological inference, or saturation claim.

INSERT INTO "ObservatoryCase"
("id","slug","displayName","currentTitle","primaryOrganization","roleBuiltFlag","verificationStatus","publicStatus","createdAt","updatedAt")
VALUES
('obs_case_neri_oxman','neri-oxman','Neri Oxman','Founder','OXMAN',false,'unreviewed','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO UPDATE SET
"displayName"=EXCLUDED."displayName","currentTitle"=EXCLUDED."currentTitle","primaryOrganization"=EXCLUDED."primaryOrganization",
"roleBuiltFlag"=false,"verificationStatus"='unreviewed',"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP;

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_nox10_mit','https://www.media.mit.edu/people/neri/overview/','Neri Oxman overview','MIT Media Lab','primary_institutional_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_agua','https://www.media.mit.edu/projects/aguahoja-iii/overview/','Aguahoja III','MIT Media Lab','primary_project_record',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_flight','https://www.media.mit.edu/projects/maiden-flight/overview/','Maiden Flight','MIT Media Lab','primary_project_record',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_oxman','https://www.oxman.com/','OXMAN','OXMAN','primary_company_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_lab','https://oxman.com/projects/lab','OXMAN Lab','OXMAN','primary_project_record',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_kcc','https://jods.mitpress.mit.edu/pub/ageofentanglement','Age of Entanglement','MIT Press','scholarly_article','2016-01-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_moma','https://www.moma.org/calendar/exhibitions/5090','Neri Oxman: Material Ecology','MoMA','primary_museum_record','2020-05-14T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_pat','https://patents.google.com/patent/US20110079936A1/en','Methods and Apparatus for Variable Property Rapid Prototyping','USPTO / Google Patents','patent_record','2011-04-07T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_mitrep','https://facultygovernance.mit.edu/sites/default/files/20200121GoodwinProcterReport.pdf','Report Concerning Jeffrey Epstein Interactions with MIT','MIT / Goodwin Procter','institutional_investigation','2020-01-10T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_bi','https://www.businessinsider.com/neri-oxman-plagiarize-wikipedia-mit-dissertation-2024-1','Academic celebrity Neri Oxman plagiarized from Wikipedia and other sources','Business Insider','independent_investigative_reporting','2024-01-05T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_ap','https://apnews.com/article/c8d7817314772b1b5443f656d0e2ae74','Business Insider stands by Neri Oxman reports','Associated Press','independent_journalism','2024-01-14T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_nox10_fc','https://www.fastcompany.com/91259975/neri-oxmans-productive-frictions','Neri Oxman productive frictions','Fast Company','independent_profile','2025-01-16T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_nox10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'role_history','Oxman was an MIT professor and founded and directed the Mediated Matter research group.','formal_role','primary_record','unreviewed',NULL,'Founder and former director of MIT Mediated Matter.','No personal ownership of MIT, laboratory assets, grants, institutional IP or all group output.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_nox10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'distributed_labor','Mediated Matter projects identify researchers, collaborators, fabricators, funders and institutional partners.','distributed_creation','primary_record','unreviewed',NULL,'Oxman led a multidisciplinary research group.','No solitary invention, sole labor, sole authorship or sole impact.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_nox10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'framework_authorship','Oxman developed and published the Material Ecology and Krebs Cycle of Creativity frameworks.','creative_role','corroborated','unreviewed',NULL,'Developed or articulated the identified frameworks.','No ownership of a field, the biological Krebs cycle, all antecedents or related work.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_nox10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'company_role','Oxman founded and leads OXMAN, a New York design company with a multidisciplinary team.','formal_role','primary_record','unreviewed',NULL,'Founder and leader of OXMAN.','No sole labor, unilateral control, complete beneficial ownership or personal ownership of all company assets.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_nox10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'financing_boundary','Fast Company reported roughly $100 million invested in OXMAN by Oxman and Bill Ackman and described them as principal investors.','financial_boundary','attributed_report','unreviewed',NULL,'Fast Company reported approximately $100 million in family investment.','No audited cap table, personal wealth, ownership percentage, liquidity or unilateral control.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_nox10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'museum_record','MoMA presented a 2020 monographic exhibition with project-specific collaborative credits.','creative_role','primary_record','unreviewed',NULL,'Subject of MoMA 2020 Material Ecology exhibition.','No personal title to every object, museum asset, fabrication contribution, image right or value.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_nox10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'inventorship','Patent records identify Oxman as an inventor on specific filings with holder-specific assignee and co-inventor records.','ip_boundary','primary_record','unreviewed',NULL,'Named inventor on the identified patent family.','No sole invention, ownership of every patent, enforceability or IP-economics claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_nox10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'adverse_evidence','MIT documented a 2015 Epstein visit connected to research-funding efforts.','adverse_record','primary_record','unreviewed',NULL,'A documented and attributed funding-related interaction during her MIT tenure.','No undisclosed motive, criminal participation or psychological conclusion.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_nox10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'adverse_evidence','Business Insider reported citation and attribution failures; Oxman apologized for specified errors and the publisher stood by the reporting after review.','adverse_record','corroborated','unreviewed',NULL,'Documented allegations and an attributed apology concerning citation errors.','No expansion beyond reviewed examples, diagnosis, motive, wholesale invalidation or adjudicated-misconduct claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_nox10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'claim_restriction','No reviewed public record establishes OXMAN complete cap table, voting control, governance, compensation, MIT-to-OXMAN IP allocation, project rights, complete labor, audited environmental outcomes or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified or incomplete.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_nox10_c01','obs_claim_nox10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.media.mit.edu/people/neri/overview/' LIMIT 1),'supports',NULL,'Archived faculty biography','Institutional role boundary.',CURRENT_TIMESTAMP),
('obs_ev_nox10_c02','obs_claim_nox10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.media.mit.edu/projects/aguahoja-iii/overview/' LIMIT 1),'supports',NULL,'Credits and acknowledgements','Distributed labor preserved.',CURRENT_TIMESTAMP),
('obs_ev_nox10_c03','obs_claim_nox10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://jods.mitpress.mit.edu/pub/ageofentanglement' LIMIT 1),'supports',NULL,'Article body','Authorship and antecedents bounded.',CURRENT_TIMESTAMP),
('obs_ev_nox10_c04','obs_claim_nox10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://oxman.com/projects/lab' LIMIT 1),'supports',NULL,'Core team and project record','Company team preserved.',CURRENT_TIMESTAMP),
('obs_ev_nox10_c05','obs_claim_nox10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.fastcompany.com/91259975/neri-oxmans-productive-frictions' LIMIT 1),'supports',NULL,'Independent profile','Reported, unaudited company financing.',CURRENT_TIMESTAMP),
('obs_ev_nox10_c06','obs_claim_nox10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.moma.org/calendar/exhibitions/5090' LIMIT 1),'supports',NULL,'Exhibition and object credits','Rights remain work-specific.',CURRENT_TIMESTAMP),
('obs_ev_nox10_c07','obs_claim_nox10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://patents.google.com/patent/US20110079936A1/en' LIMIT 1),'supports',NULL,'Inventor and assignee record','Inventorship differs from ownership.',CURRENT_TIMESTAMP),
('obs_ev_nox10_c08','obs_claim_nox10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://facultygovernance.mit.edu/sites/default/files/20200121GoodwinProcterReport.pdf' LIMIT 1),'supports',NULL,'2015 chronology','Bounded adverse institutional record.',CURRENT_TIMESTAMP),
('obs_ev_nox10_c09','obs_claim_nox10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://apnews.com/article/c8d7817314772b1b5443f656d0e2ae74' LIMIT 1),'supports',NULL,'Publisher review and apology reporting','Attribution preserved.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_nox10_mit',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'organization','MIT Media Lab','former_professor','2010-01-01T00:00:00Z','2021-12-31T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.media.mit.edu/people/neri/overview/' LIMIT 1),NULL,'Time-bounded university role',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_nox10_mm',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'organization','Mediated Matter','founder_and_former_director','2010-01-01T00:00:00Z','2021-12-31T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.media.mit.edu/people/neri/overview/' LIMIT 1),NULL,'Team and institutional assets preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_nox10_mat',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'framework','Material Ecology','framework_developer','2006-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.moma.org/calendar/exhibitions/5090' LIMIT 1),NULL,'Conceptual leadership not field ownership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_nox10_press',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'organization','MIT Press / Journal of Design and Science','author','2016-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://jods.mitpress.mit.edu/pub/ageofentanglement' LIMIT 1),NULL,'Publisher and rights preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_nox10_oxman',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'organization','OXMAN','founder_and_leader','2019-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.oxman.com/' LIMIT 1),NULL,'Team, investors, governance and IP preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_nox10_moma',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'organization','Museum of Modern Art','exhibited_artist','2008-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.moma.org/calendar/exhibitions/5090' LIMIT 1),NULL,'Holdings and rights are work-specific',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_nox10_pat',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'ip_family','Variable Property Rapid Prototyping patent family','named_inventor','2009-10-05T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://patents.google.com/patent/US20110079936A1/en' LIMIT 1),NULL,'Assignee and inventorship boundaries preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_nox10_2010',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'institution_launch','Mediated Matter founded','Oxman founded the MIT research group within university governance.','2010-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.media.mit.edu/people/neri/overview/' LIMIT 1),NULL,'No personal lab ownership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_nox10_2016',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'publication','Krebs Cycle of Creativity published','MIT Press published Oxman authored framework.','2016-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://jods.mitpress.mit.edu/pub/ageofentanglement' LIMIT 1),NULL,'Antecedent frameworks preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_nox10_2020moma',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'exhibition','MoMA Material Ecology exhibition','MoMA presented a monographic exhibition with project-specific credits.','2020-05-14T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.moma.org/calendar/exhibitions/5090' LIMIT 1),NULL,'Collaborative rights preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_nox10_2020rep',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'adverse_record','MIT Epstein report released','MIT published its commissioned investigation recording the 2015 interaction.','2020-01-10T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://facultygovernance.mit.edu/sites/default/files/20200121GoodwinProcterReport.pdf' LIMIT 1),NULL,'Attributed institutional record only',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_nox10_2021',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'role_end','MIT role ends','Oxman former MIT and Mediated Matter roles ended by 2021.','2021-12-31T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.media.mit.edu/people/neri/overview/' LIMIT 1),NULL,'Endpoint precision remains year-level',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_nox10_2024a',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'adverse_record','Citation allegations and apology','Reporting identified attribution failures and Oxman apologized for specified errors.','2024-01-05T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://apnews.com/article/c8d7817314772b1b5443f656d0e2ae74' LIMIT 1),NULL,'Allegation and admission boundaries preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_nox10_2024b',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'company_launch','OXMAN studio publicly launches','OXMAN publicly launched its New York studio and partnerships.','2024-09-26T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.oxman.com/' LIMIT 1),NULL,'Company team and governance preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_neri_oxman_100','neri-oxman-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'1.0.0','research/observatory/dossiers/neri-oxman-1.0.0.md','f352b4e42a81ee3c2552eec6464dd27f499dc9e2',
'{"claimIds":["obs_claim_nox10_c01","obs_claim_nox10_c02","obs_claim_nox10_c03","obs_claim_nox10_c04","obs_claim_nox10_c05","obs_claim_nox10_c06","obs_claim_nox10_c07","obs_claim_nox10_c08","obs_claim_nox10_c09","obs_claim_nox10_c10"],"relationshipIds":["obs_rel_nox10_mit","obs_rel_nox10_mm","obs_rel_nox10_mat","obs_rel_nox10_press","obs_rel_nox10_oxman","obs_rel_nox10_moma","obs_rel_nox10_pat"],"eventIds":["obs_event_nox10_2010","obs_event_nox10_2016","obs_event_nox10_2020moma","obs_event_nox10_2020rep","obs_event_nox10_2021","obs_event_nox10_2024a","obs_event_nox10_2024b"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","distributed_creative_and_scientific_labor","institutional_governance","company_financing_not_personal_wealth","cap_table_unverified","ip_allocation_unverified","museum_and_media_rights_unverified","adverse_evidence_attributed","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.88,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_neri_oxman_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='neri-oxman' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_neri_oxman_100',
'{"packageId":"neri-oxman-1.0.0","claimsLoaded":10,"relationshipsLoaded":7,"eventsLoaded":7,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Institutional, creative, scientific, company, ownership, financing, IP, museum-rights, labor, adverse-evidence, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
