-- Peter Diamandis public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='XPRIZE founder and executive chairman with distinct nonprofit, company, fund and media relationships.',
    "summary"='A multi-entity founder portfolio separating nonprofit governance, co-founded companies, public-company directorships, venture funds, paid communities, institutional labor and adverse evidence.',
    "inclusionRationale"='Tests whether a prolific founder portfolio can be modeled without conflating founder status, ownership, control, fund economics, personal wealth, sole causality or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.86,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='peter-diamandis';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_pd10_xprofile','https://www.xprize.org/people/peter-h-diamandis-m-d','Peter H. Diamandis profile','XPRIZE','primary_nonprofit_profile',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_pd10_xceo','https://www.xprize.org/news/xprize-foundation-announces-new-ceo','XPRIZE announces Anousheh Ansari as CEO','XPRIZE','primary_nonprofit_announcement','2018-10-18T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_pd10_suhistory','https://www.su.org/about-us','About Singularity','Singularity','primary_company_history',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_pd10_sufunding','https://www.su.org/press/singularity-university-raises-32-million-in-series-b-funding-co-led-by-westriver-group-and-boeing','Singularity raises Series B and changes founder role','Singularity','primary_company_announcement','2018-02-15T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_pd10_celu10ka','https://www.sec.gov/Archives/edgar/data/1752828/000164117225011942/form10-ka.htm','Celularity 2024 Form 10-K/A','SEC / Celularity','primary_regulatory_filing','2025-05-21T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_pd10_vaxxs1','https://www.sec.gov/Archives/edgar/data/1851657/000119312521295612/d142511ds1.htm','Vaxxinity Form S-1','SEC / Vaxxinity','primary_regulatory_filing','2021-10-08T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_pd10_fountain','https://www.fountainlife.com/about','About Fountain Life','Fountain Life','primary_company_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_pd10_bold','https://boldcapitalpartners.com/team/peter-diamandis/','Peter Diamandis team profile','BOLD Capital Partners','primary_fund_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_pd10_hli','https://www.reuters.com/article/business/healthcare-pharmaceuticals/for-his-next-act-genome-wiz-craig-venter-takes-on-aging-idUSBREA231SC/','Craig Venter, Peter Diamandis and Robert Hariri form Human Longevity','Reuters','independent_journalism','2014-03-04T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_pd10_covid','https://www.washingtonpost.com/nation/2021/02/16/peter-diamandis-summit-coronavirus-outbreak/','Conference followed by reported coronavirus outbreak','Washington Post','independent_journalism','2021-02-16T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_pd10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'nonprofit_role','Diamandis founded XPRIZE and serves as executive chairman, while Anousheh Ansari has served as CEO since 2018.','formal_role','observed','unreviewed',NULL,'Founder and executive chairman of XPRIZE within separate executive governance.','XPRIZE is not established as a personally owned asset and executive chairman is not sole operating authority.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_pd10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'cofounding_history','Singularity was co-founded by Diamandis and Ray Kurzweil in 2008.','venture_history','observed','unreviewed',NULL,'Co-founder of Singularity.','No sole-founder, sole-authorship or current-control inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_pd10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'role_transition','Singularity announced in 2018 that Diamandis would become executive founder and remain on its board after a financing.','role_transition','observed','unreviewed',NULL,'His Singularity role changed within a separately financed institution.','A historic board role does not prove unchanged current control.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_pd10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'cofounding_history','Human Longevity was formed with co-founders J. Craig Venter and Robert Hariri.','venture_history','corroborated','unreviewed',NULL,'Co-founder of Human Longevity with Venter and Hariri.','No sole-creation, current-control or personal-value claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_pd10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'governance_role','Celularity filings document Diamandis as a predecessor co-founder and director within a multi-person board.','formal_governance','primary_filing','unreviewed',NULL,'Co-founder and director of Celularity.','Director status does not establish majority ownership, voting control or personal receipt of company value.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_pd10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'governance_role','Vaxxinity filings document a director role alongside CEO Mei Mei Hu and other directors.','formal_governance','primary_filing','unreviewed',NULL,'Held a formal Vaxxinity governance role.','No sole-control, product-authorship or personal-performance inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_pd10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'portfolio_boundary','Fountain Life and BOLD identify Diamandis as one of multiple founders or partners within separately led institutions.','distributed_portfolio','observed','unreviewed',NULL,'Co-founder or partner within Fountain Life and BOLD.','Fund size, company value and portfolio value are not personal wealth or proof of portfolio-company ownership.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_pd10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'adverse_event','Independent reporting tied the January 2021 Abundance360 gathering to at least 24 reported COVID-19 cases, and Diamandis acknowledged that the attempted safety approach failed.','adverse_event','attributed','unreviewed',NULL,'Reporting documents an outbreak and Diamandis’s public correction.','Do not convert the event into a psychological diagnosis or timeless trait.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_pd10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'claim_restriction','Portfolio counts, fund size, competition value, company valuation and induced research-and-development estimates are source-defined institutional metrics.','claim_restriction','observed','unreviewed',NULL,'Use aggregate metrics only with source, date and definition.','Do not convert them into personal ownership, income, wealth or sole impact.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_pd10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'claim_restriction','No reviewed record establishes a complete portfolio cap table, cross-entity contracts, personal economics, sole causal output or psychological measurements.','claim_restriction','observed','unreviewed',NULL,'Public evidence establishes bounded roles, not complete control, economics, causality or psychology.','Absence of public evidence is not proof that no private rights exist.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_pd10_c01','obs_claim_pd10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.xprize.org/news/xprize-foundation-announces-new-ceo' LIMIT 1),'supports',NULL,'CEO announcement','Separate CEO and executive-chair roles.',CURRENT_TIMESTAMP),
('obs_ev_pd10_c02','obs_claim_pd10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.su.org/about-us' LIMIT 1),'supports',NULL,'Founding history','Ray Kurzweil co-founder attribution.',CURRENT_TIMESTAMP),
('obs_ev_pd10_c03','obs_claim_pd10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.su.org/press/singularity-university-raises-32-million-in-series-b-funding-co-led-by-westriver-group-and-boeing' LIMIT 1),'supports',NULL,'Financing and leadership paragraphs','Historic role and board transition.',CURRENT_TIMESTAMP),
('obs_ev_pd10_c04','obs_claim_pd10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/article/business/healthcare-pharmaceuticals/for-his-next-act-genome-wiz-craig-venter-takes-on-aging-idUSBREA231SC/' LIMIT 1),'supports',NULL,'Company formation report','Three-person co-founding account.',CURRENT_TIMESTAMP),
('obs_ev_pd10_c05','obs_claim_pd10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1752828/000164117225011942/form10-ka.htm' LIMIT 1),'supports',NULL,'Director biography','Primary-filed role chronology.',CURRENT_TIMESTAMP),
('obs_ev_pd10_c06','obs_claim_pd10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1851657/000119312521295612/d142511ds1.htm' LIMIT 1),'supports',NULL,'Board and governance sections','Primary-filed director role.',CURRENT_TIMESTAMP),
('obs_ev_pd10_c07','obs_claim_pd10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.fountainlife.com/about' LIMIT 1),'supports',NULL,'Founding partners','Multiple founders and separate CEO.',CURRENT_TIMESTAMP),
('obs_ev_pd10_c08','obs_claim_pd10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.washingtonpost.com/nation/2021/02/16/peter-diamandis-summit-coronavirus-outbreak/' LIMIT 1),'supports',NULL,'Reported cases and acknowledgment','Attributed adverse event; no psychology inference.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_pd10_xprize',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'organization','XPRIZE Foundation','founder_executive_chairman','1994-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.xprize.org/people/peter-h-diamandis-m-d' LIMIT 1),NULL,'Nonprofit governance and separate CEO preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_pd10_ansari',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'person','Anousheh Ansari','xprize_ceo','2018-10-18T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.xprize.org/news/xprize-foundation-announces-new-ceo' LIMIT 1),NULL,'Separate operating leadership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_pd10_singularity',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'organization','Singularity','cofounder_executive_founder_history','2008-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.su.org/about-us' LIMIT 1),NULL,'Ownership and current board control unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_pd10_hli',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'organization','Human Longevity','cofounder','2014-03-04T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/article/business/healthcare-pharmaceuticals/for-his-next-act-genome-wiz-craig-venter-takes-on-aging-idUSBREA231SC/' LIMIT 1),NULL,'Venter and Hariri co-founder attribution preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_pd10_celularity',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'organization','Celularity','cofounder_director','2016-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1752828/000164117225011942/form10-ka.htm' LIMIT 1),NULL,'Multi-person board; equity and control not inferred',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_pd10_fountain',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'organization','Fountain Life','cofounder_founding_partner','2020-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.fountainlife.com/about' LIMIT 1),NULL,'Multiple founding partners and separate CEO',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_pd10_xprize',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'formation','XPRIZE founded','Diamandis founded the nonprofit prize institution.','1994-01-01T00:00:00Z','year_approximate','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.xprize.org/people/peter-h-diamandis-m-d' LIMIT 1),NULL,'Public launch followed later',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_pd10_singularity',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'formation','Singularity co-founded','Diamandis and Ray Kurzweil co-founded Singularity.','2008-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.su.org/about-us' LIMIT 1),NULL,'Co-founder boundary preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_pd10_hli',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'formation','Human Longevity launched','Diamandis, Venter and Hariri formed Human Longevity.','2014-03-04T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/article/business/healthcare-pharmaceuticals/for-his-next-act-genome-wiz-craig-venter-takes-on-aging-idUSBREA231SC/' LIMIT 1),NULL,'Three-person formation account',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_pd10_transitions',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'role_transition','XPRIZE and Singularity roles transition','Separate 2018 announcements documented an XPRIZE CEO appointment and Diamandis’s Singularity executive-founder role.','2018-10-18T00:00:00Z','year_composite','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.xprize.org/news/xprize-foundation-announces-new-ceo' LIMIT 1),NULL,'Two institutional transitions summarized',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_pd10_covid',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'adverse_event','Abundance360 COVID-19 outbreak reported','Independent reporting documented at least 24 cases and Diamandis’s acknowledgment that the attempted safety approach failed.','2021-01-26T00:00:00Z','event_end_approximate','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.washingtonpost.com/nation/2021/02/16/peter-diamandis-summit-coronavirus-outbreak/' LIMIT 1),NULL,'Attributed reporting; no psychological inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_peter_diamandis_100','peter-diamandis-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'1.0.0','research/observatory/dossiers/peter-diamandis-1.0.0.md','f3682ac5ca64c4ac474f4818be36524e4a40f729',
'{"claimIds":["obs_claim_pd10_c01","obs_claim_pd10_c02","obs_claim_pd10_c03","obs_claim_pd10_c04","obs_claim_pd10_c05","obs_claim_pd10_c06","obs_claim_pd10_c07","obs_claim_pd10_c08","obs_claim_pd10_c09","obs_claim_pd10_c10"],"relationshipIds":["obs_rel_pd10_xprize","obs_rel_pd10_ansari","obs_rel_pd10_singularity","obs_rel_pd10_hli","obs_rel_pd10_celularity","obs_rel_pd10_fountain"],"eventIds":["obs_event_pd10_xprize","obs_event_pd10_singularity","obs_event_pd10_hli","obs_event_pd10_transitions","obs_event_pd10_covid"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","multi_entity_portfolio","nonprofit_not_personal_asset","cofounders_preserved","director_not_control","fund_and_company_values_not_personal_economics","distributed_labor_incomplete","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.86,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_peter_diamandis_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='peter-diamandis' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_peter_diamandis_100',
'{"packageId":"peter-diamandis-1.0.0","claimsLoaded":10,"relationshipsLoaded":6,"eventsLoaded":5,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Entity, ownership, governance, fund economics, IP, labor, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
