-- Mo Gawdat public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, validate health claims, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Former Google X CBO, author, host and mission founder across distinct institutional and media relationships.',
    "summary"='A role-bounded portfolio separating former employment, books, podcasting, mission work, co-founded ventures, commercial services, AI forecasts, collaborators, platforms, rights and impact claims.',
    "inclusionRationale"='Tests whether a polymath public identity can be represented without conflating titles, entities, ownership, scientific authority, forecasts, media rights, impact, sole causality or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.84,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='mo-gawdat';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_mg10_site','https://www.mogawdat.com/','Mo Gawdat official site','Mo Gawdat','first_party_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_obh','https://onebillionhappy.org/','One Billion Happy','One Billion Happy','first_party_mission_site',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_pm_bio','https://www.panmacmillan.com/authors/mo-gawdat/21014','Mo Gawdat author biography','Pan Macmillan','publisher_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_sfh','https://www.panmacmillan.com/authors/mo-gawdat/solve-for-happy/9781509809950','Solve for Happy','Pan Macmillan','publisher_book_page','2019-01-10T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_scary','https://www.panmacmillan.com/authors/mo-gawdat/scary-smart/9781529077650','Scary Smart','Pan Macmillan','publisher_book_page','2022-12-08T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_voice','https://www.panmacmillan.com/authors/mo-gawdat/that-little-voice-in-your-head/9781529066173','That Little Voice in Your Head','Pan Macmillan','publisher_book_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_unstress','https://www.panmacmillan.com/authors/mo-gawdat/unstressable/9781035085705','Unstressable','Pan Macmillan','publisher_book_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_alive','https://www.panmacmillan.com/authors/mo-gawdat/alive/9781035093090','Alive','Pan Macmillan','publisher_book_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_itu','https://aiforgood.itu.int/speaker/mo-gawdat/','Mo Gawdat speaker biography','ITU AI for Good','institutional_event_biography',NULL,'2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_guardian','https://www.theguardian.com/technology/2017/apr/30/google-mo-gawdat-solve-for-happy-interview','Google’s Mo Gawdat: ‘Happiness is like keeping fit. You have to work out’','The Guardian','independent_journalism','2017-04-30T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_cnbc','https://www.cnbc.com/2018/08/24/former-google-x-exec-mo-gawdats-formula-for-happiness.html','This former Google X exec reverse engineered happiness','CNBC','independent_journalism','2018-08-24T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_bi26','https://www.businessinsider.com/ex-google-x-exec-mo-gawdat-ai-threatens-ceos-capitalism-2026-2','Mo Gawdat on AI, CEOs and capitalism','Business Insider','independent_journalism','2026-02-01T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_mg10_flight','https://www.flightstory.com/studio','Flight Story Studio','Flight Story','primary_company_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_mg10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'role_history','Gawdat is publicly documented as the former Chief Business Officer of Google X.','formal_role','corroborated','unreviewed',NULL,'Former Chief Business Officer of Google X.','No founder, owner, sole-commercializer, project-inventor or permanent-control claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mg10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'mission_formation','One Billion Happy is publicly framed as a mission or movement founded by Gawdat.','mission_formation','observed','unreviewed',NULL,'Founder of the One Billion Happy mission.','No legal-entity, funding, governance, reach, beneficiary or causal-impact claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mg10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'media_role','Gawdat is the named author of multiple books published through identified imprints.','distributed_media','primary_publisher_record','unreviewed',NULL,'Author of the named works.','No complete publishing, translation, audiobook, adaptation, derivative-rights or revenue claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mg10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'coauthorship','Unstressable is co-authored with Alice Law.','distributed_creation','primary_publisher_record','unreviewed',NULL,'Co-author with Alice Law.','No sole authorship, expertise, labor, ownership or economics claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mg10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'formation_history','Gawdat and Alice Law are publicly described as co-founders of Unstressable LLC.','distributed_creation','first_party_attributed','unreviewed',NULL,'Publicly described co-founder of Unstressable LLC.','No equal equity, equal control, complete cap table, revenue or efficacy claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mg10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'media_role','Institutional biographies identify Gawdat as host of Slo Mo, launched in 2020.','distributed_media','corroborated','unreviewed',NULL,'Host of Slo Mo.','No sole ownership of feed, masters, studio, distribution, advertising or derivative rights.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mg10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'current_role','Institutional and commercial biographies attribute a Chief AI Officer role at Flight Story to Gawdat.','formal_role','attributed','unreviewed',NULL,'Publicly described as Flight Story Chief AI Officer, subject to current-role review.','No ownership of Flight Story, its studio, shows, IP, staff or results.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mg10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'forecast','Gawdat has made dated public forecasts about AI, labor, capitalism and social disruption.','forecast_claim','attributed','unreviewed',NULL,'Gawdat predicted, argued or warned, with date and source.','Do not state forecasts as facts, consensus, measured outcomes or demonstrated predictive accuracy.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mg10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'health_claim_boundary','His books and programs present happiness, stress, neuroscience and psychology propositions.','health_claim_boundary','observed','unreviewed',NULL,'The named book or program presents the proposition.','No clinical validation, universal effect, diagnosis, treatment or scientific-consensus claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mg10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'claim_restriction','No reviewed public record establishes complete entity maps, cap tables, governance, contracts, IP, media rights, economics, audience rights, measured impact, predictive accuracy or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified or unmeasured.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_mg10_c01','obs_claim_mg10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/21014' LIMIT 1),'supports',NULL,'Author biography','Former institutional role; ownership excluded.',CURRENT_TIMESTAMP),
('obs_ev_mg10_c02','obs_claim_mg10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://onebillionhappy.org/' LIMIT 1),'supports',NULL,'Mission presentation','Legal identity and impact remain unresolved.',CURRENT_TIMESTAMP),
('obs_ev_mg10_c03','obs_claim_mg10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/21014' LIMIT 1),'supports',NULL,'Book catalogue','Author credit; contractual rights incomplete.',CURRENT_TIMESTAMP),
('obs_ev_mg10_c04','obs_claim_mg10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/unstressable/9781035085705' LIMIT 1),'supports',NULL,'Title and byline','Alice Law co-authorship preserved.',CURRENT_TIMESTAMP),
('obs_ev_mg10_c05','obs_claim_mg10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://onebillionhappy.org/' LIMIT 1),'supports',NULL,'Current first-party presentation','Equity, control and efficacy not inferred.',CURRENT_TIMESTAMP),
('obs_ev_mg10_c06','obs_claim_mg10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://aiforgood.itu.int/speaker/mo-gawdat/' LIMIT 1),'supports',NULL,'Institutional speaker biography','Host and launch attribution only.',CURRENT_TIMESTAMP),
('obs_ev_mg10_c07','obs_claim_mg10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://aiforgood.itu.int/speaker/mo-gawdat/' LIMIT 1),'supports',NULL,'Institutional speaker biography','Current role requires periodic confirmation.',CURRENT_TIMESTAMP),
('obs_ev_mg10_c08','obs_claim_mg10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.businessinsider.com/ex-google-x-exec-mo-gawdat-ai-threatens-ceos-capitalism-2026-2' LIMIT 1),'supports',NULL,'Dated interview','Forecasts and opinions, not outcomes.',CURRENT_TIMESTAMP),
('obs_ev_mg10_c09','obs_claim_mg10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/that-little-voice-in-your-head/9781529066173' LIMIT 1),'supports',NULL,'Publisher synopsis','No independent clinical validation.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_mg10_googlex',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'organization','Google X','former_chief_business_officer',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/21014' LIMIT 1),NULL,'Exact employment dates and authority unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mg10_obh',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'initiative','One Billion Happy','mission_founder','2017-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://onebillionhappy.org/' LIMIT 1),NULL,'Entity, governance, funding and impact incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mg10_panmac',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'organization','Pan Macmillan and imprints','author_publisher_relationship','2017-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/21014' LIMIT 1),NULL,'Contract and rights schedule not public',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mg10_alice',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'person','Alice Law','coauthor_and_attributed_cofounder','2024-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/unstressable/9781035085705' LIMIT 1),NULL,'Co-authorship preserved; equity and control unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mg10_slomo',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'media_property','Slo Mo','host','2020-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://aiforgood.itu.int/speaker/mo-gawdat/' LIMIT 1),NULL,'Production, distribution, advertising and IP incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mg10_flight',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'organization','Flight Story','attributed_chief_ai_officer',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://aiforgood.itu.int/speaker/mo-gawdat/' LIMIT 1),NULL,'Appointment and current status require primary confirmation',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_mg10_google',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'appointment','Gawdat joins Google','Published biographies place his Google start in 2007.','2007-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/21014' LIMIT 1),NULL,'Biography-level chronology',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_mg10_sfh',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'publication','Solve for Happy published','The book and associated mission entered public circulation.','2017-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/solve-for-happy/9781509809950' LIMIT 1),NULL,'Publication; impact not inferred',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_mg10_slomo',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'media_launch','Slo Mo launched','Institutional biography dates the podcast launch to 2020.','2020-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://aiforgood.itu.int/speaker/mo-gawdat/' LIMIT 1),NULL,'Host credit; ownership unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_mg10_scary',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'publication','Scary Smart published','AI theses and forecasts were published in book form.','2021-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/scary-smart/9781529077650' LIMIT 1),NULL,'Forecasts remain attributed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_mg10_unstress',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'publication','Unstressable published with Alice Law','The co-authored work was published.','2024-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.panmacmillan.com/authors/mo-gawdat/unstressable/9781035085705' LIMIT 1),NULL,'Co-authorship and health-claim boundary preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_mo_gawdat_100','mo-gawdat-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'1.0.0','research/observatory/dossiers/mo-gawdat-1.0.0.md','e1f75efde60abd13f266488c0c994a26b4653ddd',
'{"claimIds":["obs_claim_mg10_c01","obs_claim_mg10_c02","obs_claim_mg10_c03","obs_claim_mg10_c04","obs_claim_mg10_c05","obs_claim_mg10_c06","obs_claim_mg10_c07","obs_claim_mg10_c08","obs_claim_mg10_c09","obs_claim_mg10_c10"],"relationshipIds":["obs_rel_mg10_googlex","obs_rel_mg10_obh","obs_rel_mg10_panmac","obs_rel_mg10_alice","obs_rel_mg10_slomo","obs_rel_mg10_flight"],"eventIds":["obs_event_mg10_google","obs_event_mg10_sfh","obs_event_mg10_slomo","obs_event_mg10_scary","obs_event_mg10_unstress"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","multi_relationship_portfolio","former_title_not_ownership","mission_not_measured_impact","coauthor_and_collaborator_attribution","publishing_and_media_rights_incomplete","venture_cap_tables_unverified","ai_forecasts_attributed","health_claims_not_validated","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.84,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_mo_gawdat_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mo-gawdat' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_mo_gawdat_100',
'{"packageId":"mo-gawdat-1.0.0","claimsLoaded":10,"relationshipsLoaded":6,"eventsLoaded":5,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Entity, title, ownership, collaborator, publishing, media, health-claim, forecast, impact, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
