-- Jony Ive public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, attribute collective labor, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Design leader operating across distinct institutional, company, client and governance systems.',
    "summary"='A role-, entity-, rights- and time-bounded account separating Apple, LoveFrom, io, OpenAI, Ferrari, Exor, Airbnb, educational work and museum governance.',
    "inclusionRationale"='Tests Apple Chief Design Officer firstness without converting a company-specific title into worldwide firstness, personal role construction, sole invention, ownership, causal performance or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.89,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='jony-ive';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_jiv10_2012','https://www.apple.com/newsroom/2012/10/29Apple-Announces-Changes-to-Increase-Collaboration-Across-Hardware-Software-Services/','Apple Announces Changes to Increase Collaboration Across Hardware Software and Services','Apple','company_press_release','2012-10-29T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jiv10_leave','https://www.apple.com/newsroom/2019/06/jony-ive-to-form-independent-design-company-with-apple-as-client/','Jony Ive to form independent design company with Apple as client','Apple','company_press_release','2019-06-27T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jiv10_iphx','https://www.apple.com/newsroom/2017/09/the-future-is-here-iphone-x/','The future is here iPhone X','Apple','product_press_release','2017-09-12T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jiv10_oai','https://openai.com/sam-and-jony/','A letter from Sam and Jony','OpenAI','joint_institutional_statement','2025-07-09T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jiv10_exor','https://www.exor.com/press-releases/2021-09-27/exor-ferrari-and-lovefrom-announce-creative-partnership','Exor Ferrari and LoveFrom announce creative partnership','Exor and Ferrari','joint_press_release','2021-09-27T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jiv10_bm','https://www.britishmuseum.org/about-us/governance','British Museum governance','British Museum','governance_record',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jiv10_bmar','https://www.britishmuseum.org/sites/default/files/2026-07/Annual_Report_and_Accounts_2025-26.pdf','British Museum Annual Report and Accounts 2025-26','British Museum','annual_report','2026-07-14T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jiv10_air','https://www.airbnb.com/resources/hosting-homes/a/a-letter-from-brian-chesky-292','A letter from Brian Chesky','Airbnb','founder_letter','2020-10-21T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jiv10_time','https://time.com/3895749/apple-jonathan-ive-tim-cook/','Apple design chief gets a promotion','Time','contemporaneous_reporting','2015-05-26T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_jiv10_ft','https://www.ft.com/content/8ac40343-2fd1-4035-9664-47c77017d0d3','OpenAI to buy Jony Ive io in hardware push','Financial Times','transaction_reporting','2025-05-21T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_jiv10_guard','https://www.theguardian.com/technology/2025/jun/23/openai-jony-ive-io-amid-trademark-iyo','OpenAI takes down mentions of Jony Ive io amid trademark row','Guardian','litigation_reporting','2025-06-23T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_jiv10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'formal_role','Apple identified Ive as leader of Industrial Design and assigned Human Interface leadership in 2012.','formal_role','primary_record','unreviewed',NULL,'Led major Apple design functions.','No sole product authorship or unilateral company control.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jiv10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'title_firstness','Apple identified Ive as Chief Design Officer in 2019; contemporaneous reporting dates the Apple title to 2015.','role_origin','bounded_inference','unreviewed',NULL,'Apple first documented Chief Design Officer.','No worldwide-first or personal role-authorship claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jiv10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'role_endpoint','Apple announced Ive would cease being an employee later in 2019 and form an independent design company.','time_bounded_authority','primary_record','unreviewed',NULL,'Left Apple employment in 2019 to form LoveFrom.','No current Apple authority.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jiv10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'distributed_labor','Apple named Evans Hankey, Alan Dye, Jeff Williams and a multidisciplinary design team in the transition.','distributed_creation','primary_record','unreviewed',NULL,'Led and worked within an institutional design organization.','No solitary-genius or complete-labor claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jiv10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'client_relationship','Exor and Ferrari announced a multi-year collaboration with Ive and Marc Newson at LoveFrom.','shared_authority','primary_record','unreviewed',NULL,'LoveFrom co-led a Ferrari and Exor collaboration.','No sole credit, client ownership or undisclosed economics.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jiv10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'merger_boundary','OpenAI states io team merged into OpenAI while Ive and LoveFrom remained independent.','entity_boundary','primary_record','unreviewed',NULL,'Ive and independent LoveFrom hold design responsibilities across OpenAI.','No OpenAI ownership, employment or sole product control.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jiv10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'distributed_labor','OpenAI describes multidisciplinary engineering, scientific, research and manufacturing labor.','distributed_creation','primary_record','unreviewed',NULL,'Works through a multidisciplinary product-development network.','No sole invention or sole causation.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jiv10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'economic_boundary','Reported io transaction values do not establish Ive personal ownership, proceeds or wealth.','economic_attribution','reported','unreviewed',NULL,'io was reportedly acquired in a multibillion-dollar transaction.','No personal proceeds or wealth inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jiv10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'adverse_evidence','Secondary reporting records a trademark dispute concerning the io name and temporary content removal.','adverse_evidence','reported','unreviewed',NULL,'The io name became subject to a reported trademark dispute.','No final liability or merger-invalidity inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jiv10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'claim_restriction','No reviewed record establishes complete LoveFrom ownership, io cap table or proceeds, title authorship, patent economics, contracts, product causality or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_jiv10_c01','obs_claim_jiv10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.apple.com/newsroom/2012/10/29Apple-Announces-Changes-to-Increase-Collaboration-Across-Hardware-Software-Services/' LIMIT 1),'supports',NULL,'Executive changes','Function leadership.',CURRENT_TIMESTAMP),
('obs_ev_jiv10_c02','obs_claim_jiv10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.apple.com/newsroom/2019/06/jony-ive-to-form-independent-design-company-with-apple-as-client/' LIMIT 1),'supports',NULL,'Opening announcement','Apple-specific title.',CURRENT_TIMESTAMP),
('obs_ev_jiv10_c03','obs_claim_jiv10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.apple.com/newsroom/2019/06/jony-ive-to-form-independent-design-company-with-apple-as-client/' LIMIT 1),'supports',NULL,'Opening announcement','Employee endpoint announced.',CURRENT_TIMESTAMP),
('obs_ev_jiv10_c04','obs_claim_jiv10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.apple.com/newsroom/2019/06/jony-ive-to-form-independent-design-company-with-apple-as-client/' LIMIT 1),'supports',NULL,'Leadership transition','Named collaborators and team.',CURRENT_TIMESTAMP),
('obs_ev_jiv10_c05','obs_claim_jiv10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.exor.com/press-releases/2021-09-27/exor-ferrari-and-lovefrom-announce-creative-partnership' LIMIT 1),'supports',NULL,'Partnership announcement','Multi-party relationship.',CURRENT_TIMESTAMP),
('obs_ev_jiv10_c06','obs_claim_jiv10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://openai.com/sam-and-jony/' LIMIT 1),'supports',NULL,'July 2025 update','Merger and independence boundary.',CURRENT_TIMESTAMP),
('obs_ev_jiv10_c07','obs_claim_jiv10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://openai.com/sam-and-jony/' LIMIT 1),'supports',NULL,'Team description','Distributed labor.',CURRENT_TIMESTAMP),
('obs_ev_jiv10_c08','obs_claim_jiv10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.ft.com/content/8ac40343-2fd1-4035-9664-47c77017d0d3' LIMIT 1),'supports',NULL,'Transaction reporting','Reported company value only.',CURRENT_TIMESTAMP),
('obs_ev_jiv10_c09','obs_claim_jiv10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.theguardian.com/technology/2025/jun/23/openai-jony-ive-io-amid-trademark-iyo' LIMIT 1),'supports',NULL,'Trademark reporting','Adverse evidence bounded.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_jiv10_apple',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'organization','Apple','former_design_leader_and_chief_design_officer','1992-01-01T00:00:00Z','2019-12-31T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.apple.com/newsroom/2019/06/jony-ive-to-form-independent-design-company-with-apple-as-client/' LIMIT 1),NULL,'Exact endpoint and later consulting term require contract records',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jiv10_love',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'company','LoveFrom','founder_and_design_leader','2019-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.apple.com/newsroom/2019/06/jony-ive-to-form-independent-design-company-with-apple-as-client/' LIMIT 1),NULL,'Ownership governance staff clients contracts and IP unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jiv10_io',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'company','io Products','reported_cofounder_and_design_leader','2024-01-01T00:00:00Z','2025-07-09T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://openai.com/sam-and-jony/' LIMIT 1),NULL,'Team merged; cap table proceeds and IP unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jiv10_oai',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'organization','OpenAI','independent_design_and_creative_responsibility',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://openai.com/sam-and-jony/' LIMIT 1),NULL,'LoveFrom remains independent; OpenAI governance and teams preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jiv10_exor',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'client_relationship','Ferrari and Exor','multi_year_creative_collaborator','2021-09-27T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.exor.com/press-releases/2021-09-27/exor-ferrari-and-lovefrom-announce-creative-partnership' LIMIT 1),NULL,'Marc Newson client entities labor rights and economics preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jiv10_air',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'client_relationship','Airbnb','design_collaborator_through_lovefrom','2020-10-21T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.airbnb.com/resources/hosting-homes/a/a-letter-from-brian-chesky-292' LIMIT 1),NULL,'Airbnb entity leadership platform and workforce preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jiv10_bm',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'organization','British Museum','trustee','2025-06-10T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.britishmuseum.org/sites/default/files/2026-07/Annual_Report_and_Accounts_2025-26.pdf' LIMIT 1),NULL,'Multi-person statutory governance; no ownership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_jiv10_1992',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'employment','Apple career begins approximately','Apple later described nearly thirty years of work.','1992-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.apple.com/newsroom/2019/06/jony-ive-to-form-independent-design-company-with-apple-as-client/' LIMIT 1),NULL,'Exact personnel date unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_jiv10_2012',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'role_expansion','Human Interface leadership added','Apple added Human Interface direction to Industrial Design leadership.','2012-10-29T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.apple.com/newsroom/2012/10/29Apple-Announces-Changes-to-Increase-Collaboration-Across-Hardware-Software-Services/' LIMIT 1),NULL,'Institutional role expansion',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_jiv10_2015',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'appointment','Apple Chief Design Officer title takes effect','Contemporaneous reporting dates the newly established title.','2015-07-01T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://time.com/3895749/apple-jonathan-ive-tim-cook/' LIMIT 1),NULL,'Secondary reporting; role-design instrument unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_jiv10_2019',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'departure_announcement','Apple announces employee departure','Apple announced a future 2019 departure and independent company.','2019-06-27T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.apple.com/newsroom/2019/06/jony-ive-to-form-independent-design-company-with-apple-as-client/' LIMIT 1),NULL,'Announcement date not exact employment endpoint',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_jiv10_2021',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'partnership','Ferrari Exor LoveFrom partnership announced','Multi-year creative collaboration names Ive and Marc Newson.','2021-09-27T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.exor.com/press-releases/2021-09-27/exor-ferrari-and-lovefrom-announce-creative-partnership' LIMIT 1),NULL,'Multi-party relationship',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_jiv10_2025',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'merger','io team merger completed','OpenAI states io team merged while Ive and LoveFrom remained independent.','2025-07-09T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://openai.com/sam-and-jony/' LIMIT 1),NULL,'Transaction economics and internal authority unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_jony_ive_100','jony-ive-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'1.0.0','research/observatory/dossiers/jony-ive-1.0.0.md','faeccf3655695dc269e4770ac6311cd2754ba577',
'{"claimIds":["obs_claim_jiv10_c01","obs_claim_jiv10_c02","obs_claim_jiv10_c03","obs_claim_jiv10_c04","obs_claim_jiv10_c05","obs_claim_jiv10_c06","obs_claim_jiv10_c07","obs_claim_jiv10_c08","obs_claim_jiv10_c09","obs_claim_jiv10_c10"],"relationshipIds":["obs_rel_jiv10_apple","obs_rel_jiv10_love","obs_rel_jiv10_io","obs_rel_jiv10_oai","obs_rel_jiv10_exor","obs_rel_jiv10_air","obs_rel_jiv10_bm"],"eventIds":["obs_event_jiv10_1992","obs_event_jiv10_2012","obs_event_jiv10_2015","obs_event_jiv10_2019","obs_event_jiv10_2021","obs_event_jiv10_2025"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","apple_specific_firstness_only","title_authorship_unverified","distributed_institutional_labor","lovefrom_and_io_ownership_unverified","transaction_proceeds_unverified","ip_and_contracts_unverified","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.89,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_jony_ive_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='jony-ive' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_jony_ive_100',
'{"packageId":"jony-ive-1.0.0","claimsLoaded":10,"relationshipsLoaded":7,"eventsLoaded":6,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Apple-specific firstness, role authorship, distributed labor, ownership, transaction value, IP, contracts, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
