-- Marc Pritchard public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, attribute collective labor, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='P&G chief brand executive operating within a public company, brand teams, agencies, platforms and industry boards.',
    "summary"='A role-, entity-, brand-, rights- and time-bounded account separating executive authority from ownership, distributed creation, industry governance and corporate outcomes.',
    "inclusionRationale"='Tests visible chief-brand leadership without converting long tenure, strategy responsibility or public frameworks into personal role construction, ownership, sole authorship, causal performance or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.88,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='marc-pritchard';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_mar10_bio','https://us.pg.com/leadership-team/marc-pritchard/','Marc Pritchard','Procter & Gamble','official_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mar10_leaders','https://us.pg.com/leadership-team/','P&G leadership team','Procter & Gamble','leadership_roster',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mar10_10k','https://www.sec.gov/Archives/edgar/data/80424/000008042425000076/pg-20250630.htm','P&G 2025 Form 10-K','Procter & Gamble','regulatory_filing','2025-08-04T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mar10_portfolio','https://us.pg.com/annualreport2025/portfolio-daily-use-where-performance-drives-brand-choice/','A Portfolio of Daily-Use Categories','Procter & Gamble','annual_report_page','2025-08-04T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mar10_awards','https://us.pg.com/blogs/best-of-brand-awards/','2024 P&G Best of Brand Awards','Procter & Gamble','institutional_article','2024-12-16T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mar10_ai','https://us.pg.com/blogs/cannes-lions-international-festival-of-creativity/','Robots Do Not Build Brands People Do','Procter & Gamble','institutional_article','2026-07-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mar10_ana','https://www.ana.net/content/show/id/board','ANA Officers and Board of Directors','Association of National Advertisers','governance_roster',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mar10_ana2017','https://www.ana.net/conference/show/id/MLC-MAR17','2017 ANA Media Conference','Association of National Advertisers','conference_record','2017-03-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_mar10_spend','https://www.reuters.com/article/business/pg-says-cut-digital-ad-spend-by-200-million-in-2017-idUSKCN1GD653/','P&G says it cut digital ad spend in 2017','Reuters','news_reporting','2018-03-01T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_mar10_olympics','https://www.reuters.com/business/retail-consumer/pg-plans-downplay-its-corporate-name-ads-during-paris-olympics-2024-05-14/','P&G plans to downplay corporate name in Paris Olympics ads','Reuters','news_reporting','2024-05-14T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_mar10_vital','https://www.vitalvoices.org/team/marc-pritchard/','Marc Pritchard','Vital Voices','board_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_mar10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'formal_role','P&G currently identifies Pritchard as Chief Brand Officer responsible for worldwide brand-building disciplines and company media marketing and advertising strategies.','formal_role','primary_record','unreviewed',NULL,'Chief Brand Officer of P&G.','No personal ownership unlimited authority or control beyond the corporate office.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mar10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'role_chronology','Pritchard joined P&G in 1982 moved into marketing in 1987 and was appointed chief marketing officer in 2008.','time_bounded_authority','primary_record','unreviewed',NULL,'Built a long internal P&G career across finance brands business leadership and marketing.','No proof he created P&G marketing or the later Chief Brand Officer role.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mar10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'entity_boundary','P&G operates through a board executive officers business units functions subsidiaries and a large workforce.','entity_boundary','primary_record','unreviewed',NULL,'Exercises senior authority inside a distributed public company.','No personally owned portfolio or sole operating credit.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mar10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'rights_boundary','P&G or its subsidiaries hold the referenced brand trademarks while other names belong to their respective owners.','ownership_boundary','primary_record','unreviewed',NULL,'Leads brand building for a company-owned or licensed portfolio.','No personal ownership of brands marks campaigns data or IP.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mar10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'distributed_labor','P&G brand work is attributed across business leaders brand teams agencies platforms creators retailers and other partners.','distributed_creation','primary_and_reported','unreviewed',NULL,'Leads within a multi-party brand-building system.','No sole authorship or complete labor attribution.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mar10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'industry_advocacy','Pritchard advocated digital-media transparency and P&G reduced certain digital spending in 2017.','institutional_influence','reported_and_attributed','unreviewed',NULL,'Was a prominent advocate for media-supply-chain reform.','No proof he alone caused industry reform savings or later performance.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mar10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'strategy_change','P&G changed its Olympics advertising emphasis in 2024 toward individual product brands.','time_bounded_strategy','reported_and_attributed','unreviewed',NULL,'Described a company strategy shift toward product brands.','No personal ownership of strategy Olympic rights budgets or outcomes.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mar10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'governance_chronology','Current ANA records list Pritchard as a director while earlier records identify him as board chair.','governance_boundary','primary_record','unreviewed',NULL,'Former ANA chair and current ANA director.','No current-chair claim or unilateral authority over ANA.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mar10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'attributed_frameworks','Pritchard publicly advances brand-building propositions involving growth social good multicultural marketing creativity human insight and AI-assisted work.','public_proposition','attributed_statement','unreviewed',NULL,'Publicly advances these brand-building propositions.','No universal validity sole authorship measured impact or psychological inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_mar10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'claim_restriction','No reviewed record establishes title authorship complete authority current compensation beneficial ownership campaign or framework IP audited individual impact causality or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_mar10_c01','obs_claim_mar10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/leadership-team/marc-pritchard/' LIMIT 1),'supports',NULL,'Official biography','Current title and remit.',CURRENT_TIMESTAMP),
('obs_ev_mar10_c02','obs_claim_mar10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/leadership-team/marc-pritchard/' LIMIT 1),'supports',NULL,'Official biography','Historic chronology.',CURRENT_TIMESTAMP),
('obs_ev_mar10_c03','obs_claim_mar10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/80424/000008042425000076/pg-20250630.htm' LIMIT 1),'supports',NULL,'Form 10-K','Corporate and workforce boundary.',CURRENT_TIMESTAMP),
('obs_ev_mar10_c04','obs_claim_mar10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/annualreport2025/portfolio-daily-use-where-performance-drives-brand-choice/' LIMIT 1),'supports',NULL,'Annual report','Trademark-holder boundary.',CURRENT_TIMESTAMP),
('obs_ev_mar10_c05','obs_claim_mar10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/blogs/best-of-brand-awards/' LIMIT 1),'supports',NULL,'Institutional article','Separate teams and leaders.',CURRENT_TIMESTAMP),
('obs_ev_mar10_c06','obs_claim_mar10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/article/business/pg-says-cut-digital-ad-spend-by-200-million-in-2017-idUSKCN1GD653/' LIMIT 1),'supports',NULL,'Reuters report','Company action and attributed rationale.',CURRENT_TIMESTAMP),
('obs_ev_mar10_c07','obs_claim_mar10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/retail-consumer/pg-plans-downplay-its-corporate-name-ads-during-paris-olympics-2024-05-14/' LIMIT 1),'supports',NULL,'Reuters report','Bounded strategy shift.',CURRENT_TIMESTAMP),
('obs_ev_mar10_c08','obs_claim_mar10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.ana.net/content/show/id/board' LIMIT 1),'supports',NULL,'Current board roster','Current director status.',CURRENT_TIMESTAMP),
('obs_ev_mar10_c09','obs_claim_mar10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/blogs/cannes-lions-international-festival-of-creativity/' LIMIT 1),'supports',NULL,'Institutional article','Attributed AI and human-insight proposition.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_mar10_pg',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'organization','The Procter & Gamble Company','employee_and_current_chief_brand_officer','1982-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/leadership-team/marc-pritchard/' LIMIT 1),NULL,'Board CEO executives shareholders capital workforce brands data and IP preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mar10_teams',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'institutional_network','P&G business units and brand teams','executive_brand_building_oversight',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/blogs/best-of-brand-awards/' LIMIT 1),NULL,'Business leaders managers researchers designers sales and regional teams preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mar10_agencies',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'partner_network','Agencies creators and production partners','client_commissioning_and_collaboration_network',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/blogs/cannes-lions-international-festival-of-creativity/' LIMIT 1),NULL,'Contracts creative authorship production labor rights and results remain holder-specific',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mar10_platforms',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'platform_network','Media and technology platforms','advertiser_standards_and_commercial_relationship',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/article/business/pg-says-cut-digital-ad-spend-by-200-million-in-2017-idUSKCN1GD653/' LIMIT 1),NULL,'Platform ownership algorithms inventory measurement and outcomes preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mar10_ana',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'association','Association of National Advertisers','former_chair_and_current_director',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.ana.net/content/show/id/board' LIMIT 1),NULL,'Officers board staff members standards and programs separately governed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mar10_cannes',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'industry_institution','Cannes Lions and advertising industry institutions','speaker_participant_and_honoree_relationship',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/blogs/cannes-lions-international-festival-of-creativity/' LIMIT 1),NULL,'Festival juries entrants awards stages recordings and rights preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_mar10_vital',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'nonprofit','Vital Voices','board_director',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.vitalvoices.org/team/marc-pritchard/' LIMIT 1),NULL,'Board staff donors programs beneficiaries assets and impact preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_mar10_1982',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'employment','P&G employment begins','Pritchard joined P&G as a cost analyst in the Paper Division.','1982-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/leadership-team/marc-pritchard/' LIMIT 1),NULL,'Employment terms unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_mar10_1987',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'role_change','Move into marketing','Pritchard moved into marketing on the Sure brand.','1987-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/leadership-team/marc-pritchard/' LIMIT 1),NULL,'Brand team and company ownership preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_mar10_2008',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'appointment','Chief marketing appointment','Pritchard was appointed P&G chief marketing officer.','2008-08-01T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/leadership-team/marc-pritchard/' LIMIT 1),NULL,'No title-authorship or worldwide-first inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_mar10_2014',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'role_change','Chief Brand Officer period documented','Public chronology identifies the Chief Brand Officer title by 2014.','2014-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/leadership-team/marc-pritchard/' LIMIT 1),NULL,'Appointment instrument and role design unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_mar10_2017',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'industry_advocacy','Media transparency campaign and spending changes','Pritchard advocated supply-chain reform and P&G reduced certain digital advertising spending.','2017-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/article/business/pg-says-cut-digital-ad-spend-by-200-million-in-2017-idUSKCN1GD653/' LIMIT 1),NULL,'Savings and causal performance not independently allocated',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_mar10_2024',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'strategy_change','Olympics advertising emphasis changed','P&G described greater emphasis on individual brands for the Paris Olympics.','2024-05-14T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/retail-consumer/pg-plans-downplay-its-corporate-name-ads-during-paris-olympics-2024-05-14/' LIMIT 1),NULL,'Company strategy budgets rights and outcomes preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_mar10_2026',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'public_framework','Human insight and AI framework presented','Pritchard presented P&G human-insight and AI-assisted brand-building propositions at Cannes Lions.','2026-06-23T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://us.pg.com/blogs/cannes-lions-international-festival-of-creativity/' LIMIT 1),NULL,'Attributed propositions effectiveness unverified',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_marc_pritchard_100','marc-pritchard-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'1.0.0','research/observatory/dossiers/marc-pritchard-1.0.0.md','2b4b9af4ce1dbde1eb5e038480a4670e2b5331e7',
'{"claimIds":["obs_claim_mar10_c01","obs_claim_mar10_c02","obs_claim_mar10_c03","obs_claim_mar10_c04","obs_claim_mar10_c05","obs_claim_mar10_c06","obs_claim_mar10_c07","obs_claim_mar10_c08","obs_claim_mar10_c09","obs_claim_mar10_c10"],"relationshipIds":["obs_rel_mar10_pg","obs_rel_mar10_teams","obs_rel_mar10_agencies","obs_rel_mar10_platforms","obs_rel_mar10_ana","obs_rel_mar10_cannes","obs_rel_mar10_vital"],"eventIds":["obs_event_mar10_1982","obs_event_mar10_1987","obs_event_mar10_2008","obs_event_mar10_2014","obs_event_mar10_2017","obs_event_mar10_2024","obs_event_mar10_2026"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","current_title_is_pg_chief_brand_officer","title_authorship_unverified","pg_ownership_boundary","distributed_brand_agency_and_platform_labor","former_ana_chair_current_director","corporate_spend_and_results_not_personal_economics","frameworks_are_attributed_propositions","ip_contracts_and_economics_unverified","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.88,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_marc_pritchard_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='marc-pritchard' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_marc_pritchard_100',
'{"packageId":"marc-pritchard-1.0.0","claimsLoaded":10,"relationshipsLoaded":7,"eventsLoaded":7,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Current title, P&G ownership, distributed brand and agency labor, historic ANA chair endpoint, corporate economics, IP, contracts, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
