-- Darren Murph public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, attribute collective labor, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Remote-work codifier operating across pre-existing institutional systems and later advisory roles.',
    "summary"='A role-, time- and rights-bounded account separating GitLab, its pre-existing all-remote model, handbook and workforce, Engadget, Guinness, Andela, reported Ford work, books, consulting and speaking.',
    "inclusionRationale"='Tests a Head of Remote role-building claim without converting a new title into worldwide firstness, sole invention, ownership, sole labor, causal performance or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.88,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='darren-murph';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_dmu10_report','https://about.gitlab.com/press/releases/2021-02-09-gitlab-announces-new-remote-work-report/','GitLab Announces New Report on Remote Work','GitLab','company_press_release','2021-02-09T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_play','https://about.gitlab.com/press/releases/2021-04-20-all-remote-playbook/','GitLab Remote Work Playbook Provides Blueprint','GitLab','company_press_release','2021-04-20T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_master','https://about.gitlab.com/blog/mastering-the-all-remote-environment/','Mastering the all-remote environment','GitLab','company_staff_article','2019-12-30T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_prod','https://about.gitlab.com/blog/how-to-build-a-more-productive-remote-team/','5 Ways to build a more productive remote team','GitLab','authored_company_article','2019-12-10T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_hand','https://handbook.gitlab.com/handbook/company/culture/all-remote/','GitLab all-remote handbook','GitLab','public_handbook',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_dep','https://www.linkedin.com/posts/darrenmurph_gitlab-allremote-remote-activity-7025874520297115648-nTvh','GitLab departure statement','Darren Murph','first_person_statement','2023-01-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_gwr','https://www.guinnessworldrecords.com/world-records/most-prolific-professional-blogger','Most prolific professional blogger','Guinness World Records','record_page','2010-07-29T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_and','https://hire.andela.com/rs/449-UCH-555/images/DecodingDistributedWork.pdf?version=0','Decoding Distributed Work','Andela','company_white_paper','2023-01-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_pub','https://www.simonandschuster.com/authors/Darren-Murph/263361277','Darren Murph author page','Simon & Schuster','publisher_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_site','https://darrenmurph.com/','Darren Murph official site','Darren Murph','personal_site',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_work','https://www.worklife.news/leadership/youre-never-putting-this-remote-genie-back-in-the-bottle-how-gitlabs-head-of-remote-darren-murph-spends-his-day/','How GitLab Head of Remote spends his day','WorkLife','interview','2020-10-05T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_ford','https://runningremote.com/speaker/darren-murph/','Darren Murph speaker biography','Running Remote','event_biography',NULL,'2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_rr','https://runningremote.com/darren-murph-head-of-remote-gitlab/','Darren Murph Head of Remote GitLab','Running Remote','interview',NULL,'2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_dmu10_fee','https://www.allamericanspeakers.com/speakers/444003/Darren-Murph','Darren Murph speaker booking page','All American Speakers','booking_page','2025-12-19T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_dmu10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'formal_role','GitLab publicly identified Murph as Head of Remote.','formal_role','primary_record','unreviewed',NULL,'Former GitLab Head of Remote.','No worldwide-first claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_dmu10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'role_novelty','Murph described the title as a new role created during his tenure.','role_origin','attributed','unreviewed',NULL,'Held a newly formalized GitLab role.','No proof he designed, negotiated or uniquely originated it.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_dmu10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'preexisting_system','GitLab states it had been all-remote since 2014, before Murph held the role.','role_origin','primary_record','unreviewed',NULL,'Joined an established all-remote company.','No claim that remote operations began with him.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_dmu10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'distributed_labor','GitLab remote practice depended on a public handbook, executives, managers, teams and workforce.','distributed_creation','primary_record','unreviewed',NULL,'Helped codify and communicate an institutional model.','No sole authorship or labor.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_dmu10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'institutional_publication','GitLab published a Remote Playbook associated with Murph and derived from its handbook.','institutional_output','primary_record','unreviewed',NULL,'Authored or led the Remote Playbook within GitLab.','No personal ownership of company content, data or rights.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_dmu10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'role_endpoint','Murph announced departure after a self-reported 3.5-year GitLab tenure.','time_bounded_authority','attributed','unreviewed',NULL,'Former GitLab remote-work leader.','No current GitLab authority.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_dmu10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'later_role','Andela identified Murph as VP, Workplace Design and Remote Experience.','formal_role','primary_record','unreviewed',NULL,'Later held an Andela workplace-design role.','No ownership or sole outcome attribution.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_dmu10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'publication_record','Guinness records 17,212 contracted Engadget posts as of July 29, 2010.','documented_output','primary_record','unreviewed',NULL,'Guinness record holder for most prolific professional blogger.','No ownership of Engadget content or claim that count is current.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_dmu10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'institutional_outcome_boundary','GitLab growth and IPO were institutional outcomes involving executives, employees, investors and market conditions.','causal_attribution','observed','unreviewed',NULL,'Contributed during GitLab growth and IPO period.','No sole causation or personal transaction value.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_dmu10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'claim_restriction','No reviewed record establishes complete role-design history, beneficial ownership, compensation, handbook IP, media rights, client contracts, causal performance or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_dmu10_c01','obs_claim_dmu10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://about.gitlab.com/press/releases/2021-02-09-gitlab-announces-new-remote-work-report/' LIMIT 1),'supports',NULL,'Press release','Company-specific title.',CURRENT_TIMESTAMP),
('obs_ev_dmu10_c02','obs_claim_dmu10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.linkedin.com/posts/darrenmurph_gitlab-allremote-remote-activity-7025874520297115648-nTvh' LIMIT 1),'supports',NULL,'Departure statement','Self-attributed role novelty.',CURRENT_TIMESTAMP),
('obs_ev_dmu10_c03','obs_claim_dmu10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://about.gitlab.com/press/releases/2021-02-09-gitlab-announces-new-remote-work-report/' LIMIT 1),'supports',NULL,'About GitLab','All-remote since 2014.',CURRENT_TIMESTAMP),
('obs_ev_dmu10_c04','obs_claim_dmu10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://handbook.gitlab.com/handbook/company/culture/all-remote/' LIMIT 1),'supports',NULL,'Public handbook','Distributed institutional system.',CURRENT_TIMESTAMP),
('obs_ev_dmu10_c05','obs_claim_dmu10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://about.gitlab.com/press/releases/2021-04-20-all-remote-playbook/' LIMIT 1),'supports',NULL,'Playbook release','Handbook-derived company publication.',CURRENT_TIMESTAMP),
('obs_ev_dmu10_c06','obs_claim_dmu10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.linkedin.com/posts/darrenmurph_gitlab-allremote-remote-activity-7025874520297115648-nTvh' LIMIT 1),'supports',NULL,'Departure statement','Historic authority endpoint.',CURRENT_TIMESTAMP),
('obs_ev_dmu10_c07','obs_claim_dmu10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://hire.andela.com/rs/449-UCH-555/images/DecodingDistributedWork.pdf?version=0' LIMIT 1),'supports',NULL,'Andela white paper','Later company role.',CURRENT_TIMESTAMP),
('obs_ev_dmu10_c08','obs_claim_dmu10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.guinnessworldrecords.com/world-records/most-prolific-professional-blogger' LIMIT 1),'supports',NULL,'Official record page','Dated contracted-post count.',CURRENT_TIMESTAMP),
('obs_ev_dmu10_c09','obs_claim_dmu10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.linkedin.com/posts/darrenmurph_gitlab-allremote-remote-activity-7025874520297115648-nTvh' LIMIT 1),'supports',NULL,'Team language','Institutional outcome boundary.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_dmu10_git',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'organization','GitLab','former_head_and_vp_of_remote','2019-01-01T00:00:00Z','2023-01-01T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.linkedin.com/posts/darrenmurph_gitlab-allremote-remote-activity-7025874520297115648-nTvh' LIMIT 1),NULL,'Approximate dates; institutional authority and labor preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_dmu10_hand',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'publication','GitLab handbook and Remote Playbook','author_editor_spokesperson_and_contributor','2019-01-01T00:00:00Z','2023-01-01T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://about.gitlab.com/press/releases/2021-04-20-all-remote-playbook/' LIMIT 1),NULL,'GitLab rights and other contributors preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_dmu10_eng',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'organization','Engadget','former_editor_and_contracted_blogger','2006-07-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.guinnessworldrecords.com/world-records/most-prolific-professional-blogger' LIMIT 1),NULL,'Platform, editorial labor and content rights preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_dmu10_gwr',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'organization','Guinness World Records','record_holder','2010-07-29T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.guinnessworldrecords.com/world-records/most-prolific-professional-blogger' LIMIT 1),NULL,'Category-specific dated record',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_dmu10_and',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'organization','Andela','vp_workplace_design_and_remote_experience','2023-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://hire.andela.com/rs/449-UCH-555/images/DecodingDistributedWork.pdf?version=0' LIMIT 1),NULL,'Company authority and outcomes preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_dmu10_ford',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'organization','Ford','reported_head_of_technology_strategy_communications',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://runningremote.com/speaker/darren-murph/' LIMIT 1),NULL,'Primary employer confirmation required',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_dmu10_ind',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'practice','Independent consulting, writing and speaking','consultant_author_and_speaker',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://darrenmurph.com/' LIMIT 1),NULL,'Entity, clients, contracts, rights and fees unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_dmu10_2006',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'employment','Engadget career begins','Guinness states Murph began at Engadget in July 2006.','2006-07-01T00:00:00Z','month','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.guinnessworldrecords.com/world-records/most-prolific-professional-blogger' LIMIT 1),NULL,'Employment details incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_dmu10_record',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'record','Guinness publication record measured','Guinness records 17,212 contracted Engadget posts.','2010-07-29T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.guinnessworldrecords.com/world-records/most-prolific-professional-blogger' LIMIT 1),NULL,'Dated count; no rights inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_dmu10_remote',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'institutional_history','GitLab all-remote baseline','GitLab states it had been all-remote since 2014.','2014-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://about.gitlab.com/press/releases/2021-02-09-gitlab-announces-new-remote-work-report/' LIMIT 1),NULL,'Predates Murph role',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_dmu10_role',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'appointment','GitLab Head of Remote period begins','Public accounts place Murph in the role around 2019.','2019-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.worklife.news/leadership/youre-never-putting-this-remote-genie-back-in-the-bottle-how-gitlabs-head-of-remote-darren-murph-spends-his-day/' LIMIT 1),NULL,'Exact appointment instrument unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_dmu10_play',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'publication','GitLab Remote Playbook released','GitLab published a handbook-derived remote-work playbook.','2021-04-20T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://about.gitlab.com/press/releases/2021-04-20-all-remote-playbook/' LIMIT 1),NULL,'Institutional publication',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_dmu10_dep',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'departure','GitLab departure announced','Murph announced leaving after a self-reported 3.5 years.','2023-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.linkedin.com/posts/darrenmurph_gitlab-allremote-remote-activity-7025874520297115648-nTvh' LIMIT 1),NULL,'Self-reported transition',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_darren_murph_100','darren-murph-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'1.0.0','research/observatory/dossiers/darren-murph-1.0.0.md','4ad493b68c755b3dc24bc0b57788ce5fcc957cc3',
'{"claimIds":["obs_claim_dmu10_c01","obs_claim_dmu10_c02","obs_claim_dmu10_c03","obs_claim_dmu10_c04","obs_claim_dmu10_c05","obs_claim_dmu10_c06","obs_claim_dmu10_c07","obs_claim_dmu10_c08","obs_claim_dmu10_c09","obs_claim_dmu10_c10"],"relationshipIds":["obs_rel_dmu10_git","obs_rel_dmu10_hand","obs_rel_dmu10_eng","obs_rel_dmu10_gwr","obs_rel_dmu10_and","obs_rel_dmu10_ford","obs_rel_dmu10_ind"],"eventIds":["obs_event_dmu10_2006","obs_event_dmu10_record","obs_event_dmu10_remote","obs_event_dmu10_role","obs_event_dmu10_play","obs_event_dmu10_dep"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","gitlab_specific_role_novelty_only","preexisting_all_remote_system","distributed_institutional_labor","current_roles_require_refresh","ownership_and_ip_unverified","compensation_and_contracts_unverified","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.88,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_darren_murph_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='darren-murph' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_darren_murph_100',
'{"packageId":"darren-murph-1.0.0","claimsLoaded":10,"relationshipsLoaded":7,"eventsLoaded":6,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Role novelty, pre-existing GitLab infrastructure, distributed labor, historic authority, IP, economics, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;