-- Noubar Afeyan public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Flagship founder and CEO; Moderna co-founder and board chair within a distributed venture system.',
    "summary"='A founder-led but institutionally produced network separating funds, portfolio companies, cofounders, executives, scientists, boards, investors, outcomes and personal economics.',
    "inclusionRationale"='Tests whether a venture-creation system can be modeled without conflating founder status, fund control, portfolio ownership, personal wealth, sole invention, sole causality or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.87,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='noubar-afeyan';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_na10_profile','https://www.flagshippioneering.com/people/noubar-afeyan','Noubar Afeyan profile','Flagship Pioneering','primary_company_profile',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_na10_fund24','https://www.flagshippioneering.com/news/press-release/flagship-pioneering-raises-3-6-billion-to-fuel-breakthrough-innovations-that-transform-human-health-and-sustainability','Flagship raises $3.6 billion','Flagship Pioneering','primary_fund_announcement','2024-07-10T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_na10_mrnas1','https://www.sec.gov/Archives/edgar/data/1682852/000119312518335714/d611137ds1a.htm','Moderna Form S-1/A','SEC / Moderna','primary_regulatory_filing','2018-11-28T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_na10_mrna25','https://www.sec.gov/Archives/edgar/data/1682852/000130817925000082/mrna-20250310.htm','Moderna 2025 proxy','SEC / Moderna','primary_regulatory_filing','2025-03-10T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_na10_mrna26','https://www.sec.gov/Archives/edgar/data/1682852/000130817926000081/mrna-courtesy-pdf.pdf','Moderna 2026 proxy','SEC / Moderna','primary_regulatory_filing','2026-03-16T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_na10_lila','https://www.flagshippioneering.com/news/press-release/flagship-pioneering-unveils-lila-sciences-to-build-superintelligence-in-science','Flagship unveils Lila Sciences','Flagship Pioneering','primary_company_announcement','2025-03-10T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_na10_quotient','https://www.flagshippioneering.com/news/press-release/flagship-pioneering-appoints-rahul-kakkar-as-ceo-partner-and-ceo-of-quotient-therapeutics','Rahul Kakkar appointed Quotient CEO','Flagship Pioneering','primary_company_announcement','2025-04-29T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_na10_rubius','https://www.sec.gov/Archives/edgar/data/1709401/000104746919002211/a2238342zdef14a.htm','Rubius Therapeutics 2019 proxy','SEC / Rubius Therapeutics','primary_regulatory_filing','2019-04-26T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_na10_seres','https://www.sec.gov/Archives/edgar/data/1609809/000114036124038575/ny20030749x10_defm14a.htm','Seres VOWST sale proxy','SEC / Seres Therapeutics','primary_regulatory_filing','2024-08-20T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_na10_seresnews','https://ir.serestherapeutics.com/news-releases/news-release-details/seres-therapeutics-stockholders-approve-sale-vowsttm-nestle','Seres stockholders approve VOWST sale','Seres Therapeutics','primary_company_announcement','2024-09-26T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_na10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'executive_role','Afeyan founded Flagship Pioneering and serves as its CEO.','formal_role','observed','unreviewed',NULL,'Founder and CEO of Flagship Pioneering.','No automatic personal ownership of every fund or portfolio company.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_na10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'fund_metric','Flagship announced a $3.6 billion raise, $10.9 billion aggregate capital pool and $14 billion AUM in July 2024.','institutional_finance','attributed','unreviewed',NULL,'Use as dated, source-defined firm and fund metrics.','Not Afeyan personal capital, income, liquidity or net worth.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_na10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'formation_history','Moderna attributes its early platform to a VentureLabs team led by Afeyan working with Derrick Rossi, Robert Langer and Kenneth Chien.','distributed_creation','primary_filing','unreviewed',NULL,'Afeyan led a team-based formation process with academic co-founders.','No sole-founder, sole-inventor or sole-labor inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_na10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'governance_role','Afeyan is a Moderna co-founder and board chair within separate executive management and multi-person board governance.','formal_governance','primary_filing','unreviewed',NULL,'Co-founder and board chair of Moderna.','Chair is not CEO, sole director or unilateral controller.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_na10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'ownership_boundary','Moderna filings distinguish personal securities, options, Flagship-held interests, affiliated fund interests and security-specific voting-power attribution.','ownership_boundary','primary_filing','unreviewed',NULL,'Use only the dated filing and precise security definition.','Do not collapse fund voting power, deemed beneficial ownership and personal ownership.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_na10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'portfolio_relationship','Generate, Lila and Quotient document co-founder or chair roles alongside separate investors, executives and institutional leadership.','distributed_portfolio','observed','unreviewed',NULL,'Formal founder and chair roles within separately led companies.','No sole invention, sole management, complete ownership or personal-value inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_na10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'role_transition','Rubius filings document changing president, chair and director roles within multi-person governance.','role_transition','primary_filing','unreviewed',NULL,'Afeyan held formal but changing Rubius roles.','Historic titles do not prove current control or personal responsibility for all outcomes.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_na10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'adverse_portfolio_event','Seres sold VOWST rights through a board-reviewed and shareholder-approved transaction after financial pressure.','adverse_portfolio_evidence','corroborated','unreviewed',NULL,'A Flagship-related company sold a major asset through formal governance.','Do not assign company distress or transaction proceeds personally to Afeyan.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_na10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'claim_restriction','Venture counts and aggregate portfolio value are Flagship-defined institutional metrics.','claim_restriction','observed','unreviewed',NULL,'Use only with source, date and definition.','Do not convert into personal ownership, liquid wealth or sole-created value.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_na10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'claim_restriction','No reviewed record establishes complete fund economics, private cap tables, cross-entity contracts, IP schedules, labor attribution, causal impact or psychological measurements.','claim_restriction','observed','unreviewed',NULL,'Public evidence establishes bounded roles and filing-specific interests.','Absence of public evidence is not proof that no private rights exist.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_na10_c01','obs_claim_na10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.flagshippioneering.com/people/noubar-afeyan' LIMIT 1),'supports',NULL,'Current profile','Founder and CEO role; promotional limits preserved.',CURRENT_TIMESTAMP),
('obs_ev_na10_c02','obs_claim_na10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.flagshippioneering.com/news/press-release/flagship-pioneering-raises-3-6-billion-to-fuel-breakthrough-innovations-that-transform-human-health-and-sustainability' LIMIT 1),'supports',NULL,'Capital announcement','Firm metrics separated from personal economics.',CURRENT_TIMESTAMP),
('obs_ev_na10_c03','obs_claim_na10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1682852/000119312518335714/d611137ds1a.htm' LIMIT 1),'supports',NULL,'Company formation section','VentureLabs and academic co-founder attribution.',CURRENT_TIMESTAMP),
('obs_ev_na10_c04','obs_claim_na10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1682852/000130817925000082/mrna-20250310.htm' LIMIT 1),'supports',NULL,'Board and nominee sections','Board chair separated from CEO and board.',CURRENT_TIMESTAMP),
('obs_ev_na10_c05','obs_claim_na10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1682852/000130817926000081/mrna-courtesy-pdf.pdf' LIMIT 1),'supports',NULL,'Ownership and director-compensation sections','Dated security-specific snapshot.',CURRENT_TIMESTAMP),
('obs_ev_na10_c06','obs_claim_na10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.flagshippioneering.com/news/press-release/flagship-pioneering-unveils-lila-sciences-to-build-superintelligence-in-science' LIMIT 1),'supports',NULL,'Launch and financing','Multiple investors and separate company.',CURRENT_TIMESTAMP),
('obs_ev_na10_c07','obs_claim_na10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1709401/000104746919002211/a2238342zdef14a.htm' LIMIT 1),'supports',NULL,'Director biography','Changing formal roles.',CURRENT_TIMESTAMP),
('obs_ev_na10_c08','obs_claim_na10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1609809/000114036124038575/ny20030749x10_defm14a.htm' LIMIT 1),'supports',NULL,'Transaction background','Board process and company-level outcome.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_na10_flagship',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'organization','Flagship Pioneering','founder_ceo','2000-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.flagshippioneering.com/people/noubar-afeyan' LIMIT 1),NULL,'Fund and portfolio ownership not inferred',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_na10_moderna',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'organization','Moderna','cofounder_board_chair','2010-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1682852/000130817925000082/mrna-20250310.htm' LIMIT 1),NULL,'Separate CEO and multi-person board',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_na10_cofounders',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'group','Derrick Rossi, Robert Langer and Kenneth Chien','moderna_academic_cofounders','2010-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1682852/000119312518335714/d611137ds1a.htm' LIMIT 1),NULL,'Academic and VentureLabs labor preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_na10_lila',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'organization','Lila Sciences','cofounder_board_chair','2025-03-10T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.flagshippioneering.com/news/press-release/flagship-pioneering-unveils-lila-sciences-to-build-superintelligence-in-science' LIMIT 1),NULL,'Multiple investors and separate institutional labor',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_na10_quotient',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'organization','Quotient Therapeutics','cofounder','2022-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.flagshippioneering.com/news/press-release/flagship-pioneering-appoints-rahul-kakkar-as-ceo-partner-and-ceo-of-quotient-therapeutics' LIMIT 1),NULL,'Rahul Kakkar separate CEO role',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_na10_rubius',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'organization','Rubius Therapeutics','historic_president_chair_director','2013-04-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1709401/000104746919002211/a2238342zdef14a.htm' LIMIT 1),NULL,'Roles changed over time; outcomes institution-level',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_na10_flagship',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'formation','Flagship formed','Afeyan founded the venture-creation institution around 1999-2000.','2000-01-01T00:00:00Z','year_approximate','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.flagshippioneering.com/people/noubar-afeyan' LIMIT 1),NULL,'Source chronology varies between 1999 and 2000',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_na10_moderna',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'formation','Moderna co-founded','VentureLabs and academic co-founders formed Moderna.','2010-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1682852/000119312518335714/d611137ds1a.htm' LIMIT 1),NULL,'Distributed formation attribution',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_na10_rubius',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'role_transition','Rubius roles changed','Afeyan served in changing president, chair and director roles beginning in 2013.','2013-04-01T00:00:00Z','month','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1709401/000104746919002211/a2238342zdef14a.htm' LIMIT 1),NULL,'Historic roles, not permanent control',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_na10_fund24',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'financing','Flagship announces new capital','Flagship announced $3.6B of new capital and associated institutional metrics.','2024-07-10T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.flagshippioneering.com/news/press-release/flagship-pioneering-raises-3-6-billion-to-fuel-breakthrough-innovations-that-transform-human-health-and-sustainability' LIMIT 1),NULL,'Firm and fund metrics only',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_na10_lila',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'formation','Lila Sciences unveiled','Flagship unveiled Lila with multiple investors and committed seed capital.','2025-03-10T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.flagshippioneering.com/news/press-release/flagship-pioneering-unveils-lila-sciences-to-build-superintelligence-in-science' LIMIT 1),NULL,'Company financing not personal economics',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_noubar_afeyan_100','noubar-afeyan-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'1.0.0','research/observatory/dossiers/noubar-afeyan-1.0.0.md','2e0ea33d50fb1892da063d743d86cd6ab53126eb',
'{"claimIds":["obs_claim_na10_c01","obs_claim_na10_c02","obs_claim_na10_c03","obs_claim_na10_c04","obs_claim_na10_c05","obs_claim_na10_c06","obs_claim_na10_c07","obs_claim_na10_c08","obs_claim_na10_c09","obs_claim_na10_c10"],"relationshipIds":["obs_rel_na10_flagship","obs_rel_na10_moderna","obs_rel_na10_cofounders","obs_rel_na10_lila","obs_rel_na10_quotient","obs_rel_na10_rubius"],"eventIds":["obs_event_na10_flagship","obs_event_na10_moderna","obs_event_na10_rubius","obs_event_na10_fund24","obs_event_na10_lila"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","distributed_venture_system","cofounders_and_scientific_labor_preserved","fund_metrics_not_personal_economics","portfolio_ownership_not_inferred","mixed_portfolio_outcomes","ip_and_contracts_incomplete","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.87,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_noubar_afeyan_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='noubar-afeyan' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_noubar_afeyan_100',
'{"packageId":"noubar-afeyan-1.0.0","claimsLoaded":10,"relationshipsLoaded":6,"eventsLoaded":5,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Fund, entity, ownership, governance, IP, labor, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
