-- Nadir Godrej public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, assign trust assets, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Current Godrej Industries Group chair with documented multi-company authority and a planned August 2026 succession.',
    "summary"='A role- and holder-bounded account separating listed companies, group leadership, promoter trusts, family succession, company performance, co-invention, poetry and philanthropy.',
    "inclusionRationale"='Tests whether a multigenerational family-business leader can be represented without conflating chairmanship, management, trusteeship, beneficial ownership, institutional labor, invention, creative authorship, causal performance or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.88,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='nadir-godrej';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_ng10_lead','https://www.godrejindustries.com/know-us/leadership/nadir-godrej-bod','Nadir Godrej leadership biography','Godrej Industries Group','primary_company_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_succ','https://www.godrejindustries.com/uploads/GILPRESSRELEASECOVERLETTER_13042026_85fda3e78d.pdf','Godrej Industries Group leadership transitions','Godrej Industries Limited','exchange_filing','2026-04-13T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_gil26','https://www.godrejindustries.com/uploads/Godrej_Industries_Limited_Annual_Report_2025_26_a51007baba.pdf','Godrej Industries annual report 2025-26','Godrej Industries Limited','annual_report','2026-03-31T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_gavl26','https://www.godrejagrovet.com/uploads/Annual_Report_2025_26_1eec0f8033.pdf','Godrej Agrovet annual report 2025-26','Godrej Agrovet Limited','annual_report','2026-03-31T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_shp25','https://www.godrejindustries.com/uploads/SHP_30_JUNE_2025websiteupload_fa5fd4a87e.pdf','Godrej Industries shareholding pattern June 2025','Godrej Industries Limited','shareholding_filing','2025-06-30T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_fin25','https://www.godrejindustries.com/uploads/Standalone_Financials_2024_25_42aa7fc6a3.pdf','Godrej Industries standalone financial statements 2024-25','Godrej Industries Limited','audited_financials','2025-03-31T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_2021','https://www.godrejindustries.com/uploads/GIL_Press_Release_9335882aff.pdf','Godrej Industries 2021 leadership transition','Godrej Industries Limited','primary_company_release','2021-08-13T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_realign','https://www.reuters.com/business/indias-godrej-family-agree-split-conglomerate-into-two-2024-05-01/','Godrej family ownership realignment','Reuters','independent_journalism','2024-05-01T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_patent','https://patents.google.com/patent/IN185675B/en','Indian patent IN185675B','Indian Patent Office via Google Patents','patent_record','2001-03-31T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_poetry','https://agfundernews.com/nadir-godrej-indias-bard-of-agtech','Nadir Godrej, India’s bard of agtech','AgFunderNews','independent_interview','2019-11-20T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_agm25','https://www.godrejindustries.com/uploads/37th_AGM_Notice_1610edd5c3.pdf','Godrej Industries 37th AGM notice','Godrej Industries Limited','agm_notice','2025-05-15T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_gov26','https://www.godrejindustries.com/uploads/Corporate_Governance_Report_31032026_dadda24af6.pdf','Godrej Industries corporate governance report 2025-26','Godrej Industries Limited','governance_filing','2026-03-31T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ng10_burjis','https://www.godrejindustries.com/uploads/GIL_POSTAL_BALLOT_MAY_2026_Final_e1a27b091b.pdf','Godrej Industries May 2026 postal ballot notice','Godrej Industries Limited','postal_ballot_notice','2026-05-15T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_ng10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'current_role','As of July 26, 2026, Godrej is Chairperson of Godrej Industries Group and Chairman and Managing Director of Godrej Industries Limited.','formal_role','primary_record','unreviewed',NULL,'Current chair and managing director, with an as-of date.','No sole ownership, permanent authority, subsidiary ownership or identity with the legal entities.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ng10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'current_role','Godrej is Chairman and Non-Executive Director of Godrej Agrovet within a separately disclosed board and executive structure.','formal_role','primary_record','unreviewed',NULL,'Chairman of Godrej Agrovet within multi-person governance.','No sole operational control, labor, strategy, ownership or company-performance attribution.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ng10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'succession','A primary April 2026 announcement fixes a planned August 2026 retirement and specified board exits and records his Astec exit effective April 13, 2026.','time_bounded_authority','primary_record','unreviewed',NULL,'Planned future role endings and one completed Astec exit.','Do not describe future exits as completed or infer forced removal, dispute, incapacity or motive.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ng10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'ownership_realignment','The 2024 family agreement separated Godrej Industries Group and Godrej Enterprises Group under distinct leadership and company structures.','institutional_boundary','corroborated','unreviewed',NULL,'A disclosed family ownership and operating realignment into distinct groups.','No pre-split personal ownership, sole-causation or ownership of Godrej Enterprises Group.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ng10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'trust_relationship','Shareholding filings name Godrej as one of multiple trustees for holder-specific promoter-group trusts.','ownership_boundary','primary_record','unreviewed',NULL,'Named co-trustee in specific promoter-group holder records.','Trustee status is not personal beneficial ownership; do not aggregate trust shares as his personal stake, wealth or vote.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ng10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'role_history','Godrej has served within the group since 1977 and formally succeeded Adi Godrej as GIL Chairman and Managing Director effective October 1, 2021.','formal_role','primary_record','unreviewed',NULL,'Long-tenured executive and formal 2021 successor.','No founder, sole builder, owner, uninterrupted identical authority or isolated performance claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ng10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'co_invention','Patent record IN185675B names Nadir Godrej with Keki Mistry and Brahmanand Vyas as inventors and Godrej Agrovet as original assignee.','distributed_invention','primary_record','unreviewed',NULL,'Named co-inventor on the identified patent record.','No sole inventorship, current validity, freedom to operate, personal IP ownership or licensing-revenue claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ng10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'creative_role','Godrej publicly writes and performs poetry, including in business and agricultural settings.','creative_role','corroborated','unreviewed',NULL,'Poet and public performer of his own verse.','No complete bibliography, publishing-rights, recording-rights, sales or measured audience-impact claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ng10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'metric_boundary','Listed-company results, market values, promoter holdings and group scale are company- or holder-specific measures.','financial_boundary','primary_record','unreviewed',NULL,'Report each measure with its entity, holder and date.','Do not convert company or trust figures into personal income, wealth, liquidity, enterprise value or isolated leadership performance.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ng10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'claim_restriction','No reviewed public record establishes complete beneficial ownership, trust instruments, voting arrangements, IP schedules, employment rights, media rights, personal philanthropy, causal performance or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified or incomplete.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_ng10_c01','obs_claim_ng10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/know-us/leadership/nadir-godrej-bod' LIMIT 1),'supports',NULL,'Leadership biography','Current role requires August refresh.',CURRENT_TIMESTAMP),
('obs_ev_ng10_c02','obs_claim_ng10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejagrovet.com/uploads/Annual_Report_2025_26_1eec0f8033.pdf' LIMIT 1),'supports',NULL,'Board of Directors','Separate CEO/MD and board preserved.',CURRENT_TIMESTAMP),
('obs_ev_ng10_c03','obs_claim_ng10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/GILPRESSRELEASECOVERLETTER_13042026_85fda3e78d.pdf' LIMIT 1),'supports',NULL,'April 13, 2026 transition announcement','Completed and future role endings separated.',CURRENT_TIMESTAMP),
('obs_ev_ng10_c04','obs_claim_ng10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/indias-godrej-family-agree-split-conglomerate-into-two-2024-05-01/' LIMIT 1),'supports',NULL,'2024 ownership realignment report','Distinct groups and leaders preserved.',CURRENT_TIMESTAMP),
('obs_ev_ng10_c05','obs_claim_ng10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/SHP_30_JUNE_2025websiteupload_fa5fd4a87e.pdf' LIMIT 1),'supports',NULL,'Promoter-group shareholding table','Trustee not equated with beneficial owner.',CURRENT_TIMESTAMP),
('obs_ev_ng10_c06','obs_claim_ng10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/GIL_Press_Release_9335882aff.pdf' LIMIT 1),'supports',NULL,'2021 transition release','Formal title transition only.',CURRENT_TIMESTAMP),
('obs_ev_ng10_c07','obs_claim_ng10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://patents.google.com/patent/IN185675B/en' LIMIT 1),'supports',NULL,'Inventor and assignee fields','Co-inventors and corporate assignee preserved.',CURRENT_TIMESTAMP),
('obs_ev_ng10_c08','obs_claim_ng10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://agfundernews.com/nadir-godrej-indias-bard-of-agtech' LIMIT 1),'supports',NULL,'Interview and poetry performance','Creative rights and impact unresolved.',CURRENT_TIMESTAMP),
('obs_ev_ng10_c09','obs_claim_ng10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/Standalone_Financials_2024_25_42aa7fc6a3.pdf' LIMIT 1),'supports',NULL,'Financial and holder-specific disclosure','Company and holder figures not personal economics.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_ng10_gig',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'organization','Godrej Industries Group','chairperson',NULL,'2026-08-13T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/GILPRESSRELEASECOVERLETTER_13042026_85fda3e78d.pdf' LIMIT 1),NULL,'Planned endpoint; refresh after effective date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ng10_gil',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'organization','Godrej Industries Limited','chairman_and_managing_director','2021-10-01T00:00:00Z','2026-08-13T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/GILPRESSRELEASECOVERLETTER_13042026_85fda3e78d.pdf' LIMIT 1),NULL,'Company authority is delegated and time-bounded',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ng10_gavl',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'organization','Godrej Agrovet Limited','chairman_nonexecutive_director',NULL,'2026-08-13T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejagrovet.com/uploads/Annual_Report_2025_26_1eec0f8033.pdf' LIMIT 1),NULL,'Separate CEO, board, employees and shareholders',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ng10_astec',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'organization','Astec LifeSciences Limited','former_chairperson_and_nonexecutive_director',NULL,'2026-04-13T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/GILPRESSRELEASECOVERLETTER_13042026_85fda3e78d.pdf' LIMIT 1),NULL,'Completed board exit',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ng10_pirojsha',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'person','Pirojsha Godrej','nephew_and_chairperson_designate','2026-04-13T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/GILPRESSRELEASECOVERLETTER_13042026_85fda3e78d.pdf' LIMIT 1),NULL,'Succession is not proof of equity transfer',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ng10_burjis',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'person','Burjis Godrej','son_and_godrej_agrovet_chair_designate','2026-04-13T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/GIL_POSTAL_BALLOT_MAY_2026_Final_e1a27b091b.pdf' LIMIT 1),NULL,'Family, executive and future governance roles separated',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ng10_trusts',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'trust','Named Godrej family trusts','co_trustee_in_promoter_group_filings',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/SHP_30_JUNE_2025websiteupload_fa5fd4a87e.pdf' LIMIT 1),NULL,'Trustee status not personal beneficial ownership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_ng10_1977',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'appointment','Godrej becomes a director of Godrej Soaps','Official biography dates his director role to 1977.','1977-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/know-us/leadership/nadir-godrej-bod' LIMIT 1),NULL,'Later titles and entity changes not backdated',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ng10_patent',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'patent_filing','Identified co-inventor patent filed','Patent record names three inventors and Godrej Agrovet as original assignee.','1995-12-21T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://patents.google.com/patent/IN185675B/en' LIMIT 1),NULL,'Legal status and scope require separate review',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ng10_2021',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'succession','Godrej becomes GIL Chairman and Managing Director','The 2021 company release states the transition became effective October 1.','2021-10-01T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/GIL_Press_Release_9335882aff.pdf' LIMIT 1),NULL,'Formal company role transition',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ng10_realign',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'ownership_realignment','Godrej family realignment announced','Public filing and reporting describe two distinct group structures.','2024-05-01T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.reuters.com/business/indias-godrej-family-agree-split-conglomerate-into-two-2024-05-01/' LIMIT 1),NULL,'No personal-ownership or sole-causation inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ng10_astec',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'role_end','Godrej exits Astec board','Primary announcement records completed Astec chair and non-executive director exit.','2026-04-13T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/GILPRESSRELEASECOVERLETTER_13042026_85fda3e78d.pdf' LIMIT 1),NULL,'Completed exit distinguished from future exits',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ng10_future',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'planned_succession','Planned group and company succession effective','Godrej is announced to become Chairman Emeritus as Pirojsha and Burjis assume specified chairs.','2026-08-14T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.godrejindustries.com/uploads/GILPRESSRELEASECOVERLETTER_13042026_85fda3e78d.pdf' LIMIT 1),NULL,'Future event as of package date; verify after effective date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_nadir_godrej_100','nadir-godrej-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'1.0.0','research/observatory/dossiers/nadir-godrej-1.0.0.md','51d24b5b4acffb3b2cb05792cbcdcba979f494cd',
'{"claimIds":["obs_claim_ng10_c01","obs_claim_ng10_c02","obs_claim_ng10_c03","obs_claim_ng10_c04","obs_claim_ng10_c05","obs_claim_ng10_c06","obs_claim_ng10_c07","obs_claim_ng10_c08","obs_claim_ng10_c09","obs_claim_ng10_c10"],"relationshipIds":["obs_rel_ng10_gig","obs_rel_ng10_gil","obs_rel_ng10_gavl","obs_rel_ng10_astec","obs_rel_ng10_pirojsha","obs_rel_ng10_burjis","obs_rel_ng10_trusts"],"eventIds":["obs_event_ng10_1977","obs_event_ng10_patent","obs_event_ng10_2021","obs_event_ng10_realign","obs_event_ng10_astec","obs_event_ng10_future"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","current_roles_require_as_of_date","planned_future_exits_not_completed","multi_company_governance","family_groups_separated","trustee_not_beneficial_owner","company_metrics_not_personal_wealth","co_inventors_and_assignee_preserved","creative_rights_incomplete","philanthropy_not_personal_impact","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.88,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_nadir_godrej_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='nadir-godrej' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_nadir_godrej_100',
'{"packageId":"nadir-godrej-1.0.0","claimsLoaded":10,"relationshipsLoaded":7,"eventsLoaded":6,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Current and future role, group, company, trust, beneficial-ownership, family succession, co-invention, media-rights, philanthropy, performance, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
