-- Mustafa Suleyman public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, resolve private economics, or mark saturation complete.

INSERT INTO "ObservatoryCase"
("id","slug","displayName","caseType","primaryField","jurisdiction","headline","summary","inclusionRationale","roleBuiltFlag","verificationStatus","evidenceCoverage","consentStatus","publicStatus","createdAt","updatedAt")
VALUES
('obs_case_mustafa_suleyman','mustafa-suleyman','Mustafa Suleyman','professional','Artificial intelligence and technology','United States / United Kingdom',
'Microsoft AI executive whose formal authority, transferred teams, institutional dependencies and changing remit illustrate how a role-centered organization is assembled.',
'A public-evidence case separating a newly formed administrative organization from its pre-existing products, transferred personnel, licensed technology, retained corporate governance and later model-development capacity.',
'Selected to test the claim that Microsoft created a new AI division around Suleyman without inflating appointment into personal invention, ownership or sole causation.',
true,'in_review',0.88,'public_evidence','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("slug") DO UPDATE SET "headline"=EXCLUDED."headline","summary"=EXCLUDED."summary","inclusionRationale"=EXCLUDED."inclusionRationale","roleBuiltFlag"=true,"verificationStatus"='in_review',"evidenceCoverage"=0.88,"updatedAt"=CURRENT_TIMESTAMP;

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_ms_s01','https://blogs.microsoft.com/blog/2024/03/19/mustafa-suleyman-deepmind-and-inflection-co-founder-joins-microsoft-to-lead-copilot/','Mustafa Suleyman joins Microsoft to lead Copilot','Microsoft','company_announcement','2024-03-19T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s02','https://blogs.microsoft.com/blog/2024/04/07/announcing-new-microsoft-ai-hub-in-london/','Announcing new Microsoft AI Hub in London','Microsoft','company_announcement','2024-04-07T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s03','https://blogs.microsoft.com/blog/2026/03/17/announcing-copilot-leadership-update/','Announcing Copilot leadership update','Microsoft','company_announcement','2026-03-17T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s04','https://microsoft.ai/news-categories/models/','Models archive','Microsoft AI','company_product_record',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s05','https://microsoft.ai/news/introducing-mai-image-1-debuting-in-the-top-10-on-lmarena/','Introducing MAI-Image-1','Microsoft AI','company_product_record','2025-10-13T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s06','https://microsoft.ai/news/building-a-hillclimbing-machine-launching-seven-new-mai-models/','Building a hill-climbing machine: launching seven new MAI models','Microsoft AI','company_product_record','2026-06-02T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s07','https://microsoft.ai/news/the-path-to-medical-superintelligence/','The Path to Medical Superintelligence','Microsoft AI','company_research_record','2025-06-30T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s08','https://www.gov.uk/cma-cases/microsoft-slash-inflection-ai-inquiry','Microsoft / Inflection inquiry','UK Competition and Markets Authority','regulator_record','2024-04-24T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s09','https://www.gov.uk/government/news/cma-seeks-views-on-ai-partnerships-and-other-arrangements','CMA seeks views on AI partnerships and other arrangements','UK Competition and Markets Authority','regulator_release','2024-04-24T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s10','https://www.reuters.com/technology/microsoft-hires-deepmind-co-founder-suleyman-head-new-consumer-ai-organization-2024-03-19/','Microsoft taps DeepMind co-founder Suleyman','Reuters','independent_reporting','2024-03-19T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s11','https://www.reuters.com/technology/microsoft-agreed-pay-inflection-650-mln-while-hiring-its-staff-information-2024-03-21/','Microsoft agreed to pay Inflection $650 million while hiring staff','Reuters','independent_reporting','2024-03-21T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s12','https://www.reuters.com/markets/europe/eu-antitrust-regulators-will-not-act-microsofts-hiring-inflection-staff-2024-09-18/','No EU merger scrutiny of Microsoft Inflection hiring','Reuters','independent_reporting','2024-09-18T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s13','https://greylock.com/portfolio-news/a-new-paradigm-in-human-machine-interaction/','A New Paradigm in Human-Machine Interaction','Greylock','founder_announcement','2022-03-08T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s14','https://greylock.com/team/mustafa-suleyman/','Mustafa Suleyman biography','Greylock','firm_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s15','https://greylock.com/firm-news/welcome-mustafa-suleyman/','Welcome Mustafa Suleyman','Greylock','firm_announcement','2022-01-20T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s16','https://www.engadget.com/deepmind-ai-mustafa-suleyman-google-greylock-partners-152049755.html','DeepMind co-founder Suleyman exits Google','Engadget','independent_reporting','2022-01-21T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_ms_s17','https://ico.org.uk/for-the-public/ico-40/google-deepmind-and-class-action-lawsuit/','Google DeepMind and class action lawsuit','UK Information Commissioner''s Office','regulator_retrospective',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_ms_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'organization_formation','Microsoft announced Microsoft AI on 19 March 2024 as a new organization.','institution_building','observed','unreviewed',NULL,'Microsoft formed a new organization called Microsoft AI in March 2024.','Formation does not establish Suleyman ownership or sole invention.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'executive_appointment','Suleyman became EVP and CEO of Microsoft AI, joined the senior leadership team and reported to Satya Nadella.','formal_authority','observed','unreviewed',NULL,'Microsoft appointed Suleyman EVP and CEO of Microsoft AI, reporting to Satya Nadella.','The title did not grant authority over all Microsoft AI activity.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'scientific_leadership','Karén Simonyan joined as chief scientist and reported to Suleyman.','distributed_leadership','observed','unreviewed',NULL,'Karén Simonyan joined Microsoft AI as chief scientist.','Do not attribute scientific leadership solely to Suleyman.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'transferred_teams','Existing Copilot, Bing, Edge and GenAI teams moved into Suleyman''s reporting line in 2024.','resource_assembly','observed','unreviewed',NULL,'Microsoft AI combined transferred Microsoft teams with incoming personnel.','Suleyman and Inflection did not originate those existing products.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'retained_governance','Kevin Scott retained company-wide AI strategy and architecture authority while Rajesh Jha retained Microsoft 365 Copilot responsibility.','governance_accountability','observed','unreviewed',NULL,'Microsoft preserved material AI authority outside Microsoft AI.','Microsoft AI was not Microsoft''s sole AI authority.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'openai_dependency','Microsoft stated that its OpenAI partnership and supporting infrastructure work would continue.','institutional_dependency','observed','unreviewed',NULL,'Microsoft AI was formed within a wider Microsoft–OpenAI architecture.','Do not describe Microsoft AI as technologically independent in 2024.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'inflection_arrangements','Microsoft hired Inflection leaders and employees and entered associated licensing arrangements with Inflection.','institutional_portability','observed','unreviewed',NULL,'Microsoft AI''s formation included personnel transfer and licensed Inflection technology.','Microsoft did not publicly describe the arrangement as an outright Inflection acquisition.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'regulatory_review','The UK CMA found a relevant merger situation and cleared the arrangements after finding no realistic prospect of substantial lessening of competition.','governance_accountability','observed','unreviewed',NULL,'UK regulators reviewed and cleared the Microsoft–Inflection arrangements.','Clearance does not erase structural significance or resolve every jurisdiction.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'london_hub','Microsoft AI opened a London hub led by Jordan Hoffmann for model and infrastructure work.','resource_assembly','observed','unreviewed',NULL,'Microsoft AI expanded its capacity through a London hub.','Hub outputs are institutional and collaborative.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'model_outputs','Microsoft AI announced internally developed model families and product deployments in 2025 and 2026.','institutional_outputs','observed','unreviewed',NULL,'Teams within Microsoft AI released Microsoft-developed model families.','Do not say Suleyman personally invented or trained the models.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c11',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'remit_change','Microsoft changed Copilot and model leadership in March 2026, shifting Suleyman''s principal focus toward frontier models and superintelligence.','role_evolution','observed','unreviewed',NULL,'Suleyman retained the CEO title but shifted his principal focus toward frontier models and superintelligence.','His March 2024 product remit did not remain unchanged.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c12',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'copilot_governance','Jacob Andreou became EVP of Copilot reporting to Nadella while a cross-functional leadership team connected product, platform, applications and models.','distributed_leadership','observed','unreviewed',NULL,'Current Copilot authority is distributed across named leaders.','Suleyman does not have exclusive day-to-day control of unified Copilot.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c13',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'career_chronology','Suleyman previously co-founded DeepMind, led applied AI, moved to Google product and policy, joined Greylock and co-founded Inflection.','institutional_portability','observed','unreviewed',NULL,'His appointment followed roles across DeepMind, Google, Greylock and Inflection.','Prior institutional outputs are not solely his work or property.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c14',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'management_boundary','Public sources document management complaints at DeepMind and Suleyman''s later apology.','governance_accountability','observed','unreviewed',NULL,'A complete leadership record includes reported management complaints and Suleyman''s public apology.','Do not diagnose motive, personality or stable psychological disposition.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c15',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'data_governance_boundary','The Royal Free–DeepMind health-data project generated a privacy finding against the Trust.','governance_accountability','observed','unreviewed',NULL,'DeepMind Health''s institutional history includes a material data-governance controversy.','Do not attribute the legal finding personally to Suleyman.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c16',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'bounded_role_architecture','Microsoft created a role with substantial organizational authority and assembled resources around it while retaining distributed governance.','role_centered_architecture','interpretive','unreviewed',NULL,'Microsoft formed a role-centered organization around Suleyman, but authority and causation remained distributed.','Prohibit invented-empire and sole-causation language.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_ms_c17',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'psychology_boundary','No reviewed source measures Suleyman''s psychological constructs.','claim_restriction','observed','unreviewed',NULL,'The case measures roles, resources, relationships and outputs; it does not measure psychology.','Do not score ambition, empathy, ethics or leadership psychology from biography.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_ms_c01','obs_claim_ms_c01','obs_src_ms_s01','supports',NULL,'Formation announcement','Primary formation language.',CURRENT_TIMESTAMP),
('obs_ev_ms_c02','obs_claim_ms_c02','obs_src_ms_s01','supports',NULL,'Title and reporting line','Primary appointment record.',CURRENT_TIMESTAMP),
('obs_ev_ms_c03','obs_claim_ms_c03','obs_src_ms_s01','supports',NULL,'Chief scientist appointment','Distributed scientific leadership.',CURRENT_TIMESTAMP),
('obs_ev_ms_c04','obs_claim_ms_c04','obs_src_ms_s01','supports',NULL,'Transferred reporting teams','Pre-existing product boundary.',CURRENT_TIMESTAMP),
('obs_ev_ms_c05','obs_claim_ms_c05','obs_src_ms_s01','supports',NULL,'Retained leadership remits','Distributed governance.',CURRENT_TIMESTAMP),
('obs_ev_ms_c06','obs_claim_ms_c06','obs_src_ms_s01','supports',NULL,'OpenAI partnership paragraph','External partnership boundary.',CURRENT_TIMESTAMP),
('obs_ev_ms_c07a','obs_claim_ms_c07','obs_src_ms_s09','supports',NULL,'CMA arrangement description','Personnel and related arrangements.',CURRENT_TIMESTAMP),
('obs_ev_ms_c07b','obs_claim_ms_c07','obs_src_ms_s11','qualifies',NULL,'Reported license economics','Independent deal reporting.',CURRENT_TIMESTAMP),
('obs_ev_ms_c08','obs_claim_ms_c08','obs_src_ms_s08','supports',NULL,'Phase 1 outcome','Regulatory decision boundary.',CURRENT_TIMESTAMP),
('obs_ev_ms_c09','obs_claim_ms_c09','obs_src_ms_s02','supports',NULL,'London hub announcement','Hub scope and leadership.',CURRENT_TIMESTAMP),
('obs_ev_ms_c10a','obs_claim_ms_c10','obs_src_ms_s05','supports',NULL,'MAI-Image-1 release','Institutional model output.',CURRENT_TIMESTAMP),
('obs_ev_ms_c10b','obs_claim_ms_c10','obs_src_ms_s06','supports',NULL,'Seven-model release','2026 model output.',CURRENT_TIMESTAMP),
('obs_ev_ms_c11','obs_claim_ms_c11','obs_src_ms_s03','supports',NULL,'New structure for Microsoft AI','Current remit change.',CURRENT_TIMESTAMP),
('obs_ev_ms_c12','obs_claim_ms_c12','obs_src_ms_s03','supports',NULL,'Copilot leadership structure','Current distributed governance.',CURRENT_TIMESTAMP),
('obs_ev_ms_c13a','obs_claim_ms_c13','obs_src_ms_s14','supports',NULL,'Career biography','DeepMind and Google chronology.',CURRENT_TIMESTAMP),
('obs_ev_ms_c13b','obs_claim_ms_c13','obs_src_ms_s13','supports',NULL,'Inflection founding','Founder and incubator record.',CURRENT_TIMESTAMP),
('obs_ev_ms_c14','obs_claim_ms_c14','obs_src_ms_s16','supports',NULL,'Reported apology','Management boundary.',CURRENT_TIMESTAMP),
('obs_ev_ms_c15','obs_claim_ms_c15','obs_src_ms_s17','supports',NULL,'ICO retrospective','Institutional data-governance boundary.',CURRENT_TIMESTAMP),
('obs_ev_ms_c16','obs_claim_ms_c16','obs_src_ms_s01','qualifies',NULL,'Formation and retained remits','Bounded synthesis only.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_ms_microsoft',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'organization','Microsoft','evp_and_ceo_microsoft_ai','2024-03-19T00:00:00Z',NULL,'unreviewed','draft','obs_src_ms_s01',NULL,'Employment and delegated authority, not ownership',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ms_nadella',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'person','Satya Nadella','direct_report','2024-03-19T00:00:00Z',NULL,'unreviewed','draft','obs_src_ms_s01',NULL,'Chief executive authority retained',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ms_simonyan',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'person','Karén Simonyan','cofounder_and_scientific_collaborator','2022-03-08T00:00:00Z',NULL,'unreviewed','draft','obs_src_ms_s13',NULL,'Inflection and Microsoft AI collaboration',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ms_andreou',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'person','Jacob Andreou','copilot_leadership_counterpart','2026-03-17T00:00:00Z',NULL,'unreviewed','draft','obs_src_ms_s03',NULL,'Andreou leads unified Copilot experience',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ms_scott',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'person','Kevin Scott','distributed_ai_governance','2024-03-19T00:00:00Z',NULL,'unreviewed','draft','obs_src_ms_s01',NULL,'All-up strategy and architecture remit',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ms_openai',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'organization','OpenAI','microsoft_strategic_model_partner',NULL,NULL,'unreviewed','draft','obs_src_ms_s01',NULL,'Microsoft partnership, not Suleyman asset',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ms_inflection',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'organization','Inflection AI','cofounder_former_ceo_and_licensed_technology_source','2022-03-08T00:00:00Z','2024-03-19T00:00:00Z','unreviewed','draft','obs_src_ms_s09',NULL,'Separate company; private economics incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ms_deepmind',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'organization','DeepMind / Google','cofounder_applied_ai_leader_and_google_vp','2010-01-01T00:00:00Z','2022-01-21T00:00:00Z','unreviewed','draft','obs_src_ms_s14',NULL,'Institutional IP and output boundaries',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_ms_greylock',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'organization','Greylock','venture_partner_and_inflection_incubator','2022-01-20T00:00:00Z',NULL,'unreviewed','draft','obs_src_ms_s15',NULL,'Current continuing interests require confirmation',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_ms_deepmind',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'company_formation','Suleyman co-founds DeepMind','Institutional formation with Demis Hassabis and Shane Legg.','2010-01-01T00:00:00Z','year','unreviewed','draft','obs_src_ms_s14',NULL,'Year precision',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ms_greylock',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'role_transition','Suleyman joins Greylock','Moves from Google to venture partner role.','2022-01-20T00:00:00Z','day','unreviewed','draft','obs_src_ms_s15',NULL,'Announcement date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ms_inflection',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'company_formation','Inflection AI announced','Co-founded with Reid Hoffman and Karén Simonyan.','2022-03-08T00:00:00Z','day','unreviewed','draft','obs_src_ms_s13',NULL,'Announcement date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ms_formation',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'organization_formation','Microsoft forms Microsoft AI','Suleyman appointed EVP and CEO; teams and personnel assembled.','2024-03-19T00:00:00Z','day','unreviewed','draft','obs_src_ms_s01',NULL,'Announcement date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ms_london',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'capacity_expansion','Microsoft AI London hub announced','Model, infrastructure and tooling hub led by Jordan Hoffmann.','2024-04-07T00:00:00Z','day','unreviewed','draft','obs_src_ms_s02',NULL,'Announcement date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ms_cma',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'regulatory_decision','CMA clears Microsoft–Inflection arrangements','Relevant merger situation found; no realistic prospect of substantial lessening of competition.','2024-09-04T00:00:00Z','day','unreviewed','draft','obs_src_ms_s08',NULL,'Decision date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ms_restructure',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'role_restructure','Microsoft changes Copilot and superintelligence leadership','Suleyman focuses on frontier models; Andreou leads unified Copilot experience.','2026-03-17T00:00:00Z','day','unreviewed','draft','obs_src_ms_s03',NULL,'Announcement date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_ms_models',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'institutional_output','Microsoft AI announces seven-model family','Institutional output of model and superintelligence teams.','2026-06-02T00:00:00Z','day','unreviewed','draft','obs_src_ms_s06',NULL,'Announcement date',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_mustafa_suleyman_100','mustafa-suleyman-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'1.0.0','research/observatory/dossiers/mustafa-suleyman-1.0.0.md','pending-runtime-content-hash',
'{"claimIds":["obs_claim_ms_c01","obs_claim_ms_c02","obs_claim_ms_c03","obs_claim_ms_c04","obs_claim_ms_c05","obs_claim_ms_c06","obs_claim_ms_c07","obs_claim_ms_c08","obs_claim_ms_c09","obs_claim_ms_c10","obs_claim_ms_c11","obs_claim_ms_c12","obs_claim_ms_c13"],"relationshipIds":["obs_rel_ms_microsoft","obs_rel_ms_nadella","obs_rel_ms_simonyan","obs_rel_ms_andreou","obs_rel_ms_scott","obs_rel_ms_openai","obs_rel_ms_inflection","obs_rel_ms_deepmind","obs_rel_ms_greylock"],"eventIds":["obs_event_ms_deepmind","obs_event_ms_greylock","obs_event_ms_inflection","obs_event_ms_formation","obs_event_ms_london","obs_event_ms_cma","obs_event_ms_restructure","obs_event_ms_models"],"observationIds":[],"contextOnlyClaimIds":["obs_claim_ms_c14","obs_claim_ms_c15"],"excludedInterpretiveClaimIds":["obs_claim_ms_c16"],"methodBoundaryClaimIds":["obs_claim_ms_c17"],"limitations":["saturation_decision_not_yet_recorded","two_no_new_material_evidence_passes_absent","division_assembled_from_existing_and_incoming_resources","current_remit_changed_in_2026","microsoft_ai_not_sole_company_ai_authority","openai_dependency_material","inflection_not_acquired_outright","reported_deal_economics_not_complete_contract","personal_compensation_and_equity_unverified","institutional_outputs_not_personal_inventions","health_privacy_finding_not_personalized","psychological_attributes_unmeasured"]}'::jsonb,
0.88,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_mustafa_suleyman_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='mustafa-suleyman'),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_mustafa_suleyman_100',
'{"packageId":"mustafa-suleyman-1.0.0","sourcesAdded":17,"claimsAdded":17,"claimsInPublicationManifest":13,"contextOnlyClaims":2,"relationshipsAdded":9,"eventsAdded":8,"publication":"draft","saturation":"incomplete"}'::jsonb,
'Draft package distinguishes Microsoft AI formation from transferred products, Inflection personnel and licensing, OpenAI dependence, retained Microsoft governance, institutional outputs and the March 2026 remit change.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
