import styles from "./Edition007Figure.module.css";
import type {CSSProperties} from "react";

export type Edition007FigureRecord={
 id:string; heading:string; title:string; evidence:string; caption:string;
 credit:string; proofLimit:string; sourceId:string; sourceUrl:string;
 kind:"platforms"|"chain"|"timeline"|"territory"|"artifact"|"route";
 image?:{src:string;alt:string;width:number;height:number};
};

export const edition007Figures:readonly Edition007FigureRecord[]=[
 {id:"ED007-FIG-01",heading:"Organic content can acquire an advertising engine",title:"Two platforms. Two authorization architectures.",evidence:"META · PARTNERSHIP ADS | TIKTOK · SPARK ADS",kind:"platforms",caption:"Separate systems require separate evidence records.",credit:"Source for the claim: Meta, Making it Easier for Brands and Creators to Collaborate on Instagram, February 21, 2024. Diagram by Institutions of One / RN Collins.",proofLimit:"Supports Meta’s published workflow and interface examples only; not proof of permission in any individual transaction.",sourceId:"META_MARKETPLACE",sourceUrl:"https://about.fb.com/news/2024/02/creator-marketplace-for-brands-and-creators-to-collaborate-on-instagram/"},
 {id:"ED007-FIG-02",heading:"“Online” is not one place",title:"Paid distribution adds an authority chain.",evidence:"CREATOR → POST → ADVERTISER → PAID DELIVERY",kind:"chain",caption:"Map the actors and permissions before comparing features.",credit:"Source for the claim: Meta, Making it Easier for Brands and Creators to Collaborate on Instagram, February 21, 2024. Diagram by Institutions of One / RN Collins.",proofLimit:"Supports Meta’s published workflow and interface examples only; not proof of permission in any individual transaction.",sourceId:"META_MARKETPLACE",sourceUrl:"https://about.fb.com/news/2024/02/creator-marketplace-for-brands-and-creators-to-collaborate-on-instagram/"},
 {id:"ED007-FIG-03",heading:"Duration governs the afterlife, not just the launch",title:"When month three ends, six different things may happen",evidence:"STOP NEW ADS|STOP ACTIVE DELIVERY|REMOVE CONTROLLED PLACEMENTS|RETAIN AGREED ARCHIVE|RECORD EXCEPTIONS|RENEW OR CLOSE",kind:"timeline",caption:"A campaign end date is not a complete asset closeout instruction.",credit:"Meta Help Center, What is the Meta Ad Library and how do I search it?; editorial diagram by Institutions of One / RN Collins.",proofLimit:"The Meta source describes public Ad Library availability. The six-gate closeout model is editorial guidance, not a universal platform rule or legal conclusion.",sourceId:"META_AD_LIBRARY",sourceUrl:"https://www.facebook.com/help/259468828226154/"},
 {id:"ED007-FIG-04",heading:"A global platform can still carry a bounded market",title:"Accessible worldwide is not the same as licensed worldwide",evidence:"ACCESSIBILITY|PAID TARGET|PRODUCT MARKET|BRAND ENTITY|LANGUAGE VERSION",kind:"territory",caption:"Territory becomes usable only when a team can translate it into settings, entities, products, languages, and files.",credit:"RN Collins, The Asset’s Afterlife; editorial diagram by Institutions of One / RN Collins.",proofLimit:"Conceptual distinction from the article; it does not state the territorial terms of any particular campaign.",sourceId:"ED007_CANONICAL_ARTICLE",sourceUrl:"https://polymath-rn-collins.beehiiv.com/p/the-assets-afterlife"},
 {id:"ED007-FIG-05",heading:"Exclusivity is a fence. Draw it.",title:"One public moment. Multiple commercial systems.",evidence:"TEAM UNIFORM|REEBOK VISIBILITY|JORDAN IDENTITY|NIKE RELATIONSHIP|TELEVISED CEREMONY",kind:"artifact",caption:"Illustrative photo: the U.S. men’s basketball team at the 1992 Olympics in Barcelona (David Robinson shooting a free throw against Puerto Rico, August 4, 1992). It is not the medal ceremony or the warm-up jacket. Logos from more than one company are visible on the uniforms and shoes. The jacket account comes from the Sotheby’s article and does not disclose every contract term.",credit:"Photo: Ken Hackman, U.S. Air Force, via the U.S. National Archives and Wikimedia Commons (public domain), cropped for this edition. Jacket account: Sotheby’s, The Ultimate Symbol of Michael Jordan’s Loyalty to Nike? A Reebok Jacket, June 20, 2023.",proofLimit:"The photo is illustrative and does not show the jacket, the medal ceremony or any Reebok mark. The Sotheby’s article supports the account that Jordan used the U.S. flag to obscure the Reebok mark and that safety pins remained with the jacket. It is not an IOC adjudication or a legal conclusion about sponsorship obligations.",sourceId:"SOTHEBYS_JORDAN_REEBOK",sourceUrl:"https://www.sothebys.com/en/articles/the-ultimate-symbol-of-michael-jordans-loyalty-to-nike-a-reebok-jacket",image:{src:"/edit-images/007/dream-team-1992-barcelona.jpg",alt:"A U.S. men’s basketball player in a dark USA jersey shoots a free throw during a 1992 Olympic game in Barcelona while teammates and opponents line up along the lane.",width:1200,height:927}},
 {id:"ED007-FIG-06",heading:"Draw the route before pricing the journey",title:"The route card",evidence:"MECHANISM|IDENTITY|PLACEMENT|EDITS|DURATION|TERRITORY|EXCLUSIVITY|EVIDENCE",kind:"route",caption:"Price the commercial route around the file, not the file in isolation.",credit:"RN Collins, The Asset’s Afterlife; worksheet design by Institutions of One / RN Collins.",proofLimit:"Educational workflow, not legal advice or a substitute for reviewing the governing agreement and live platform controls.",sourceId:"ED007_CANONICAL_ARTICLE",sourceUrl:"https://polymath-rn-collins.beehiiv.com/p/the-assets-afterlife"}
] as const;

export function edition007FigureForHeading(heading:string){return edition007Figures.find(item=>item.heading===heading)}

function Visual({item}:{item:Edition007FigureRecord}){
 const fields=item.evidence.split("|");
 if(item.kind==="artifact")return <div className={styles.artifact}>{item.image&&<img src={item.image.src} alt={item.image.alt} width={item.image.width} height={item.image.height} loading="lazy"/>}<ol>{fields.map(field=><li key={field}>{field}</li>)}</ol></div>;
 if(item.kind==="chain")return <ol className={styles.chain}>{fields[0].split(" → ").map(field=><li key={field}>{field}</li>)}</ol>;
 if(item.kind==="timeline")return <ol className={styles.timeline}>{fields.map((field,index)=><li key={field}><b>{String(index+1).padStart(2,"0")}</b><span>{field}</span></li>)}</ol>;
 if(item.kind==="territory")return <div className={styles.territory}>{fields.map((field,index)=><div key={field} style={{"--inset":`${index*7}%`} as CSSProperties}>{field}</div>)}</div>;
 if(item.kind==="route")return <div className={styles.route}>{fields.map((field,index)=><div key={field}><b>{String(index+1).padStart(2,"0")}</b><span>{field}</span><i aria-hidden="true"/></div>)}</div>;
 return <div className={styles.platforms}>{fields.map((field,index)=><div key={field}><small>{index===0?"01 · PLATFORM RECORD":"02 · SEPARATE RECORD"}</small><strong>{field}</strong></div>)}</div>;
}

export function Edition007Figure({item}:{item:Edition007FigureRecord}){return <figure className={styles.figure} data-kind={item.kind} data-figure-id={item.id}><header><small>EDITION 007 · FIGURE {item.id.slice(-2)}</small><h3>{item.title}</h3></header><Visual item={item}/><figcaption><p>{item.caption}</p><small>Credit: {item.credit} <a href={item.sourceUrl} target="_blank" rel="noopener noreferrer">Source record ↗</a></small><details><summary>What the record shows</summary><p>{item.proofLimit}</p></details></figcaption></figure>}
