-- Josephus Allmond public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, attribute collective labor, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Virginia inaugural Chief Energy Officer operating through gubernatorial, cabinet, agency and regulatory coordination.',
    "summary"='A jurisdiction- and authority-bounded account separating Executive Order 14, Allmond''s appointment, the Governor''s retained authority, office staff, state agencies, regulators, PJM, former SELC work and community governance.',
    "inclusionRationale"='Tests a government first-role claim without converting appointment into role authorship, unilateral control, sole labor, causal performance, ownership or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.89,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='josephus-allmond';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_jal10_eo','https://www.governor.virginia.gov/media/governorvirginiagov/governor-of-virginia/pdf/eo/EO-14-ESTABLISHING-THE-ROLE-OF-CHIEF-ENERGY-OFFICER.pdf','Executive Order 14: Establishing the Role of Chief Energy Officer','Governor of Virginia','executive_order','2026-03-25T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_appt','https://www.governor.virginia.gov/newsroom/news-releases/2026/march-releases/name-1114943-en.html','Governor Spanberger Announces New Cabinet-Level Chief Energy Officer','Governor of Virginia','primary_appointment_release','2026-03-25T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_cab','https://www.governor.virginia.gov/cabinet/name-1114976-en.html','Chief Energy Officer cabinet biography','Governor of Virginia','primary_cabinet_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_bio','https://www.energychief.virginia.gov/about-the-chief/','About the Chief','Office of the Chief Energy Officer','primary_office_biography',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_reg','https://www.energychief.virginia.gov/regulatory-engagement/','Regulatory Engagement','Office of the Chief Energy Officer','primary_filing_index',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_t1','https://www.energychief.virginia.gov/media/governorvirginiagov/chief-energy-officer/pdf/PUR-2026-00056-Comments-from-the-Chief-Energy-Officer-for-the-Governor-of-Virginia.pdf','Comments of the Chief Energy Officer in PUR-2026-00056','Virginia State Corporation Commission','regulatory_filing','2026-07-09T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_ll','https://www.energychief.virginia.gov/media/governorvirginiagov/chief-energy-officer/pdf/26.06.21_PUR-2026-00011_Large-Load_CEO-Letter-to-SCC.pdf','Chief Energy Officer letter in PUR-2026-00011','Virginia State Corporation Commission','regulatory_filing','2026-06-21T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_pjm','https://www.energychief.virginia.gov/media/governorvirginiagov/chief-energy-officer/pdf/RBP-Ltr%3B-VA-CEO-to-PJM-20260517.pdf','Virginia Chief Energy Officer letter to PJM','Office of the Chief Energy Officer','primary_government_letter','2026-05-17T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_selc','https://www.selc.org/press-release/allmond-joins-spanberger-administration-as-first-ever-chief-energy-officer-in-virginia/','Allmond joins Spanberger administration','Southern Environmental Law Center','former_employer_release','2026-03-25T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_eq','https://www.selc.org/news/how-associate-attorney-josephus-allmond-is-tackling-inequities/','How Josephus Allmond is tackling inequities','Southern Environmental Law Center','staff_interview','2023-02-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_scc','https://www.scc.virginia.gov/docketsearch/DOCS/7vkz01%21.PDF','Hearing Examiner report PUR-2023-00069','Virginia State Corporation Commission','tribunal_record','2023-11-06T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_ceur','https://apps.dlas.virginia.gov/User_db/frmView.aspx?ViewId=6474&s=7','Members of the Commission on Electric Utility Regulation','Virginia Division of Legislative Services','legislative_membership_record',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_duke','https://law.duke.edu/news/class-notes-march-2026','Class Notes March 2026','Duke University School of Law','primary_alumni_record','2026-03-24T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_jal10_cacf','https://cacfonline.org/charlottesville-area-community-foundation-welcomes-three-new-board-members/','Community Foundation welcomes three new board members','Charlottesville Area Community Foundation','primary_board_release','2024-07-05T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_jal10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'role_creation','Executive Order 14 created the Chief Energy Officer position within the Office of the Governor on 25 March 2026.','role_origin','primary_record','unreviewed',NULL,'A cabinet-level Virginia office created by Executive Order 14.','No pre-existing statutory independence or permanent tenure.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jal10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'jurisdictional_first','Spanberger appointed Allmond as the position inaugural holder.','firstness','corroborated','unreviewed',NULL,'Virginia first Chief Energy Officer.','No United States, worldwide or profession-wide firstness.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jal10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'role_authorship_boundary','The governor created the role through executive authority; reviewed records do not establish Allmond as its designer.','role_origin','primary_record','unreviewed',NULL,'Appointed to a newly created role.','No claim that Allmond invented, negotiated or personally built the role.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jal10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'authority_boundary','Executive Order 14 reserves the governor continuing and ultimate authority.','time_bounded_authority','primary_record','unreviewed',NULL,'Cabinet-level officer operating under gubernatorial authority.','No independent sovereignty or unilateral statewide control.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jal10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'coordination_role','The role coordinates affordability, reliability and clean-energy work across named governmental, regulatory and market institutions.','distributed_governance','primary_record','unreviewed',NULL,'Coordinates Virginia energy policy across named bodies.','No sole control of agencies, PJM, utilities, legislation or rates.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jal10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'distributed_labor','Louise White serves as deputy and the office includes additional staff.','distributed_creation','primary_record','unreviewed',NULL,'Leads an office with a deputy and staff.','No sole labor or sole authorship of office output.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jal10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'prior_legal_role','Allmond previously worked at SELC on utility-regulatory, solar and environmental-justice matters.','formal_role','corroborated','unreviewed',NULL,'Former SELC attorney with Virginia utility-regulatory experience.','No attribution of all SELC matters or results to him.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jal10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'commission_role','Allmond served as a citizen member of CEUR before entering the cabinet.','formal_role','primary_record','unreviewed',NULL,'Former citizen member of CEUR.','No sole commission authority or ownership of commission work.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jal10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'regulatory_engagement','The office has filed comments and letters in named SCC and PJM matters since the appointment.','institutional_output','primary_record','unreviewed',NULL,'The office has engaged in named regulatory proceedings.','No final victory, rate savings or causal performance absent decisions and measurement.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_jal10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'claim_restriction','No reviewed public record establishes Allmond employment terms, compensation, budget authority, unilateral agency control, personal ownership, sole authorship, quantified attributable savings or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified or incomplete.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_jal10_c01','obs_claim_jal10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.governor.virginia.gov/media/governorvirginiagov/governor-of-virginia/pdf/eo/EO-14-ESTABLISHING-THE-ROLE-OF-CHIEF-ENERGY-OFFICER.pdf' LIMIT 1),'supports',NULL,'Executive Order 14','Creation and authority bounded.',CURRENT_TIMESTAMP),
('obs_ev_jal10_c02','obs_claim_jal10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.governor.virginia.gov/newsroom/news-releases/2026/march-releases/name-1114943-en.html' LIMIT 1),'supports',NULL,'Appointment release','Virginia-specific inaugural role.',CURRENT_TIMESTAMP),
('obs_ev_jal10_c03','obs_claim_jal10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.governor.virginia.gov/media/governorvirginiagov/governor-of-virginia/pdf/eo/EO-14-ESTABLISHING-THE-ROLE-OF-CHIEF-ENERGY-OFFICER.pdf' LIMIT 1),'supports',NULL,'Executive Order 14','Governor creates role.',CURRENT_TIMESTAMP),
('obs_ev_jal10_c04','obs_claim_jal10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.governor.virginia.gov/media/governorvirginiagov/governor-of-virginia/pdf/eo/EO-14-ESTABLISHING-THE-ROLE-OF-CHIEF-ENERGY-OFFICER.pdf' LIMIT 1),'supports',NULL,'Authority clause','Ultimate authority retained by governor.',CURRENT_TIMESTAMP),
('obs_ev_jal10_c05','obs_claim_jal10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.governor.virginia.gov/media/governorvirginiagov/governor-of-virginia/pdf/eo/EO-14-ESTABLISHING-THE-ROLE-OF-CHIEF-ENERGY-OFFICER.pdf' LIMIT 1),'supports',NULL,'Directive','Coordination rather than sole control.',CURRENT_TIMESTAMP),
('obs_ev_jal10_c06','obs_claim_jal10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.energychief.virginia.gov/about-the-chief/' LIMIT 1),'supports',NULL,'Office staff page','Deputy and staff preserved.',CURRENT_TIMESTAMP),
('obs_ev_jal10_c07','obs_claim_jal10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.selc.org/press-release/allmond-joins-spanberger-administration-as-first-ever-chief-energy-officer-in-virginia/' LIMIT 1),'supports',NULL,'Former-employer release','Prior role and institutional work bounded.',CURRENT_TIMESTAMP),
('obs_ev_jal10_c08','obs_claim_jal10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://apps.dlas.virginia.gov/User_db/frmView.aspx?ViewId=6474&s=7' LIMIT 1),'supports',NULL,'CEUR membership','Collective commission role.',CURRENT_TIMESTAMP),
('obs_ev_jal10_c09','obs_claim_jal10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.energychief.virginia.gov/regulatory-engagement/' LIMIT 1),'supports',NULL,'Regulatory filing index','Activity is not outcome.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_jal10_gov',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'organization','Office of Governor Abigail Spanberger','chief_energy_officer_and_cabinet_member','2026-03-25T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.governor.virginia.gov/newsroom/news-releases/2026/march-releases/name-1114943-en.html' LIMIT 1),NULL,'Governor retains ultimate authority',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jal10_office',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'organization','Office of the Chief Energy Officer','office_leader','2026-03-25T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.energychief.virginia.gov/about-the-chief/' LIMIT 1),NULL,'Deputy, staff and partner institutions preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jal10_selc',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'organization','Southern Environmental Law Center','former_staff_attorney','2020-01-01T00:00:00Z','2026-03-25T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.selc.org/press-release/allmond-joins-spanberger-administration-as-first-ever-chief-energy-officer-in-virginia/' LIMIT 1),NULL,'Clients, co-counsel and institutional work preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jal10_ceur',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'commission','Commission on Electric Utility Regulation','former_citizen_member','2024-01-01T00:00:00Z','2026-03-25T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://apps.dlas.virginia.gov/User_db/frmView.aspx?ViewId=6474&s=7' LIMIT 1),NULL,'Collective legislative commission',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jal10_scc',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'regulator','Virginia State Corporation Commission','advocate_then_government_filer','2021-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.energychief.virginia.gov/regulatory-engagement/' LIMIT 1),NULL,'SCC retains adjudicatory authority',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jal10_pjm',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'regional_organization','PJM Interconnection and PJM states','governmental_engagement_and_collaboration','2026-03-25T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.energychief.virginia.gov/media/governorvirginiagov/chief-energy-officer/pdf/RBP-Ltr%3B-VA-CEO-to-PJM-20260517.pdf' LIMIT 1),NULL,'No ownership or unilateral market authority',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_jal10_cacf',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'organization','Charlottesville Area Community Foundation','governing_board_member','2024-07-05T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://cacfonline.org/charlottesville-area-community-foundation-welcomes-three-new-board-members/' LIMIT 1),NULL,'Foundation assets and outcomes remain institutional',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_jal10_2020',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'credential_and_role','Duke JD and SELC transition','Allmond earned a Duke Law JD and began SELC work around this period.','2020-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://law.duke.edu/news/class-notes-march-2026' LIMIT 1),NULL,'Exact employment start remains approximate',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_jal10_2024',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'institutional_service','CEUR and community governance documented','Public records identify commission and community-board service.','2024-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://apps.dlas.virginia.gov/User_db/frmView.aspx?ViewId=6474&s=7' LIMIT 1),NULL,'Institution-specific authority only',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_jal10_appointment',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'appointment','Chief Energy Officer role created and filled','Executive Order 14 created the cabinet-level role and Spanberger appointed Allmond.','2026-03-25T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.governor.virginia.gov/newsroom/news-releases/2026/march-releases/name-1114943-en.html' LIMIT 1),NULL,'Virginia-specific inaugural role',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_jal10_pjm',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'regulatory_engagement','Office engages PJM','Office records document regional-market engagement.','2026-05-17T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.energychief.virginia.gov/media/governorvirginiagov/chief-energy-officer/pdf/RBP-Ltr%3B-VA-CEO-to-PJM-20260517.pdf' LIMIT 1),NULL,'No outcome or unilateral authority inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_jal10_large',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'regulatory_engagement','Large-load filing','Office submitted a letter in the SCC large-load proceeding.','2026-06-21T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.energychief.virginia.gov/media/governorvirginiagov/chief-energy-officer/pdf/26.06.21_PUR-2026-00011_Large-Load_CEO-Letter-to-SCC.pdf' LIMIT 1),NULL,'Policy activity, not adjudicated success',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_jal10_t1',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'regulatory_filing','Rider T-1 comments filed','Allmond and Deputy Louise White signed administration comments.','2026-07-09T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.energychief.virginia.gov/media/governorvirginiagov/chief-energy-officer/pdf/PUR-2026-00056-Comments-from-the-Chief-Energy-Officer-for-the-Governor-of-Virginia.pdf' LIMIT 1),NULL,'Co-signed institutional filing; outcome unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_josephus_allmond_100','josephus-allmond-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'1.0.0','research/observatory/dossiers/josephus-allmond-1.0.0.md','340612ca76b41439afa9e5c33add1f49f55b392c',
'{"claimIds":["obs_claim_jal10_c01","obs_claim_jal10_c02","obs_claim_jal10_c03","obs_claim_jal10_c04","obs_claim_jal10_c05","obs_claim_jal10_c06","obs_claim_jal10_c07","obs_claim_jal10_c08","obs_claim_jal10_c09","obs_claim_jal10_c10"],"relationshipIds":["obs_rel_jal10_gov","obs_rel_jal10_office","obs_rel_jal10_selc","obs_rel_jal10_ceur","obs_rel_jal10_scc","obs_rel_jal10_pjm","obs_rel_jal10_cacf"],"eventIds":["obs_event_jal10_2020","obs_event_jal10_2024","obs_event_jal10_appointment","obs_event_jal10_pjm","obs_event_jal10_large","obs_event_jal10_t1"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","virginia_specific_firstness_only","governor_retains_ultimate_authority","distributed_government_and_regulatory_labor","appointment_terms_unverified","budget_and_compensation_unverified","regulatory_outcomes_unresolved","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.89,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_josephus_allmond_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='josephus-allmond' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_josephus_allmond_100',
'{"packageId":"josephus-allmond-1.0.0","claimsLoaded":10,"relationshipsLoaded":7,"eventsLoaded":6,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Jurisdictional firstness, executive authority, distributed governance, regulatory outcomes, labor, economics, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
