-- Simon Cook public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, attribute collective labor, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='LIONS chief executive operating within Informa, multi-brand teams, juries and partner institutions.',
    "summary"='A role-, entity-, awards-, rights- and time-bounded account separating executive leadership from ownership, jury labor, parent governance and institutional outcomes.',
    "inclusionRationale"='Tests Cannes Lions leadership without converting executive visibility or credited framework work into personal role construction, ownership, sole authorship, causal performance or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.88,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='simon-cook';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_sim10_bio','https://www.canneslions.com/festival/speakers/simon-cook-s1-112589','Simon Cook','Cannes Lions','official_biography','2026-06-24T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_sim10_lions','https://www.lions.co/en/dei','Diversity Equity and Inclusion','LIONS','institutional_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_sim10_jury','https://www.canneslions.com/news/2021-juries-announced','Cannes Lions announces 2021 jury members','Cannes Lions','institutional_release','2021-04-12T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_sim10_integrity','https://www.canneslions.com/statement-cannes-lions-introduces-global-integrity-standards','Cannes Lions Introduces Global Integrity Standards','Cannes Lions','institutional_statement','2025-07-10T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_sim10_2026','https://www.canneslions.com/news/73rd-cannes-lions-international-festival-of-creativity-opens-monday','73rd Cannes Lions International Festival of Creativity opens Monday','Cannes Lions','institutional_release','2026-06-20T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_sim10_brazil','https://www.canneslions.com/news/jurors','A response from Simon Cook','Cannes Lions','attributed_response',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_sim10_results','https://www.informa.com/globalassets/documents/investor-relations/2025/informa-2024-full-year-results.pdf','Informa 2024 Preliminary Full-Year Results','Informa','results','2025-03-06T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_sim10_offer','https://www.informa.com/globalassets/documents/investor-relations/2024/announcement-of-recommended-cash-offer-for-ascential-plc.pdf','Recommended Cash Offer for Ascential plc','Informa','transaction_announcement','2024-07-24T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_sim10_agm','https://www.informa.com/globalassets/documents/investor-relations/general-meeting/2025/informa-notice-of-agm-2025.pdf','Informa Notice of AGM 2025','Informa','governance_record','2025-05-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_sim10_appt','https://lbbonline.com/news/simon-cook-announced-as-managing-director-of-cannes-lions','Simon Cook Announced as Managing Director of Cannes Lions','Little Black Book','appointment_reporting','2019-03-27T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_sim10_rac','https://www.raconteur.net/marketing-sales/ceo-on-the-spot-10-questions-with-cannes-lions-simon-cook','CEO on the spot: Simon Cook','Raconteur','interview','2024-05-22T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_sim10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'formal_role','LIONS currently identifies Cook as CEO of the organization behind Cannes Lions WARC Effie Contagious and Acuity Pricing.','formal_role','primary_record','unreviewed',NULL,'CEO of LIONS.','No personal ownership or unilateral control.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_sim10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'role_chronology','Cook became Cannes Lions managing director in 2019 and CEO two years later.','time_bounded_authority','reported_and_attributed','unreviewed',NULL,'Progressed through awards leadership to managing director and CEO.','No title authorship or worldwide-first claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_sim10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'credited_system_work','Appointment reporting credits Cook with the Tracks framework and oversight of many awards introductions.','distributed_creation','reported','unreviewed',NULL,'Was publicly credited with major awards-system work.','No sole authorship permanent IP ownership or complete labor attribution.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_sim10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'entity_boundary','Informa acquired Ascential in October 2024 and identifies the acquired business as owner of Cannes Lions.','entity_boundary','primary_record','unreviewed',NULL,'Leads LIONS within Informa corporate structure.','No personal ownership or personal-wealth conversion.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_sim10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'distributed_labor','LIONS operates through multiple brands teams juries shared services and parent infrastructure.','distributed_creation','primary_record','unreviewed',NULL,'Leads a multi-brand institutional platform.','No personally owned portfolio or sole operating credit.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_sim10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'jury_boundary','Cannes Lions judging depends on named jury presidents jurors and institutional procedures.','governance_boundary','primary_record','unreviewed',NULL,'Has executive responsibility alongside separate jury labor.','No claim Cook personally made every judging decision.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_sim10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'adverse_evidence','Winning work was withdrawn in 2025 after concerns involving manipulation synthetic media and AI.','adverse_evidence','primary_record','unreviewed',NULL,'Led during an institutional awards-integrity failure and response.','No personal misconduct knowledge motive or sole-causation inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_sim10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'governance_response','Cannes Lions announced strengthened integrity standards and possible sanctions after the withdrawals.','formal_process','primary_record','unreviewed',NULL,'The organization introduced strengthened integrity controls.','No sole authorship or demonstrated future effectiveness.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_sim10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'representation_acknowledgement','Cook acknowledged that Cannes Lions missed the mark on Brazilian jury representation.','adverse_evidence','attributed_statement','unreviewed',NULL,'Publicly acknowledged an institutional representation shortfall.','No generalized discrimination or personality inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_sim10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'claim_restriction','No reviewed record establishes beneficial ownership complete authority compensation award IP transaction proceeds isolated performance or psychology.','claim_restriction','observed','unreviewed',NULL,'Those domains remain unverified.','Absence of public evidence is not evidence of absence.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_sim10_c01','obs_claim_sim10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/festival/speakers/simon-cook-s1-112589' LIMIT 1),'supports',NULL,'Official biography','Current title and group remit.',CURRENT_TIMESTAMP),
('obs_ev_sim10_c02','obs_claim_sim10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/simon-cook-announced-as-managing-director-of-cannes-lions' LIMIT 1),'supports',NULL,'Appointment report','Historic title chronology.',CURRENT_TIMESTAMP),
('obs_ev_sim10_c03','obs_claim_sim10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/simon-cook-announced-as-managing-director-of-cannes-lions' LIMIT 1),'supports',NULL,'Appointment report','Credited work remains distributed.',CURRENT_TIMESTAMP),
('obs_ev_sim10_c04','obs_claim_sim10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.informa.com/globalassets/documents/investor-relations/2025/informa-2024-full-year-results.pdf' LIMIT 1),'supports',NULL,'Ascential acquisition','Corporate ownership boundary.',CURRENT_TIMESTAMP),
('obs_ev_sim10_c05','obs_claim_sim10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.lions.co/en/dei' LIMIT 1),'supports',NULL,'Institutional identity','Brands and parent structure.',CURRENT_TIMESTAMP),
('obs_ev_sim10_c06','obs_claim_sim10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/news/2021-juries-announced' LIMIT 1),'supports',NULL,'Jury roster','Separate jury labor.',CURRENT_TIMESTAMP),
('obs_ev_sim10_c07','obs_claim_sim10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/statement-cannes-lions-introduces-global-integrity-standards' LIMIT 1),'supports',NULL,'Institutional statement','Withdrawals and integrity concerns.',CURRENT_TIMESTAMP),
('obs_ev_sim10_c08','obs_claim_sim10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/statement-cannes-lions-introduces-global-integrity-standards' LIMIT 1),'supports',NULL,'Institutional statement','Governance response.',CURRENT_TIMESTAMP),
('obs_ev_sim10_c09','obs_claim_sim10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/news/jurors' LIMIT 1),'supports',NULL,'Attributed response','Bounded representation acknowledgement.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_sim10_lions',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'organization','LIONS and Informa','current_ceo_inside_parent_structure',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/festival/speakers/simon-cook-s1-112589' LIMIT 1),NULL,'Parent board capital employees brands data and IP preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_sim10_cannes',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'organization','Cannes Lions','historic_and_current_executive_oversight',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/simon-cook-announced-as-managing-director-of-cannes-lions' LIMIT 1),NULL,'Festival employees partners awards and rights preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_sim10_brands',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'brand_network','WARC Effie Contagious and Acuity Pricing','group_executive_oversight',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.lions.co/en/dei' LIMIT 1),NULL,'Separate histories teams products data clients and rights',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_sim10_juries',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'governance_network','Cannes Lions juries','executive_and_awards_governance_relationship',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/news/2021-juries-announced' LIMIT 1),NULL,'Jury presidents jurors and decisions separately attributed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_sim10_festivals',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'division','Informa Festivals','operating_division_relationship','2024-10-09T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.informa.com/globalassets/documents/investor-relations/general-meeting/2025/informa-notice-of-agm-2025.pdf' LIMIT 1),NULL,'Division leadership shared services and finances preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_sim10_palais',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'partner','Palais des Festivals and Cannes','venue_and_institutional_partnership',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/festival/speakers/simon-cook-s1-112589' LIMIT 1),NULL,'City venue contracts and counterparty work preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_sim10_stakeholders',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'institutional_network','Entrants agencies brands and industry community','platform_and_stakeholder_relationship',NULL,NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/statement-cannes-lions-introduces-global-integrity-standards' LIMIT 1),NULL,'Creative work claims rights results and misconduct remain holder-specific',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_sim10_2019',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'appointment','Managing director appointment announced','Cook was announced as Cannes Lions managing director.','2019-03-27T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://lbbonline.com/news/simon-cook-announced-as-managing-director-of-cannes-lions' LIMIT 1),NULL,'No title-authorship inference',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_sim10_2021',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'appointment','Cannes Lions CEO period begins','Public interview chronology places the CEO transition two years after 2019.','2021-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.raconteur.net/marketing-sales/ceo-on-the-spot-10-questions-with-cannes-lions-simon-cook' LIMIT 1),NULL,'Employment terms unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_sim10_2023',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'role_expansion','Combined LIONS group role documented','Cook publicly described leading the combined brand division.','2023-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.lions.co/en/dei' LIMIT 1),NULL,'Brand teams and parent governance preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_sim10_2024',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'acquisition','Informa acquisition of Ascential completed','Informa completed the acquisition on October 9.','2024-10-09T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.informa.com/globalassets/documents/investor-relations/2025/informa-2024-full-year-results.pdf' LIMIT 1),NULL,'Transaction consideration is not Cook proceeds or wealth',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_sim10_2025',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'integrity_incident','Winning work withdrawn during 2025 integrity concerns','Cannes Lions recorded withdrawals involving manipulation synthetic media and AI concerns.','2025-06-20T00:00:00Z','month','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/statement-cannes-lions-introduces-global-integrity-standards' LIMIT 1),NULL,'Individual liability unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_sim10_2026',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'governance_implementation','Strengthened standards used for 2026 festival','Festival communications described strengthened integrity standards.','2026-06-20T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.canneslions.com/news/73rd-cannes-lions-international-festival-of-creativity-opens-monday' LIMIT 1),NULL,'Effectiveness and causal allocation unresolved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_simon_cook_100','simon-cook-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'1.0.0','research/observatory/dossiers/simon-cook-1.0.0.md','ce2ee758a80703e7d32247643642465951137bed',
'{"claimIds":["obs_claim_sim10_c01","obs_claim_sim10_c02","obs_claim_sim10_c03","obs_claim_sim10_c04","obs_claim_sim10_c05","obs_claim_sim10_c06","obs_claim_sim10_c07","obs_claim_sim10_c08","obs_claim_sim10_c09","obs_claim_sim10_c10"],"relationshipIds":["obs_rel_sim10_lions","obs_rel_sim10_cannes","obs_rel_sim10_brands","obs_rel_sim10_juries","obs_rel_sim10_festivals","obs_rel_sim10_palais","obs_rel_sim10_stakeholders"],"eventIds":["obs_event_sim10_2019","obs_event_sim10_2021","obs_event_sim10_2023","obs_event_sim10_2024","obs_event_sim10_2025","obs_event_sim10_2026"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","current_title_is_lions_ceo","title_authorship_unverified","informa_ownership_boundary","distributed_brand_and_jury_labor","transaction_value_not_personal_wealth","integrity_withdrawals_bounded","future_control_effectiveness_unverified","ip_contracts_and_economics_unverified","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.88,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_simon_cook_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='simon-cook' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_simon_cook_100',
'{"packageId":"simon-cook-1.0.0","claimsLoaded":10,"relationshipsLoaded":7,"eventsLoaded":6,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Current title, parent ownership, distributed brand and jury labor, transaction value, integrity failures, corrective controls, IP, contracts, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
