-- Klitos Teklos public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Tory Burch’s first Chief Brand Officer in a newly consolidated, company-specific role.',
    "summary"='A company-specific role-novelty case separating title creation, inherited functions, shared authority, ownership, labor and causal performance.',
    "inclusionRationale"='Tests how a newly created executive title can reorganize existing functions without supporting worldwide firstness, personal ownership or sole causation.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.78,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='klitos-teklos';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_kt10_wwd','https://wwd.com/business-news/human-resources/tory-burch-names-klitos-teklos-chief-brand-officer-1239054554/','Tory Burch Appoints Klitos Teklos Chief Brand Officer','WWD','journalism','2026-07-07T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_kt10_bof','https://www.businessoffashion.com/news/luxury/tory-burch-names-first-chief-brand-officer/','Tory Burch Names First Chief Brand Officer','Business of Fashion','journalism','2026-07-07T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_kt10_fu','https://fashionunited.uk/news/people/tory-burch-names-klitos-teklos-chief-brand-officer/2026070889056','Tory Burch names Klitos Teklos chief brand officer','FashionUnited','journalism','2026-07-08T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_kt10_self','https://www.linkedin.com/posts/klitosteklos_tory-burch-appoints-klitos-teklos-chief-brand-activity-7482395717081387008-NNk2','Klitos Teklos appointment announcement','Klitos Teklos / LinkedIn','first_person_announcement',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_kt10_studio','https://www.klitosteklos.com/about','Tēklos Studio biography','Tēklos Studio','first_party_profile',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_kt10_profile','https://www.linkedin.com/in/klitosteklos','Klitos Teklos professional profile','LinkedIn','first_person_profile',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_kt10_lat','https://www.latimes.com/lifestyle/image/story/2026-05-14/for-tory-burch-20-year-fashion-career-is-sport-driven-by-endurance-discipline-grit','For Tory Burch, a 20-year fashion career is a sport','Los Angeles Times','editorial_interview','2026-05-14T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP),
('obs_src_kt10_bp','https://www.beautypackaging.com/breaking-news/sabrina-carpenter-unveils-sweet-tooth-caramel-dream-fragrance/','Sabrina Carpenter Unveils Sweet Tooth: Caramel Dream','Beauty Packaging','trade_journalism','2023-08-22T00:00:00Z','2026-07-26T00:00:00Z',false,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_kt10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'role_appointment','Tory Burch appointed Teklos Chief Brand Officer effective July 7, 2026.','role_history','observed','unreviewed',NULL,'Teklos became Tory Burch Chief Brand Officer in July 2026.','Do not imply earlier tenure or permanent current status.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_kt10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'firstness_boundary','Contemporaneous reports identify the position as newly created and Teklos as Tory Burch’s first holder.','role_firstness','observed','unreviewed',NULL,'He is the first publicly identified Tory Burch Chief Brand Officer.','Worldwide and industry firstness are prohibited.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_kt10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'delegated_remit','The announced remit includes global brand strategy and oversight of global marketing, social media and visual merchandising.','delegated_authority','observed','unreviewed',NULL,'Teklos has announced oversight of specified brand functions.','Oversight does not prove ownership, sole labor, budget control or unilateral authority.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_kt10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'shared_authority','Teklos reports to Tory Burch and Pierre-Yves Roussel and partners with Honor Brodie.','distributed_authority','observed','unreviewed',NULL,'The role sits within a shared executive and creative structure.','Do not depict Teklos as replacing or controlling the other leaders.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_kt10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'institutional_boundary','The Tory Burch company, brand, leaders, teams, channels and relevant functions predate the appointment.','institutional_system','observed','unreviewed',NULL,'Teklos entered an established organization and inherited existing functions.','Do not say he created the brand apparatus from zero.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_kt10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'prior_venture','Teklos founded Tēklos Studio in 2023 and describes a residency-based brand consultancy model.','portfolio_boundary','attributed','unreviewed',NULL,'Teklos publicly presents himself as founder of Tēklos Studio.','Founder label does not prove current equity, sole labor, revenue or legal form.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_kt10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'economics_boundary','No reviewed record establishes Tory Burch equity, a board seat, compensation, budget authority, employment terms or IP rights for Teklos.','claim_restriction','observed','unreviewed',NULL,'Public evidence establishes appointment and remit, not private economics or ownership.','Absence of public evidence is not proof that no rights exist.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_kt10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'psychology_boundary','No reviewed source validly measures Teklos’s psychological constructs.','claim_restriction','observed','unreviewed',NULL,'The case measures public roles, relationships and events, not psychology.','Do not infer motivation, cognition, resilience, personality or mental state.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_kt10_c01','obs_claim_kt10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://wwd.com/business-news/human-resources/tory-burch-names-klitos-teklos-chief-brand-officer-1239054554/' LIMIT 1),'supports',NULL,'Appointment report','Contemporaneous report quoting company.',CURRENT_TIMESTAMP),
('obs_ev_kt10_c02','obs_claim_kt10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.businessoffashion.com/news/luxury/tory-burch-names-first-chief-brand-officer/' LIMIT 1),'supports',NULL,'Headline and appointment description','Company-specific firstness only.',CURRENT_TIMESTAMP),
('obs_ev_kt10_c03','obs_claim_kt10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://fashionunited.uk/news/people/tory-burch-names-klitos-teklos-chief-brand-officer/2026070889056' LIMIT 1),'supports',NULL,'Role description','Functions and intended outcomes kept separate.',CURRENT_TIMESTAMP),
('obs_ev_kt10_c04','obs_claim_kt10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://fashionunited.uk/news/people/tory-burch-names-klitos-teklos-chief-brand-officer/2026070889056' LIMIT 1),'supports',NULL,'Reporting-line paragraph','Shared authority preserved.',CURRENT_TIMESTAMP),
('obs_ev_kt10_c05','obs_claim_kt10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.latimes.com/lifestyle/image/story/2026-05-14/for-tory-burch-20-year-fashion-career-is-sport-driven-by-endurance-discipline-grit' LIMIT 1),'supports',NULL,'Pre-appointment interview','Documents continuing founder involvement and pre-existing system.',CURRENT_TIMESTAMP),
('obs_ev_kt10_c06','obs_claim_kt10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.klitosteklos.com/about' LIMIT 1),'supports',NULL,'Studio biography','First-party venture description.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_kt10_tbllc',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'organization','Tory Burch LLC','chief_brand_officer','2026-07-07T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://wwd.com/business-news/human-resources/tory-burch-names-klitos-teklos-chief-brand-officer-1239054554/' LIMIT 1),NULL,'Contract, equity and board authority unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_kt10_tory',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'person','Tory Burch','reports_to_and_collaborates','2026-07-07T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://fashionunited.uk/news/people/tory-burch-names-klitos-teklos-chief-brand-officer/2026070889056' LIMIT 1),NULL,'Burch retains founder, executive-chair and chief-creative roles',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_kt10_roussel',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'person','Pierre-Yves Roussel','reports_to_and_partners','2026-07-07T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://wwd.com/business-news/human-resources/tory-burch-names-klitos-teklos-chief-brand-officer-1239054554/' LIMIT 1),NULL,'CEO decision split unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_kt10_brodie',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'person','Honor Brodie','creative_partner','2026-07-07T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://fashionunited.uk/news/people/tory-burch-names-klitos-teklos-chief-brand-officer/2026070889056' LIMIT 1),NULL,'Collaboration does not disclose hierarchy or rights',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_kt10_studio',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'organization','Tēklos Studio','founder','2023-01-01T00:00:00Z','2026-07-07T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.klitosteklos.com/about' LIMIT 1),NULL,'Post-appointment status, ownership, staff and economics incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_kt10_elc',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'organization','The Estée Lauder Companies','former_creative_leader',NULL,'2023-01-01T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.linkedin.com/in/klitosteklos' LIMIT 1),NULL,'Exact employment and project attribution incomplete',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_kt10_elc',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'role_history','Multi-brand creative leadership','Profiles place Teklos in senior Estée Lauder-related creative work before founding his studio.','2018-01-01T00:00:00Z','year_approximate','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.linkedin.com/in/klitosteklos' LIMIT 1),NULL,'Exact personnel records unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_kt10_studio',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'venture_launch','Tēklos Studio founded','Teklos’s first-party biography dates the studio to 2023.','2023-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.klitosteklos.com/about' LIMIT 1),NULL,'Exact formation date and entity unavailable',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_kt10_campaign',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'project_credit','Fragrance campaign credit','Trade reporting credits Teklos as chief creative and brand architect within a multi-party campaign.','2023-08-22T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.beautypackaging.com/breaking-news/sabrina-carpenter-unveils-sweet-tooth-caramel-dream-fragrance/' LIMIT 1),NULL,'Credit does not prove sole authorship or results',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_kt10_appointment',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'role_appointment','Tory Burch appointment','Teklos becomes Tory Burch Chief Brand Officer in a newly created company role.','2026-07-07T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://wwd.com/business-news/human-resources/tory-burch-names-klitos-teklos-chief-brand-officer-1239054554/' LIMIT 1),NULL,'Company-specific title novelty only',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_kt10_snapshot',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'role_snapshot','Public role snapshot','Appointment and first-person profiles reviewed.','2026-07-26T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.linkedin.com/posts/klitosteklos_tory-burch-appoints-klitos-teklos-chief-brand-activity-7482395717081387008-NNk2' LIMIT 1),NULL,'Access-date snapshot',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_klitos_teklos_100','klitos-teklos-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'1.0.0','research/observatory/dossiers/klitos-teklos-1.0.0.md','96f5e9041bfdb55f5822a2604120519a6b4b77c7',
'{"claimIds":["obs_claim_kt10_c01","obs_claim_kt10_c02","obs_claim_kt10_c03","obs_claim_kt10_c04","obs_claim_kt10_c05","obs_claim_kt10_c06","obs_claim_kt10_c07","obs_claim_kt10_c08"],"relationshipIds":["obs_rel_kt10_tbllc","obs_rel_kt10_tory","obs_rel_kt10_roussel","obs_rel_kt10_brodie","obs_rel_kt10_studio","obs_rel_kt10_elc"],"eventIds":["obs_event_kt10_elc","obs_event_kt10_studio","obs_event_kt10_campaign","obs_event_kt10_appointment","obs_event_kt10_snapshot"],"observationIds":[],"limitations":["saturation_open","company_specific_firstness_only","worldwide_firstness_prohibited","role_built_flag_false","institutional_functions_preexisting","shared_authority","ownership_and_economics_unavailable","distributed_labor_incomplete","causal_performance_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.78,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_klitos_teklos_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='klitos-teklos' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_klitos_teklos_100',
'{"packageId":"klitos-teklos-1.0.0","claimsLoaded":8,"relationshipsLoaded":6,"eventsLoaded":5,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Company-specific firstness, institutional authority, distributed labor, ownership, performance, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
