-- Brad Keywell public-evidence review package 1.0.0.
-- Draft only. Does not publish, verify, score, infer psychology, or mark saturation complete.

UPDATE "ObservatoryCase"
SET "headline"='Founder, executive, investor, director and cultural creator across distinct institutions.',
    "summary"='A multi-institution portfolio separating companies, funds, boards, cofounders, employees, artists, nonprofits, university teaching, historic securities and personal economics.',
    "inclusionRationale"='Tests whether a public polymath portfolio can be represented without conflating roles, entities, ownership, valuation, institutional output, sole causality or psychology.',
    "roleBuiltFlag"=false,"verificationStatus"='in_review',"evidenceCoverage"=0.86,"publicStatus"='draft',"updatedAt"=CURRENT_TIMESTAMP
WHERE "slug"='brad-keywell';

INSERT INTO "ObservatorySource"
("id","url","title","publisher","sourceType","publishedAt","accessedAt","primarySource","publicStatus","createdAt")
VALUES
('obs_src_bk10_tko26','https://www.sec.gov/Archives/edgar/data/1973266/000119312526173833/d913980ddef14a.htm','TKO 2026 proxy','SEC / TKO Group Holdings','primary_regulatory_filing','2026-04-24T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bk10_tko8k','https://www.sec.gov/Archives/edgar/data/1973266/000119312524012566/d713319d8k.htm','TKO January 2024 Form 8-K','SEC / TKO Group Holdings','primary_regulatory_filing','2024-01-23T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bk10_grpn15','https://www.sec.gov/Archives/edgar/data/1490281/000119312515157079/d846113ddef14a.htm','Groupon 2015 proxy','SEC / Groupon','primary_regulatory_filing','2015-04-27T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bk10_form4','https://www.sec.gov/Archives/edgar/data/1114238/000122520815010344/xslF345X03/doc4.xml','Brad Keywell Groupon Form 4','SEC / Groupon','primary_regulatory_filing','2015-04-21T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bk10_bio','https://www.bradkeywell.com/files/Brad_Keywell_Bio_2024.pdf','Brad Keywell biography 2024','Brad Keywell','first_party_biography','2024-01-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bk10_1plus1','https://www.1plus1.vc/','1+1 Ventures','1+1 Ventures','primary_company_page',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bk10_chiideas','https://www.chicagoideas.com/people/brad-keywell','Brad Keywell profile','Chicago Ideas','primary_institutional_profile',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bk10_wndr','https://www.wndrmuseum.com/installations/chicago/we-are-all-artists','We Are All Artists','WNDR Museum','primary_museum_record','2020-01-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bk10_ff','https://www.futurefounders.com/bradkeywell/','Brad Keywell','Future Founders','primary_nonprofit_profile',NULL,'2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP),
('obs_src_bk10_booth','https://magazine.uchicago.edu/1104/chicago_journal/class-disruption.shtml','Class disruption','University of Chicago Magazine','institutional_publication','2011-04-01T00:00:00Z','2026-07-26T00:00:00Z',true,'public',CURRENT_TIMESTAMP)
ON CONFLICT ("url") DO UPDATE SET "title"=EXCLUDED."title","publisher"=EXCLUDED."publisher","sourceType"=EXCLUDED."sourceType","publishedAt"=EXCLUDED."publishedAt","accessedAt"=EXCLUDED."accessedAt","primarySource"=EXCLUDED."primarySource","publicStatus"='public';

INSERT INTO "ObservatoryClaim"
("id","caseId","claimType","statement","constructId","epistemicStatus","verificationStatus","confidence","permissibleLanguage","contradictionNote","publicStatus","createdAt","updatedAt")
VALUES
('obs_claim_bk10_c01',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'executive_role','TKO identifies Keywell as Uptake founder and executive chairman and as CEO from 2015 through 2019.','formal_role','primary_filing','unreviewed',NULL,'Founder and executive chairman of Uptake; former CEO.','No complete ownership, current valuation or unilateral-control inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bk10_c02',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'executive_role','TKO identifies Keywell as SkillHero founder, executive chairman and CEO since 2023.','formal_role','primary_filing','unreviewed',NULL,'Formal roles in a separate workforce-technology company.','No cap-table, performance or sole-labor inference.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bk10_c03',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'investment_role','1+1 Ventures is described as the operating and investment arm of Keywell family-office activity.','portfolio_relationship','corroborated','unreviewed',NULL,'Founder of a family-office investment and operating activity.','No complete asset, fund, ownership or personal-liquidity claim.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bk10_c04',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'role_transition','Keywell co-founded Lightbank and served as co-managing director during a bounded historic period.','role_transition','primary_filing','unreviewed',NULL,'Lightbank co-founder and former co-managing director.','Fund assets and portfolio exits are not personal wealth.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bk10_c05',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'ownership_boundary','Groupon filings document historic co-founder and director status and dated security-specific beneficial interests.','ownership_boundary','primary_filing','unreviewed',NULL,'Use only the filing date, holder, security class and attribution definition.','No current percentage or simple personal-ownership carry-forward.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bk10_c06',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'governance_role','Keywell became a TKO director on January 23, 2024 within a multi-person board.','formal_governance','primary_filing','unreviewed',NULL,'TKO director from the documented date.','Director status is not ownership or operating control.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bk10_c07',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'cultural_role','WNDR identifies a Keywell installation and institutional profiles identify him as founder and curator.','creative_participation','observed','unreviewed',NULL,'WNDR founder and curator with a documented artistic work.','No ownership of all art, sites, labor or rights.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bk10_c08',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'institutional_role','Chicago Ideas identifies Keywell as founder and chair of an institutional ideas platform.','distributed_creation','observed','unreviewed',NULL,'Founder and chair within a staffed platform.','Attendance and programming are not sole-person output.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bk10_c09',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'teaching_role','Institutional records document historic entrepreneurship teaching, including co-teaching with Eric Lefkofsky.','historic_role','observed','unreviewed',NULL,'Documented historic entrepreneurship teaching.','No automatic claim of a current 2026 faculty appointment.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_claim_bk10_c10',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'claim_restriction','No reviewed record establishes complete private cap tables, fund economics, IP schedules, contracts, labor attribution, current personal wealth, causal impact or psychological measurement.','claim_restriction','observed','unreviewed',NULL,'Public evidence establishes bounded roles and historic filing-specific interests.','Absence of public evidence is not proof that no private rights exist.','draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryClaimEvidence"
("id","claimId","sourceId","supportType","exactPassage","locator","analystNote","createdAt")
VALUES
('obs_ev_bk10_c01','obs_claim_bk10_c01',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312526173833/d913980ddef14a.htm' LIMIT 1),'supports',NULL,'Director biography','Current role chronology; ownership not inferred.',CURRENT_TIMESTAMP),
('obs_ev_bk10_c02','obs_claim_bk10_c02',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312526173833/d913980ddef14a.htm' LIMIT 1),'supports',NULL,'Director biography','Separate company and formal roles.',CURRENT_TIMESTAMP),
('obs_ev_bk10_c03','obs_claim_bk10_c03',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.1plus1.vc/' LIMIT 1),'supports',NULL,'Company description','Family-office activity; economics undisclosed.',CURRENT_TIMESTAMP),
('obs_ev_bk10_c04','obs_claim_bk10_c04',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312526173833/d913980ddef14a.htm' LIMIT 1),'supports',NULL,'Director biography','Historic co-managing period.',CURRENT_TIMESTAMP),
('obs_ev_bk10_c05','obs_claim_bk10_c05',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1490281/000119312515157079/d846113ddef14a.htm' LIMIT 1),'supports',NULL,'Beneficial ownership and director sections','Dated, security-specific snapshot.',CURRENT_TIMESTAMP),
('obs_ev_bk10_c06','obs_claim_bk10_c06',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312524012566/d713319d8k.htm' LIMIT 1),'supports',NULL,'Director appointment','Multi-person governance preserved.',CURRENT_TIMESTAMP),
('obs_ev_bk10_c07','obs_claim_bk10_c07',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.wndrmuseum.com/installations/chicago/we-are-all-artists' LIMIT 1),'supports',NULL,'Installation page','Specific work attribution only.',CURRENT_TIMESTAMP),
('obs_ev_bk10_c08','obs_claim_bk10_c08',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.chicagoideas.com/people/brad-keywell' LIMIT 1),'supports',NULL,'Institution profile','Institutional output not personal output.',CURRENT_TIMESTAMP),
('obs_ev_bk10_c09','obs_claim_bk10_c09',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://magazine.uchicago.edu/1104/chicago_journal/class-disruption.shtml' LIMIT 1),'supports',NULL,'Chicago Journal','Historic co-teaching evidence.',CURRENT_TIMESTAMP)
ON CONFLICT ("claimId","sourceId","supportType") DO NOTHING;

INSERT INTO "ObservatoryRelationship"
("id","fromCaseId","targetType","targetName","relationshipType","startedAt","endedAt","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_rel_bk10_uptake',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'organization','Uptake Technologies','founder_executive_chair_former_ceo','2015-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312526173833/d913980ddef14a.htm' LIMIT 1),NULL,'CEO role ended 2019; ownership not inferred',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bk10_skillhero',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'organization','SkillHero','founder_executive_chair_ceo','2023-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312526173833/d913980ddef14a.htm' LIMIT 1),NULL,'Separate company; cap table undisclosed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bk10_1plus1',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'organization','1+1 Ventures','founder_family_office_activity','2023-01-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.1plus1.vc/' LIMIT 1),NULL,'Assets and economics undisclosed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bk10_lightbank',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'organization','Lightbank','cofounder_former_comanaging_director','2012-01-01T00:00:00Z','2020-12-31T00:00:00Z','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312526173833/d913980ddef14a.htm' LIMIT 1),NULL,'Fund and portfolio economics not inferred',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bk10_tko',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'organization','TKO Group Holdings','director','2024-01-23T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312524012566/d713319d8k.htm' LIMIT 1),NULL,'Director within multi-person board',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_rel_bk10_wndr',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'organization','WNDR Museum','founder_curator_artist','2018-09-01T00:00:00Z',NULL,'unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.wndrmuseum.com/installations/chicago/we-are-all-artists' LIMIT 1),NULL,'Other artists, sites, employees and rights preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryEvent"
("id","caseId","eventType","title","description","occurredAt","precision","verificationStatus","publicStatus","sourceId","exactPassage","sourceLocator","createdAt","updatedAt")
VALUES
('obs_event_bk10_lightbank',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'formation','Lightbank co-founded','Keywell co-founded Lightbank; later filing supplies a bounded co-managing period.','2010-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312526173833/d913980ddef14a.htm' LIMIT 1),NULL,'Fund structure and economics not inferred',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_bk10_uptake',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'formation','Uptake founded','Keywell founded Uptake and served as CEO during 2015-2019.','2015-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312526173833/d913980ddef14a.htm' LIMIT 1),NULL,'Separate employees, investors and governance',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_bk10_wndr',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'formation','WNDR Museum launched','Keywell founded and curated an immersive art institution.','2018-09-01T00:00:00Z','month_approximate','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.wndrmuseum.com/installations/chicago/we-are-all-artists' LIMIT 1),NULL,'Institutional and artist labor preserved',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_bk10_skillhero',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'formation','SkillHero role begins','TKO biography dates Keywell founder, executive-chair and CEO roles from 2023.','2023-01-01T00:00:00Z','year','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312526173833/d913980ddef14a.htm' LIMIT 1),NULL,'Company ownership and performance undisclosed',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP),
('obs_event_bk10_tko',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'appointment','TKO board appointment','Keywell became a TKO director.','2024-01-23T00:00:00Z','day','unreviewed','draft',(SELECT "id" FROM "ObservatorySource" WHERE "url"='https://www.sec.gov/Archives/edgar/data/1973266/000119312524012566/d713319d8k.htm' LIMIT 1),NULL,'Board appointment only',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ObservatoryReviewPackage"
("id","packageId","caseId","version","dossierPath","contentHash","manifest","evidenceCoverage","status","createdAt","updatedAt")
VALUES
('obs_package_brad_keywell_100','brad-keywell-1.0.0',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'1.0.0','research/observatory/dossiers/brad-keywell-1.0.0.md','3686658e15de65028845b6da42f3724598da531f',
'{"claimIds":["obs_claim_bk10_c01","obs_claim_bk10_c02","obs_claim_bk10_c03","obs_claim_bk10_c04","obs_claim_bk10_c05","obs_claim_bk10_c06","obs_claim_bk10_c07","obs_claim_bk10_c08","obs_claim_bk10_c09","obs_claim_bk10_c10"],"relationshipIds":["obs_rel_bk10_uptake","obs_rel_bk10_skillhero","obs_rel_bk10_1plus1","obs_rel_bk10_lightbank","obs_rel_bk10_tko","obs_rel_bk10_wndr"],"eventIds":["obs_event_bk10_lightbank","obs_event_bk10_uptake","obs_event_bk10_wndr","obs_event_bk10_skillhero","obs_event_bk10_tko"],"observationIds":[],"limitations":["saturation_open","role_built_flag_false","multi_entity_portfolio","historic_securities_not_current_ownership","fund_and_family_office_economics_unverified","valuation_not_personal_wealth","institutional_labor_preserved","teaching_currentness_unresolved","ip_and_contracts_incomplete","causality_unmeasured","psychological_attributes_unmeasured","scoring_prohibited"]}'::jsonb,
0.86,'draft',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)
ON CONFLICT ("packageId") DO NOTHING;

INSERT INTO "ObservatoryAuditEvent"
("id","caseId","actorUserId","actorEmail","action","entityType","entityId","afterValue","note","createdAt")
VALUES
('obs_audit_brad_keywell_100',(SELECT "id" FROM "ObservatoryCase" WHERE "slug"='brad-keywell' LIMIT 1),'system:versioned-import','system@institutions-of-one.local','import_review_package','review_package','obs_package_brad_keywell_100',
'{"packageId":"brad-keywell-1.0.0","claimsLoaded":10,"relationshipsLoaded":6,"eventsLoaded":5,"publication":"draft","saturation":"open","roleBuiltFlag":false}'::jsonb,
'Public-evidence package imported as draft. Entity, ownership, fund, valuation, IP, labor, current-role, causality, psychology and saturation restrictions remain active.',CURRENT_TIMESTAMP)
ON CONFLICT ("id") DO NOTHING;
